### ISSUE TITLE
Unable to get PersistentPeers address 

### ISSUE THREAD

**Issue by nagarajmanjunath** [hyperledger/burrow#1012]
Please include in your bug report:

 `burrow version` (0.23.3+2018-12-20T12:00:18Z)
 `go version` (go1.10.4 darwin/amd64)
  operating system details (osx)

  what you expected to happen
 I have to generate the **PersistentPeers address**  using below cmd
 NODE_0_URL=`curl -s 127.0.0.1:20001/network | jq -r '.result.ThisNode | [.ID, .ListenAddress] | join("@") | ascii_downcase'`

  what actually happened
 when  I execute  **echo  $NODE_0_URL** after executing above code, i get empty value in NODE_0_URL. Unable get the **PersistentPeers address** 

Please do let me know how i can generate **PersistentPeers address** 
I am following the steps to create multiple validator from the doc [`multiple-validators`](https://github.com/hyperledger/burrow/blob/develop/docs/quickstart/multiple-validators.md)

**Comment by phymbert** [comment]
Hello, please confirm the node is started, and listen on port 20001. Then send us the output of `curl -s 127.0.0.1:20001/network` to check node network configuration.

**Comment by nagarajmanjunath** [comment]
@phymbert, Thanks for your response.
  I solved it.
  I have started the node with the same config has mention in doc and try to execute above cmd ,still 
  it was not displaying  value  **echo $NODE_0_URL**  in my terminal.

  I used the below code  to save the file. I copied the Node ID from the file,It worked

   NODE_0_URL=`curl -v -o ${GoPath}/{FolderName}/Node_address.txt   127.0.0.1:20001/network | jq -r '.result.ThisNode | [.ID, .ListenAddress] | join("@") | ascii_downcase'`

**Comment by phymbert** [comment]
Happy you solved it.
