### ISSUE TITLE
No Go files / can't load package

### ISSUE THREAD

**Issue by Villem-OskarOssip** [hyperledger/burrow#1015]
OS: macOS High Sierra version 10.13.6
Go version on mac: go1.11.5 windows/amd64

OS: Windows 10 Enterprise, 64-bit, version 1511
Go version on Windows: go1.11.5 darwin/amd64

Hello,

I am following burrow [installation instructions](https://github.com/hyperledger/burrow/blob/develop/docs/INSTALL.md). When trying to execute command:
 `go get github.com/hyperledger/burrow` 
command prompt returns: 
`can't load package: package github.com/hyperledger/burrow: no Go files in C:\Users\Villem Ossip\go\src\github.com\hyperledger\burrow`. 

I have successfully downloaded the latest version of GO and have set up the environment variable `$GOPATH`.  I made demo Go programm `hello.go`, from my desktop,  which successfully printed out 
what was expected.

Exactly same issue occured from both of my computers (mac and windows).

What might be the issue of this error?

**Comment by seanyoung** [comment]
That should probably be `go get -d github.com/hyperledger/burrow` 

Does that work?

**Comment by Villem-OskarOssip** [comment]
@seanyoung 
Gives me exactly the same error as before on both mac and windows.

**Comment by seanyoung** [comment]
@Villem-OskarOssip that message can just be ignored. Not sure how to make it go away

**Comment by Villem-OskarOssip** [comment]
I can't procceed to the next step which should be `cd $GOPATH/src/github.com/hyperledger/burrow`. There is no folder called `github.com` under `C:\Go\src`.

**Comment by seanyoung** [comment]
From your earlier message I assume go get has put them in C:\Users\Villem Ossip\go\src\github.com\hyperledger\burrow

**Comment by compleatang** [comment]
@Villem-OskarOssip going to close this issue, but feel free to reopen if you have any problems with burrow now that it is installed.!
