### ISSUE TITLE
[Build] Move to go module

### ISSUE THREAD

**Issue by phymbert** [hyperledger/burrow#1019]
Moving to `go mod` instead of `dep` and vendoring approach will bring us several advantages:
 
1. Reduce the line of code in the repo
1. Ease other framework to depend on burrow
1. Secure dependency management with hash and version management with `go.mod` and `go.sum`

**WARNING** It implies to update go lang minimal version requirement to 1.11.

More information can be found on the [go module documentation](https://github.com/golang/go/wiki/Modules).

**Comment by compleatang** [comment]
++

We now have the `final solution` for Go dependency management (which replaces the previous three `final solutions`). :-)

**Comment by phymbert** [comment]
oh yes, at least this one is in the core.
