### ISSUE TITLE
[Error] Can't connect multiple validators

### ISSUE THREAD

**Issue by mrsirja** [hyperledger/burrow#1050]
- [ ] `burrow version` (0.24.2+commit.v0.24.1-21-gac9771cc+2019-03-05)
- [ ] `go version` (go1.11 linux/amd64)
- [ ] `os` ( Ubuntu 16.04.1 x86_64)

### Expected to happen
Two peers connected with each other and empty blocks automatically created Sending vote message and Finalizing commit of block with 0 txs

### Actual Behavior
I am trying to connect multiple validator with the help of this [documentation](https://github.com/hyperledger/burrow/blob/develop/docs/quickstart/multiple-validators.md). I followed each step described in the documentation. But when i start node i see following error in logs.

.burrow_val0.toml logs:

> {"caller":"reactor.go:260","component":"Tendermint","inbound":0,"log_channel":"Trace","message":"Consensus ticker","module":"blockchain","numPending":0,"outbound":0,"run_id":"9344b8cd-3fdb-11e9-8ec5-ebff76d9d01f","scope":"tendermint.NewNode","time":"2019-03-06T06:47:12.435217803Z","total":0}
{"caller":"pool.go:167","component":"Tendermint","log_channel":"Trace","message":"Blockpool has no peers","module":"blockchain","run_id":"9344b8cd-3fdb-11e9-8ec5-ebff76d9d01f","scope":"tendermint.NewNode","time":"2019-03-06T06:47:12.435279749Z"}
{"caller":"switch.go:493","component":"Tendermint","err":"auth failure: handshake failed: EOF","log_channel":"Info","message":"Inbound Peer rejected","module":"p2p","numPeers":0,"run_id":"9344b8cd-3fdb-11e9-8ec5-ebff76d9d01f","scope":"tendermint.NewNode","time":"2019-03-06T06:47:12.435623463Z"}

.burrow_val1.toml logs:

> {"caller":"pex_reactor.go:399","component":"Tendermint","log_channel":"Info","message":"Ensure peers","module":"pex","numDialing":0,"numInPeers":0,"numOutPeers":0,"numToDial":10,"run_id":"992ecbc9-3fdb-11e9-8f96-b2d53295bac4","scope":"tendermint.NewNode","time":"2019-03-06T06:47:11.394169472Z"}
> {"caller":"pex_reactor.go:456","component":"Tendermint","log_channel":"Info","message":"No addresses to dial nor connected peers. Falling back to seeds","module":"pex","run_id":"992ecbc9-3fdb-11e9-8f96-b2d53295bac4","scope":"tendermint.NewNode","time":"2019-03-06T06:47:11.394258804Z"}
> {"caller":"pex_reactor.go:551","component":"Tendermint","log_channel":"Info","message":"Couldn't connect to any seeds","module":"p2p","run_id":"992ecbc9-3fdb-11e9-8f96-b2d53295bac4","scope":"tendermint.NewNode","time":"2019-03-06T06:47:11.394290864Z"}
> {"address":"0.0.0.0:20000","caller":"switch.go:561","component":"Tendermint","log_channel":"Info","message":"Dialing peer","module":"p2p","run_id":"992ecbc9-3fdb-11e9-8f96-b2d53295bac4","scope":"tendermint.NewNode","time":"2019-03-06T06:47:12.300685303Z"}
> {"caller":"reactor.go:260","component":"Tendermint","inbound":0,"log_channel":"Trace","message":"Consensus ticker","module":"blockchain","numPending":0,"outbound":0,"run_id":"992ecbc9-3fdb-11e9-8f96-b2d53295bac4","scope":"tendermint.NewNode","time":"2019-03-06T06:47:12.395341038Z","total":0}
> {"addr":"0.0.0.0:20000","caller":"switch.go:347","component":"Tendermint","err":"auth failure: conn.ID (d6018980487bfe80e77aad6b85f84e3248ef1c8a) dialed ID () missmatch","log_channel":"Info","message":"Error reconnecting to peer. Trying again","module":"p2p","run_id":"992ecbc9-3fdb-11e9-8f96-b2d53295bac4","scope":"tendermint.NewNode","time":"2019-03-06T06:47:12.424919227Z","tries":4}

Network of both nodes:
```
$ curl -s 127.0.0.1:20001/network
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "ThisNode": {
      "ID": "D6018980487BFE80E77AAD6B85F84E3248EF1C8A",
      "ListenAddress": "tcp://0.0.0.0:20000",
      "Network": "BurrowChain_B8849F-55AFD9",
      "Version": "0.30.1",
      "Channels": "4020212223303800",
      "Moniker": "BurrowChain_B8849F-55AFD9_Validator_74DD3ED70E2095D8706B0AC05BD1C8F7107A5F96",
      "TxIndex": "on"
    },
    "listening": true,
    "listeners": null,
    "n_peers": 0,
    "peers": []
  }
}

$ curl -s 127.0.0.1:30001/network
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "ThisNode": {
      "ID": "66942160C681F59141FCB9B61E3EE4D294A4C3E4",
      "ListenAddress": "tcp://0.0.0.0:30000",
      "Network": "BurrowChain_B8849F-55AFD9",
      "Version": "0.30.1",
      "Channels": "4020212223303800",
      "Moniker": "BurrowChain_B8849F-55AFD9_Validator_E59863D76BA20DD20D870C0574A6CC70F0252CB7",
      "TxIndex": "on"
    },
    "listening": true,
    "listeners": null,
    "n_peers": 0,
    "peers": []
  }
```

### Steps to Reproduction
`burrow spec -f2 | burrow configure -s- > .burrow_init.toml`
`burrow start --validator-index=0 --config=.burrow_val0.toml`
```
NODE_0_URL=`curl -s 127.0.0.1:20001/network | jq -r '.result.ThisNode | [.ID, .ListenAddress] | join("@") | ascii_downcase'`
sed -i s%PUT_HERE_NODE_0_ID@LISTEN_EXTERNAL_ADDRESS%${NODE_0_URL}% .burrow_val1.toml
```
`burrow start --validator-index=1 --config=.burrow_val1.toml`

### Files and full Logs

`.burrow_val0.toml` https://pastebin.com/JmqGvWiU
`.burrow_val1.toml` https://pastebin.com/18NMkdK7
`Node 1 logs` https://pastebin.com/jg47UxEx
`Node 2 logs` https://pastebin.com/yGY6gRGG

**Comment by silasdavis** [comment]
Hi there... couple of fiddly things here (I woul like to do a piece of work on 'node introductions' which would avoid the need for caring about node ids ahead of time).

1. Node IDs despite being public key addresses are treated as strings and are expected to be lower case
2. The tcp:// never used to be included, but when it is it must be before the ID

So:

You have:
```
  PersistentPeers = "D6018980487BFE80E77AAD6B85F84E3248EF1C8A@tcp://0.0.0.0:20000"
```
You need:
```
  PersistentPeers = "tcp://d6018980487bfe80e77aad6b85f84e3248ef1c8a@0.0.0.0:20000"
```

That crazy one-liner now gets's the tcp:// in the wrong place - though it does have the downcase function so not sure how you ended up with the upper case ID.

Let me know how you get on. I'm sure the docs/process could be improved here - and if you are willing to give that a go contributions are very welcome.

**Comment by mrsirja** [comment]
Hello, Thank you for your instance response.
Your solution perfectly worked. I am getting node id using below command line and manually putting into .burrow_val1.toml file:

`curl -s 127.0.0.1:20001/network | jq -r '.result.ThisNode.ID'`

I thought that can not be problem, because in previous version i tried with uppercase node id and it worked fine.

**Comment by silasdavis** [comment]
I've created a couple of issues referenced from this. Thanks for the detailed report. Let me know if you would like to get involved in the project (https://chat.hyperledger.org/channel/burrow-contributors).

**Comment by mrsirja** [comment]
How can i get involved in project. I will be happy to give my contribution
to this project.

**Comment by phymbert** [comment]
Hello @mrsirja, welcome, you can join us on the chat linked above by Silas and/or read the contribute.md and we will be happy to receive your PR, for example on improving documentation or if you want to start with codebase : check issues tagged as Help wanted / Good starter issue. Good luck
