### ISSUE TITLE
[Question] How Can i add peer in running network?

### ISSUE THREAD

**Issue by yuvi76** [hyperledger/burrow#1064]
Please include in your bug report:

- [ ] `burrow version` (0.24.2+2019-03-01T16:43:24Z)
- [ ] `go version` (1.11.3 linux/amd64)
- [ ] operating system details (Ubuntu 16.04.1)

### Expected Behavior
 I have 2 peer in network. Now i want to add 3rd peer without restarting chain from genesis block.

### Steps to reproduction
I have network of 2 validator. I had created using this [documentation](https://github.com/hyperledger/burrow/blob/develop/docs/quickstart/multiple-validators.md). 

Now in this network i want to add one more peer without restarting chain from genesis block.
How can i?

**Comment by gregdhill** [comment]
Hi @yuvi76, I've put together some [documentation](https://github.com/hyperledger/burrow/blob/develop/docs/quickstart/add-validators.md) which should explain the process of adding a new validator to a running chain. Let me know if you have any problems!
