### ISSUE TITLE
[Deploy] Support for yaml data stream or string-arg when using deploy

### ISSUE THREAD

**Issue by SchulerSimon** [hyperledger/burrow#1099]
It would be nice to have the ability to pass data-streams or strings to `burrow deploy` via another application.

Example use case: python-server using `subprocess.Popen(burrow deploy [...])`. 
Instead of creating a temp_deploy_file.yaml and passing this file to deploy, one could just pass an argument or stream to burrow with the deploy instructions.

@seanyoung advised me to make an Issue here after discussing in the chat.

**Comment by silasdavis** [comment]
So all these would require is for burrow deploy to read playbooks from stdin or would there be more to the streaming interface? Very happen to support reading from stdin as we do elsewhere, so PR welcome.

However I would also suggest that for machine-to-machine integration I would suggest skipping `burrow deploy` and integrating directly with our GRPC interfaces (there is good support for GRPC in python). In particular:

- https://github.com/hyperledger/burrow/blob/develop/protobuf/rpctransact.proto
- Also: https://github.com/silasdavis/burrow/blob/develop/integration/rpctest/helpers.go to see how the API works

I appreciate this does mean you would need to deal with ABI encoding locally.

However we have recently added ABI hosting within Burrow - something we are very interested in doing is providing Burrow-side EVM code formulation and exposing a more natural calling interface (i.e. call function by name and arguments) externally.

If you want to programmatically send transactions to Burrow this is probably better than trying to work through the text-base yaml interface of burrow deploy.
