### ISSUE TITLE
Empty blocks creation and interval settings are not respected

### ISSUE THREAD

**Issue by nmanchovski** [hyperledger/burrow#1110]
- [x] `burrow version` (docker image tag or branch if built from source)
v0.25.1 or develop branch

- [x] `go version` (if applicable)

go version go1.12.4 darwin/amd64

- [x] operating system details (osx/windows/linux)

osx and linux

- [x] what you expected to happen
 
After setting up: 
[Tendermint]
  CreateEmptyBlocks = false
  CreateEmptyBlocksInterval = 0

or 

[Tendermint]
  CreateEmptyBlocks = true
  CreateEmptyBlocksInterval = 1000

There should be no empty blocks created at all or within the preconfigured interval

- [x] what actually happened

New blocks are created just after the previous one

- [x] steps to reproduction

Configure the CreateEmptyBlocks to false in burrow.toml and follow the setup procedures of a new network from scratch. Observe block creation.

Instead of "message":"Broadcasting proposal heartbeat message"
new blocks with incremented height are created.

- [x] Investigation:

Related Tendermint issue has been filed before and can be found here:
https://github.com/tendermint/tendermint/issues/1995

In Tendermint this issue specific code is defined here:

https://github.com/tendermint/tendermint/blob/4253e67c07c69be6d7f7263ab03944ce30a9fc90/consensus/state.go#L828

where cs.needProofBlock(height) is always TRUE due to 

!bytes.Equal(cs.state.AppHash, lastBlockMeta.Header.AppHash)

After deeper investigation I have found that this misbehave of AppHash has been introduced in burrow with commit:

"Merge pull request #1000 from silasdavis/state" from 1.Feb

This commit is about changing the state to become merkelised.

The particular issue appear in 

https://github.com/hyperledger/burrow/blob/da78d34e40d823fe46ce97fb8afeefa46af33337/execution/execution.go#L319

Where before the merge of the mentioned commit the hash of 
hash, version, err := exe.state.Update(func(ws state.Updatable) error {

was remaining the same with empty blocks and changing only with a state change

where after the commit the hash is always different causing Tendermint to produce new block that needs to be proved as there was an app hash change

**Comment by g3d** [comment]
:+1: experiencing the same problem

**Comment by gregdhill** [comment]
I believe this was fixed in #1137, if @seanyoung could confirm then let's close this ticket.

**Comment by seanyoung** [comment]
Yes this fixed in that PR.
