### ISSUE TITLE
[Logs] Harmonize field types when using `duration`

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#1126]
The current difference in log output between the status and metrics servers cause an inherent type conflict within elasticsearch (and presumably other log management systems). See below.

![screenshot-logs monax io-2019 06 06-22-23-46](https://user-images.githubusercontent.com/590037/59067665-1a62a100-88aa-11e9-920b-9e20b9303c98.png)

**Comment by silasdavis** [comment]
@compleatang what is the third column?

**Comment by silasdavis** [comment]
fixed by #1172
