### ISSUE TITLE
Multiple Validator cannot generate Nodeaddress to connect Peers

### ISSUE THREAD

**Issue by Nagaraj007** [hyperledger/burrow#1128]
`burrow version`(0.25.1+commit.v0.25.0-51-ga11c9a4c+2019-06-08)
   `go version` (go version go1.12.5 darwin/amd64)
     operating system details (osx)
     what you expected to happen
     Trying to connect multiple validator 
      Using  cmd 
  `   "NODE_0_URL=curl -v -o ${GoPath}/{FolderName}/Node_address.txt 127.0.0.1:20001/network | jq -r '.result.ThisNode | [.ID, .ListenAddress] | join("@") | ascii_downcase'"` 
to generate Node_address.
     'what actually happened'
      Facing Error when i run above cmd. 
     'output'
  ```
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
         0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
        * TCP_NODELAY set
        * Connected to 127.0.0.1 (127.0.0.1) port 26656 (#0)
        > GET /network HTTP/1.1
       > Host: 127.0.0.1:26656
       > User-Agent: curl/7.54.0
       > Accept: */*
       > 
     { [34 bytes data]
       * Recv failure: Connection reset by peer
       * stopped the pause stream!
       100    68    0    68    0     0  50221      0 --:--:-- --:--:-- --:--:-- 68000         
       * Closing connection 0
        curl: (56) Recv failure: Connection reset by peer
```

**Comment by silasdavis** [comment]
This looks like a connection issue with the chain. Could we pick this up in https://chat.hyperledger.org/channel/burrow
