### ISSUE TITLE
[Deploy] Make burrow deploy suck less

### ISSUE THREAD

**Issue by silasdavis** [hyperledger/burrow#1134]
Burrow deploy has had its insides refactored and cleaned up quite a bit (though there is more to do there too). However through its many iterations the UX has languished. Trying to use burrow deploy to do adhoc queries and scripting is quite painful, luckily most of the issues are fairly trivial, but a thousand cuts...

Here's a list before I forget:

- Cannot handle absolute paths for deploy files
- Inconsistent path handling in general (still broken with more options than necessary)
- Logging output is ugly and broken (unsupported value type everywhere)
- Deploy files are unnecessarily verbose - jobs should only require a name if they need to be referenced - n-back references might be a reasonable alternative. We could go further and come up with a lexable language rather than a verbose mini-language in YAML (particularly assertions). What should it mean to be declarative here.
- At least use go templates rather hand inconsistent hand-rolled version
- Mixture of deploy/query/test - could be made cleaner - this is bigger
- Why can't we right parseable (e.g. jq-able) output to stdout rather than files. In a script files get overwritten on repeated iteratoins.
- Put 'normal' output on stdout not stderr for better scripting
- ABI discovery should work over a directory with a bag of ABIs without explicit address naming (ala vent)
- Panics everywhere, e.g. query contract error references null call, we are not checking `TxExectuion.Exeception` everywhere even though we must.
- Name reg lookups could be integrated inline into templates

More sweepingly, we might more quickly reach a better solution by developing `burrow tx` with more compact functional language.

There are also different use cases for:
- Repeatable contract deployment - declarative - only really depending on deployed address
- Test assertions
- Live system interaction/scripting/queries (this particularly might more reasonably belong to `burrow tx`)

**Comment by seanyoung** [comment]
Each message should include the job name it originated from

**Comment by silasdavis** [comment]
It seems increasingly likely that we will use typescript code to deploy contacts using the JS API rather than continuing to maintain Burrow deploy for this purpose.
