### ISSUE TITLE
[Vent] Systematize Logging

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#1136]
See below....

![screenshot-logs monax io-2019 06 12-22-08-09](https://user-images.githubusercontent.com/590037/59386508-bdaa2f00-8d5e-11e9-94f3-3128e203f710.png)

**Comment by silasdavis** [comment]
Beautiful... @seanyoung could you take a look with the projection change

**Comment by silasdavis** [comment]
fixed by #1172 - in so far as we decided this is about JSON serialising nested values where possible.
