### ISSUE TITLE
[Dump] Catchup block 0

### ISSUE THREAD

**Issue by gregdhill** [hyperledger/burrow#1145]
With a dump-restore, previous events are stored in block zero which is an issue when catching up a node as Tendermint will not replay this block, resulting in an appHash collision.

**Comment by silasdavis** [comment]
The idea with restore is that we explicitly do not pay for consensus on transactions committed in a previous chain, so Tendermint not gossiping those is as-designed.

Effectively on a restore chain genesis == genesis doc + dump state. They should be distributed together
