### ISSUE TITLE
Cannot install burrow module

### ISSUE THREAD

**Issue by lucianosilva44** [hyperledger/burrow#1150]
Hello,

When I try to build the module with **make build**, I get this:

go: cannot use modules with build cache disabled
go: cannot use modules with build cache disabled
Checking code for formatting style compliance.

The terminal stays infinitevely in this screen and nothing happens. Someone knows what could be happening?

**Comment by gregdhill** [comment]
What version of go are you using @lucianosilva44?

**Comment by lucianosilva44** [comment]
1.11.4, @gregdhill

**Comment by gregdhill** [comment]
Could you try again with 1.12 @lucianosilva44?

**Comment by silasdavis** [comment]
Looks like a system issue, if still having trouble we are happy to help in: https://chat.hyperledger.org/channel/burrow

Closing for now.
