### ISSUE TITLE
IBM HYPERLEDGER FABRIC LICENSING COST

### ISSUE THREAD

**Issue by CaptainUday** [hyperledger/burrow#1168]
Please include in your bug report:

- [ ] `burrow version` (docker image tag or branch if built from source)
- [ ] `monax version` (if applicable)
- [ ] `go version` (if applicable)
- [ ] `docker version` (if applicable)
- [ ] operating system details (osx/windows/linux)
- [ ] what you expected to happen
- [ ] what actually happened
- [ ] steps to reproduction

If issue is a feature request, tell us why this feature is useful.

**Comment by CaptainUday** [comment]
Hi Everyone, 
I am working on a proposal where i need to propose to my clients to build an de centralized app for their business support using Hyperledger fabric. Request if someone can help in understanding what will be the costing for procuring its license from IBM. Will they charge us on per  node wise ? How do we estimate how many nodes will be there at proposal stage??
Any suggestions/ recommendations would be helpful 

Regards

**Comment by gregdhill** [comment]
Please forward your question to the Hyperledger fabric team [here](https://gerrit.hyperledger.org/r/#/admin/projects/fabric).
