### ISSUE TITLE
can't load package: package github.com/hyperledger/burrow: no Go files in

### ISSUE THREAD

**Issue by VtpVlan-oo7** [hyperledger/burrow#1175]
i am using this just for install hyperledger-burrow but facing this issue-->

$ go get -d github.com/hyperledger/burrow

can't load package: package github.com/hyperledger/burrow: no Go files in /home/vtp/go/src/github.com/hyperledger/burrow

**Comment by gregdhill** [comment]
@VtpVlan-oo7 I believe that error can be ignored, please refer to [this issue](https://github.com/hyperledger/burrow/issues/1015).

**Comment by seanyoung** [comment]
Since commit https://github.com/hyperledger/burrow/commit/ad85e420defe974c6939695443a21e99d7ce4967 this should not happen any more.
