### ISSUE TITLE
[Deploy] Multiple validators cannot generate blocks.

### ISSUE THREAD

**Issue by ccconnor** [hyperledger/burrow#1179]
I followed instuctions about [Multiple validators](https://github.com/hyperledger/burrow/blob/develop/docs/quickstart/add-validators.md) , but no blocks were generated. I put the detailed log [here](https://www.dropbox.com/s/kocfmpq3cxm67x0/burrow000.log?dl=0).
I found these logs
```
{"addr":"50B5C58A9FD85CC25B7D9D5EDAAD07113DFF4962@127.0.0.1:26657","caller":"switch.go:351","component":"tendermint","err":"auth failure: conn.ID (dd873187266902d66d5fc0565c1075b761fb3cce) dialed ID (50B5C58A9FD85CC25B7D9D5EDAAD07113DFF4962) mismatch","height":0,"log_channel":"Info","message":"Error reconnecting to peer. Trying again","module":"p2p","run_id":"c8c6c44e-b4d1-11e9-830c-9fdf2165aaf0","scope":"tendermint.NewNode","time":"2019-08-02T03:01:18.789439Z","tries":1}
```
So I guess maybe it's related with PersistentPeers of burrowxxx.toml, but I'm not sure.

By the way, is there any documentation to explain what's the usage of deploy-script and how to write a deploy-script?

**Comment by silasdavis** [comment]
Yep, this is a bug, thanks for bringing it to my attention, It should be fixed in #1184
