### ISSUE TITLE
[Docs] Adding new validator not working

### ISSUE THREAD

**Issue by lucianoacsilva** [hyperledger/burrow#1181]
Hello,

When I was trying to add a new validator in an existing network, the last command of the process fails:

burrow deploy -c 127.0.0.1:10997 --mempool-signing=true --address=$OLD_VALIDATOR deploy.yaml

The error that is thrown is the following:

ERROR: error querying validators with jq-style query Set..Power: . does not exist.log_channel=Info message="JOBS THAT FAILED" count=1

Obs.: When defining the variable OLD_VALIDATOR, the command in the terminal:

OLD_VALIDATOR=$(cat burrow000.toml | grep ValidatorAddress | cut -d \" -f2)

does not work, since the field ValidatorAddress does not exist in the generated **.toml** files. Then, I defined it as one of the addresses of the already existing validators. The rest of the steps I did as described in documentation.

**Comment by silasdavis** [comment]
Can you provide your deploy,yaml?

**Comment by ccconnor** [comment]
@silasdavis The same problem with me. Apparently, the deploy yaml is as [Add Validator](https://github.com/hyperledger/burrow/blob/develop/docs/quickstart/add-validators.md) shows.

The doc tries to extract ValidatorAddress from burrow000.toml, while there isn't a ValidatorAddress in burrow000.toml at all.

Could developers quickly go over these docs?

**Comment by silasdavis** [comment]
I've added the issue above as the more permanent way to fix this class of issues.

> Could developers quickly go over these docs?

I will try and find some time to do this, though I would rather spend a bit more time fixing all of the docs by integration testing them.

In the meantime - if you are able to see a way to do a tactical fix on these docs it would be much appreciated :) - any 'proof of work' from users is a good way for me to choose how to allocate my limited time - i.e. if it its worth your time fixing our docs, its worth my time prioritising your issues.

**Comment by silasdavis** [comment]
Since this is non-specific and we have recently done quite a bit of general work on docs: #1266  #1243 

Closing this
