### ISSUE TITLE
Test of vm_test.go don't run all the opcodes when using vm.Call()

### ISSUE THREAD

**Issue by madiazp** [hyperledger/burrow#1244]
To test the call of a smart contract I added : 
```
 func TestBigModExp(t *testing.T) {
	cache := NewState(newAppState(), blockHashGetter)
	ourVm := NewVM(newParams(), crypto.ZeroAddress, nil, logger)
	account1 := newAccount(cache, "1")
	account2 := newAccount(cache, "101")

	var gas uint64 = 10000
	fmt.Printf("Testing bigModExp, inputs \n")
	bc := hex.MustDecodeString("608060405234801561001057600080fd5b50610109806100206000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063783ce45814602d575b600080fd5b606a60048036036060811015604157600080fd5b810190808035906020019092919080359060200190929190803590602001909291905050506080565b6040518082815260200191505060405180910390f35b60008060405160208152602080820152602060408201528560608201528460808201528360a082015260208160c083600060056107d05a03f1915080519250508060c957600080fd5b81915050939250505056fea265627a7a723158207adae9fda357a576526c1acb8c3c6b3866b1b7831b82d833cd31c8190d23b5e964736f6c634300050b0032")
	input := hex.MustDecodeString("783ce458000000000000000000000000000000000000000000000000000000000000000b00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000009")
	//addr := crypto.Address{11, 101}
	ourVm.debugOpcodes = true
	out1, err := ourVm.Call(cache, NewNoopEventSink(), account1, account2, bc, input, 0, &gas)

	fmt.Printf("output: %x", out1)

	require.NoError(t, err)

}
```

in the [vm_test.go](https://github.com/hyperledger/burrow/blob/develop/execution/evm/vm_test.go) file. The output was:

`Testing bigModExp, inputs 
(1) (C47907ABD2A80492CA9388B05C0E382518FF3960) FE9362E30831F55EEB1F0D837CD5F98848386EF9 (code=297) gas: 10000 (d) 783CE458000000000000000000000000000000000000000000000000000000000000000B00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000009
(pc) 0   (op) PUSH1          (st) 0    (gas) 10000 => 0x30303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303830
(pc) 2   (op) PUSH1          (st) 1    (gas) 9999 => 0x30303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303430
(pc) 4   (op) MSTORE         (st) 2    (gas) 9998 => 0x30303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303830 @ 0x40
(pc) 5   (op) CALLVALUE      (st) 0    (gas) 9996 => 0
(pc) 6   (op) DUP1           (st) 1    (gas) 9995 => [1] 0x0000000000000000000000000000000000000000000000000000000000000000
(pc) 7   (op) ISZERO         (st) 2    (gas) 9993 30303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030 == 0 = 1
(pc) 8   (op) PUSH2          (st) 2    (gas) 9991 => 0x30303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303130
(pc) 11  (op) JUMPI          (st) 3    (gas) 9990 ~> 16
(pc) 16  (op) JUMPDEST       (st) 1    (gas) 9988
(pc) 17  (op) POP            (st) 1    (gas) 9988 => 0x30303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030
(pc) 18  (op) PUSH2          (st) 0    (gas) 9987 => 0x30303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030313039
(pc) 21  (op) DUP1           (st) 1    (gas) 9986 => [1] 0x0000000000000000000000000000000000000000000000000000000000000109
(pc) 22  (op) PUSH2          (st) 2    (gas) 9984 => 0x30303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303230
(pc) 25  (op) PUSH1          (st) 3    (gas) 9983 => 0x30303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030
(pc) 27  (op) CODECOPY       (st) 4    (gas) 9982 => [0, 32, 265] 6080604052348015600F57600080FD5B506004361060285760003560E01C8063783CE45814602D575B600080FD5B606A60048036036060811015604157600080FD5B810190808035906020019092919080359060200190929190803590602001909291905050506080565B6040518082815260200191505060405180910390F35B60008060405160208152602080820152602060408201528560608201528460808201528360A082015260208160C083600060056107D05A03F1915080519250508060C957600080FD5B81915050939250505056FEA265627A7A723158207ADAE9FDA357A576526C1ACB8C3C6B3866B1B7831B82D833CD31C8190D23B5E964736F6C634300050B0032
(pc) 28  (op) PUSH1          (st) 1    (gas) 9979 => 0x30303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030
(pc) 30  (op) RETURN         (st) 2    (gas) 9978 => [0, 265] (265) 0x6080604052348015600F57600080FD5B506004361060285760003560E01C8063783CE45814602D575B600080FD5B606A60048036036060811015604157600080FD5B810190808035906020019092919080359060200190929190803590602001909291905050506080565B6040518082815260200191505060405180910390F35B60008060405160208152602080820152602060408201528560608201528460808201528360A082015260208160C083600060056107D05A03F1915080519250508060C957600080FD5B81915050939250505056FEA265627A7A723158207ADAE9FDA357A576526C1ACB8C3C6B3866B1B7831B82D833CD31C8190D23B5E964736F6C634300050B0032
output: 6080604052348015600f57600080fd5b506004361060285760003560e01c8063783ce45814602d575b600080fd5b606a60048036036060811015604157600080fd5b810190808035906020019092919080359060200190929190803590602001909291905050506080565b6040518082815260200191505060405180910390f35b60008060405160208152602080820152602060408201528560608201528460808201528360a082015260208160c083600060056107d05a03f1915080519250508060c957600080fd5b81915050939250505056fea265627a7a723158207adae9fda357a576526c1acb8c3c6b3866b1b7831b82d833cd31c8190d23b5e964736f6c634300050b0032PASS`

If you see the [assembly](https://github.com/madiazp/Crypto-Gov/blob/master/tests/testissue.txt) of the code it seems that the test ignored the data. and all its opcodes. But if I use this smart contract in a running environment it works fine (with some other errors related to the contract). 

PD: This is the sol [contract](https://github.com/madiazp/Crypto-Gov/blob/master/tests/testissue.sol) It won't work because the precompiled contract with address 0x05 is not implemented yet. But it should run all the opcodes.
PD2: I switched Call with call and delegateCall, and use different kinds of addresses, but I had the same output.

**Comment by silasdavis** [comment]
This might be clearer once I have a change to run your test, but:

> code it seems that the test ignored the data.

Could you expand this a bit I don't quite follow: which data and ignored how?

**Comment by madiazp** [comment]
@silasdavis I mean that the test only ran the [portion](https://github.com/madiazp/Crypto-Gov/blob/master/tests/testissue.txt#L22) from L1 to L22 and finished with the RETURN opcode returning the code copied with the [CODECOPY](https://github.com/madiazp/Crypto-Gov/blob/master/tests/testissue.txt#L20) opcode without jumping to the `.data `section.

**Comment by silasdavis** [comment]
@madiazp would you be able to encode your expected failure as a failing test, i.e. assert the output that you expect to see. This will make it easier to investigate.

Also could you provide the solidity you have compiled and I can make this a test fixture (you can do this yourself by copying the solidity file next to the test and running `make solidity`).

> But if I use this smart contract in a running environment

By this do you mean fabric chaincode?

**Comment by madiazp** [comment]
@silasdavis  I remade the test like this:

```
func TestBigModExp(t *testing.T) {
	// var needed for the call
	cache := NewState(newAppState(), blockHashGetter)
	ourVm := NewVM(newParams(), crypto.ZeroAddress, nil, logger)
	account1 := newAccount(cache, "1")
	account2 := newAccount(cache, "101")
	// solidity  uint256 with value: 1
	sucess := "0000000000000000000000000000000000000000000000000000000000000001"

	var gas uint64 = 10000
	fmt.Printf("Testing bigModExp, inputs \n")
	// The solidity compiled contract. It call bigmodexp with b,e,m inputs and compare the result with proof, where m is the mod, b the base, e the exp, and proof the expected result.
	bc := hex.MustDecodeString("608060405234801561001057600080fd5b5061012a806100206000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063b4f7c68d14602d575b600080fd5b607460048036036080811015604157600080fd5b8101908080359060200190929190803590602001909291908035906020019092919080359060200190929190505050608a565b6040518082815260200191505060405180910390f35b600080600060405160208152602080820152602060408201528760608201528660808201528560a082015260208160c083600060056107d05a03f1925080519150508160d557600080fd5b8084141560e65760019250505060ed565b6000925050505b94935050505056fea265627a7a723158206604ca9dcdd8b165e037bcf20d7f160c2ff6be12a0b1cef5101768564fa1cae664736f6c634300050b0032")
	// the input test, this is a bigmodexp call. The base is 3, the exp is 2, the mod is 8 and the result is 1, 3^2 % 8 = 1
	input := hex.MustDecodeString("b4f7c68d0000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000001")
	//addr := crypto.Address{11, 101}
	// debugging opcodes
	ourVm.debugOpcodes = true
	out1, err := ourVm.Call(cache, NewNoopEventSink(), account1, account2, bc, input, 0, &gas)

	fmt.Printf("output: %x", out1)

	require.NoError(t, err)
	// if the sol contract didn't return uint256 1 the test fails
	require.Equal(t, sucess, fmt.Sprintf("%x", out1))
}
```
The solidity contract is:
```
pragma solidity ^0.5.0;

contract SimpleStorage {

    function expmod(uint256 base, uint256 e, uint256 m, uint256 proof) public returns (uint256) {
        bool success;
        uint256 o;
    
         assembly {
        
           let p := mload(0x40)
           // store data assembly-favouring ways
           mstore(p, 0x20)             // Length of Base
           mstore(add(p, 0x20), 0x20)  // Length of Exponent
           mstore(add(p, 0x40), 0x20)  // Length of Modulus
           mstore(add(p, 0x60), base)  // Base
           mstore(add(p, 0x80), e)     // Exponent
           mstore(add(p, 0xa0), m)     // Modulus
           // call modexp precompile
           success := call(sub(gas, 2000), 0x05, 0, p, 0xc0, p, 0x20)
           // gas fiddling
           
            o := mload(p)
           
        
            
        }
        require(success);
        if (proof == o){
            return 1;
        }
        return 0;
    }
}
```
The  `success := call(sub(gas, 2000), 0x05, 0, p, 0xc0, p, 0x20)` execution calls the 5th precompiled eth contract (bigModExp). e is the exp, m the mod and proof is the expected result. Note if you don't have BigModExp implemented in the native.go this contract will not work.

> By this do you mean fabric chaincode?

Yes, the fabric + fabric-chaincode-evm + burrow

**Comment by silasdavis** [comment]
@madiazp the problem here is you are sending the contract creation bytecode not the deployed bytecode. That is why your return value is the contract itself.

See how we handle this with our test fixtures in: https://github.com/hyperledger/burrow/pull/1264/files#diff-77d123266b7a37ee11de9b08a9b33f4dR1482-R1509

**Comment by madiazp** [comment]
Thanks @silasdavis , the deployed bytecode did the trick. closing the issue
