### ISSUE TITLE
Native contarct addresses wrong padded

### ISSUE THREAD

**Issue by madiazp** [hyperledger/burrow#1245]
The native contracts are [added to a map](https://github.com/hyperledger/burrow/blob/develop/execution/evm/native.go#L48) with a crypto.Address of it eth address.

This make the number of the address right padded, while the caller addr is left padded. For example the key in the map of the 4th native is `0400000000000000000000000000000000000000` while the caller addr is `0000000000000000000000000000000000000004` (I debugged this with Printf, sorry the dirtiness). So the condition [if IsRegisteredNativeContract(address)](https://github.com/hyperledger/burrow/blob/develop/execution/evm/vm.go#L859) always fails.

**Comment by silasdavis** [comment]
Thanks @madiazp I've resolved this is a refactored I have done, your work looks good though and I will merge and resolve conflicts when we get your changes integrated
