### ISSUE TITLE
Using Webassembly to compile smart contracts in Burrow

### ISSUE THREAD

**Issue by stanta** [hyperledger/burrow#1248]
@silasdavis , What about using Webassembly to compile smart contracts in Burrow, like EWASM?

**Comment by silasdavis** [comment]
We have experimental WASM support based around: https://github.com/hyperledger-labs/solang

That is for compiling Solidity currently. We are interested in other languages. We need to iterate on how we expose our native functionality, our syscall equivalents, but ultimately we'd like to support any language with an LLVM backend. 

I am doing some groundwork for this now: https://github.com/hyperledger/burrow/pull/1249

Is there anything in particularly you have in mind?

**Comment by stanta** [comment]
have this version restrictions of stack deep like original Solidity?

**Comment by stanta** [comment]
its seems very perspective! keep us informed in roadmap!
