### ISSUE TITLE
is this just a money grab ? project is abandoned

### ISSUE THREAD

**Issue by AndreiD** [hyperledger/burrow#1255]
I wouldn't have looked at your project, but it seems that a company that I interact with is using this...

Upon trying to learn more about it, I stumble on dead links on the readme/wiki.... oO.. how can this be possible!

**I smell a money grab here... from IBM, Intel or whomever wanted to sponsor this.**

There is no development going on
The links from the readme are dead
the links from the wiki are dead
Issues are piling
pull requests from people that want to contribute are not looked at

------------
So you tell me ? is this project dead ?

**Comment by AndreiD** [comment]
"Hyperledger Burrow was originally contributed by Monax and co-sponsored by Intel. "

so please don't throw the open source shit in my face, you have been paid to work on it.

Now have at least the decency to add some maintainers if you don't care anymore about this project

**Comment by silasdavis** [comment]
Are you having a bad day?

> There is no development going on

This project is extremely active see: https://github.com/hyperledger/burrow/graphs/code-frequency

In the last month (from GH pulse):
> On master, 176 files have changed and there have been 12,269 additions and 1,001 deletions. 

> co-sponsored by Intel. 

The sponsorship in question was sponsorship of our project proposal (see: https://www.hyperledger.org/wp-content/uploads/2017/06/HIP_Burrowv2.pdf) by Dan Middleton who happens to work for Intel. We have received no monetary or development assistance from Intel. I have requested this wording is changed to avoid confusion.


> The links from the readme are dead
the links from the wiki are dead

Pull requests welcome :) We are in the process of a major refactor of our docs that will be accompanied by a blog post shortly.

> Issues are piling

43 open / 409 closed

> pull requests from people that want to contribute are not looked at

Most of them are from my colleagues at Monax, they are looked at, discussed, and will be merged in due course.

> so please don't throw the open source shit in my face, you have been paid to work on it.

I don't recall throwing anything in your face. Yes, I am paid by https://monax.io/company/, how do you feed your family?
