### ISSUE TITLE
Cannot Execute "burrow configure" from Helm chart

### ISSUE THREAD

**Issue by dizzy721** [hyperledger/burrow#1286]
**Describe the Bug**
Following the instructions from [here](https://github.com/helm/charts/tree/master/stable/burrow) under the Prerequisites section, the script fails to execute beginning at [line 72 in initialize.sh](https://github.com/helm/charts/blob/master/stable/burrow/initialize.sh#L72).  The script outputs "Error: incorrect usage" and exits.  

**To Reproduce**

1. Download latest Burrow binary and extract to somewhere in user's PATH (I used /usr/local/sbin/) 

2. Follow the steps [under Prerequisites](https://github.com/helm/charts/tree/master/stable/burrow#prerequisites)
```
curl -LO https://raw.githubusercontent.com/helm/charts/master/stable/burrow/initialize.sh
CHAIN_NODES=4 CHAIN_NAME="my-release" ./initialize.sh
```

**Expected Behavior**
I would anticipate that the burrow configure command would complete without error and generate the configure files for the next steps. 

**Technical Details**
- [0.28.2 - Linux x86_64 binary, Also confirmed with latest (0.28.2) Docker image] Burrow Version 
- [N/A] Go Version (if applicable)
- [18.09.9]  Docker Version (if applicable)
- [Linux/Ubuntu 18.04.3 ] Operating System (linux)

**Additional Context**
I get the same output when running an altered script that uses the Docker image as well.  Running the same commands outside of the initialize.sh also returns "Error: incorrect usage".  I seem to be able to successfully build the genesis spec.  I've also tried updating the option "--keysdir" to "--keys-dir" and have had no luck. 

Not sure if this is the appropriate place to file a bug so please let me know if I should move it elsewhere.

**Comment by gregdhill** [comment]
Thanks for reporting this @dizzy721, I've submitted a PR to resolve it here > https://github.com/helm/charts/pull/17863

Once that's in, please try again and let us know how you get on!

**Comment by dizzy721** [comment]
Greg I appreciate the quick response! I was able to execute the steps for the Helm chart successfully after pulling in the change you made.  

Cheers!
