### ISSUE TITLE
Burrow Roadmap

### ISSUE THREAD

**Issue by silasdavis** [hyperledger/burrow#1331]
To discuss:

## Core WASM/contract work
- Finish proxy work (is there a better name?)
- Make solidity contract call WASM function (complete engines work)
- Implement eWASM support
- Emit event from WASM contract

## Burrow offline state
- Run state over single contract without consensus
- Attempt to sync updates back
- Permit conflict resolution

Result: limited counter-party offline transacting

## Burrow offline triggers
- Call WASM smart contract from Blackstone activity
- Trigger Blackstone activity completion from `burrow proxy` command (i.e. scriptable agreements)
- `burrow proxy` sync events and ping HTTP service

Result: 'offline' scriptable burrow

Overall idea: blend multiple online/offline state channels. Do we need state subspaces for this?

**Comment by gregdhill** [comment]
Also: https://github.com/hyperledger/burrow/pull/1343

**Comment by silasdavis** [comment]
This ticket is quite speculative and does not have a clear definition of done, some of this would probably be better on wiki.
