### ISSUE TITLE
Consider deprecating burrow deploy

### ISSUE THREAD

**Issue by gregdhill** [hyperledger/burrow#1341]
**Is your feature request related to a problem? Please describe.**
Burrow deploy is not well documented, therefore hard to learn. It is also error-prone, in that libraries to link must be explicitly known. Lastly, it is not efficiently parallelizable.

**Describe the solution you'd like**
Remove the deploy tooling and focus improvements on `burrow tx` and the incoming typescript client.

**Describe alternatives you've considered**
We could move deploy tooling to the typescript client.

**Comment by silasdavis** [comment]
Do not underestimate the effort involved in maintaining a decent CLI like `burrow tx` is is currently far from polished. That said with the various corner cases and oddities in parts of burrow deploy coupled with the fact an actual programming language with actual syntax and grammar is better suited to quite a bit of what burrow deploy has grown to do (e.g. back-substitution).

The original idea of burrow deploy is to have a fairly declarative text recipe for deploying contracts to the chain. This isn't at all a bad idea. It does seem like javascript would serve this purpose particularly if a typescript backend for things like auto-completion.

However I do slightly fear the feature-creep this would introduce into burrow.js if that becomes our primary tool for deployment/testing/glue. Burrow deploy has a certain amount of dealing with keys, calling out to solc, etc that is kind of messy. I wouldn't want to inflict this on the core runtime library code, but equally I wouldn't want to lose this functionality.

What would an MVP for burrow-deploy.js look like?
