### ISSUE TITLE
Is there a way to set MaxBytes for tendermint through burrow config?

### ISSUE THREAD

**Issue by ghoshbishakh** [hyperledger/burrow#1356]
I want to limit the block size for tendermint. Can we do that through some burrow config?

For example setting MaxBytes.
https://github.com/tendermint/tendermint/blob/master/types/params.go#L43

**Comment by gregdhill** [comment]
We are intentionally opinionated about what we expose from Tendermint, however if you wish to add this please see the configuration setup [here](https://github.com/hyperledger/burrow/blob/master/consensus/tendermint/config.go#L64).

**Comment by silasdavis** [comment]
Could you tell us a bit about your motivation for doing this, what are you trying to achieve? This can help us to understand it it should be part of a broader feature.

**Comment by silasdavis** [comment]
Closing for lack of response
