### ISSUE TITLE
Is a transaction finalised when the burrow deploy command finished?

### ISSUE THREAD

**Issue by devos50** [hyperledger/burrow#1361]
I have a question about transaction finalisation in Burrow. When submitting a transaction to Burrow using the `burrow deploy` command, is the transaction finalized/committed when the playbook finishes? I need to get the time between submitting a transaction and its finalisation. Or is there any other way to reliably get the transaction confirmation times?

Thanks!

**Comment by gregdhill** [comment]
What `burrow deploy` will do is synchronously broadcast each transaction in your playbook, effectively waiting at each step to finalize. When it has been included in a block, your node should be able to fetch the block header from the store ([here](https://github.com/hyperledger/burrow/blob/8a98ad0158aabf411e2d7f7cd4a402f754bfa119/bcm/blockchain.go#L252)) which contains a [timestamp](https://github.com/tendermint/tendermint/blob/master/types/block.go#L328) from Tendermint. If you have the transaction hash, I might suggest that you utilize the web3 RPC to pull the header ([here](https://github.com/hyperledger/burrow/blob/8a98ad0158aabf411e2d7f7cd4a402f754bfa119/rpc/eth.go#L374)).
