### ISSUE TITLE
How does offline transaction signing work in burrow?

### ISSUE THREAD

**Issue by sueno51** [hyperledger/burrow#1363]
I am a bit familiar with how offline transaction signing works for hyperledger fabric. I am not sure how offline transaction signing works in burrow. Can someone guide me with an example or a documentation?

**Comment by gregdhill** [comment]
Thanks for your question @sueno51! The current setup involves something called 'mempool signing', whereby any node with access to the corresponding keys for an [input account](https://github.com/hyperledger/burrow/blob/master/protobuf/payload.proto#L42) will sign an unsigned transaction received over GRPC. In addition, the same server also exposes an endpoint to explicitly [sign raw transactions](https://github.com/hyperledger/burrow/blob/master/rpc/rpctransact/transact_server.go#L70). I would note however that we intend to change the core functionality of transaction signing [here](https://github.com/hyperledger/burrow/pull/1247), so watch this space!
