### ISSUE TITLE
Can't get Burrows Seeding node to work when not running locally

### ISSUE THREAD

**Issue by multimedial** [hyperledger/burrow#1386]
Trying to set up a minimal burrow network cconsisting of one validator node plus a seeding node in order to test the setup described [here](https://hyperledger.github.io/burrow/#/tutorials/6-seeding) but NOT running on the local machine (no use of ip address 127.0.0.1) but on two separate machines in a network instead.  NOTE: the local examples DOES RUN fine for me (once one has figured out that the instructions for the seeders toml file are to be derived from the toml file from the validators - otherwise the seeder and the validators will be on different networks and won't connect. The tutorial is wrong or misleading in that regards, see also [this](https://www.element14.com/community/groups/internet-of-things/blog/2020/03/06/blockchain-hyperledger-burrow-set-up-a-distributed-ledger) for a better example ).

The two machines are on same network, respective ip addresses are
192.168.178.61 (for the seed node)
192.168.178.89 (for the validator)

Both spin up, and get to see each other (excerpt from the seed node log file):

 ```
 "caller": "http_server.go:84",
  "component": "RPC_Info",
  "duration": "314.719µs",
  "height": 0,
  "log_channel": "Info",
  "message": "Served RPC HTTP response",
  "method": "GET",
  "remote_address": "127.0.0.1:56202",
  "run_id": "4805d7f8-97b8-11ea-8b71-2987a90dcbd6",
  "scope": "NewKernel()",
  "status": 200,
  "time": "2020-05-16T21:13:28.859935634Z",
  "url": "/network"
}
{
  "caller": "service.go:138",
  "component": "tendermint",
  "height": 0,
  "impl": "Peer{MConn{192.168.178.87:39014} 9bfaab74127c6e92259f647b95c1712cfd972b73 in}",
  "log_channel": "Info",
  "message": "Starting Peer",
  "module": "p2p",
  "peer": "9bfaab74127c6e92259f647b95c1712cfd972b73@192.168.178.87:39014",
  "run_id": "4805d7f8-97b8-11ea-8b71-2987a90dcbd6",
  "scope": "tendermint.NewNode",
  "time": "2020-05-16T21:13:47.461628436Z"
}
{
  "caller": "service.go:138",
  "component": "tendermint",
  "height": 0,
  "impl": "MConn{192.168.178.87:39014}",
  "log_channel": "Info",
  "message": "Starting MConnection",
  "module": "p2p",
  "peer": "9bfaab74127c6e92259f647b95c1712cfd972b73@192.168.178.87:39014",
  "run_id": "4805d7f8-97b8-11ea-8b71-2987a90dcbd6",
  "scope": "tendermint.NewNode",
  "time": "2020-05-16T21:13:47.461836693Z"
}
{
  "caller": "switch.go:817",
  "component": "tendermint",
  "height": 0,
  "log_channel": "Info",
  "message": "Added peer",
  "module": "p2p",
  "peer": "Peer{MConn{192.168.178.87:39014} 9bfaab74127c6e92259f647b95c1712cfd972b73 in}",
  "run_id": "4805d7f8-97b8-11ea-8b71-2987a90dcbd6",
  "scope": "tendermint.NewNode",
  "time": "2020-05-16T21:13:47.462067597Z"
}
{
  "caller": "switch.go:347",
  "component": "tendermint",
  "height": 0,
  "log_channel": "Info",
  "message": "Stopping peer gracefully",
  "module": "p2p",
  "run_id": "4805d7f8-97b8-11ea-8b71-2987a90dcbd6",
  "scope": "tendermint.NewNode",
  "time": "2020-05-16T21:13:47.575895375Z"
}
{
  "caller": "service.go:166",
  "component": "tendermint",
  "height": 0,
  "impl": "Peer{MConn{192.168.178.87:39014} 9bfaab74127c6e92259f647b95c1712cfd972b73 in}",
  "log_channel": "Info",
  "message": "Stopping Peer",
  "module": "p2p",
  "peer": "9bfaab74127c6e92259f647b95c1712cfd972b73@192.168.178.87:39014",
  "run_id": "4805d7f8-97b8-11ea-8b71-2987a90dcbd6",
  "scope": "tendermint.NewNode",
  "time": "2020-05-16T21:13:47.576103688Z"
}
{
  "caller": "service.go:166",
  "component": "tendermint",
  "height": 0,
  "impl": "MConn{192.168.178.87:39014}",
  "log_channel": "Info",
  "message": "Stopping MConnection",
  "module": "p2p",
  "peer": "9bfaab74127c6e92259f647b95c1712cfd972b73@192.168.178.87:39014",
  "run_id": "4805d7f8-97b8-11ea-8b71-2987a90dcbd6",
  "scope": "tendermint.NewNode",
  "time": "2020-05-16T21:13:47.576293964Z"
}
{
  "caller": "reactor.go:473",
  "component": "tendermint",
  "height": 0,
  "log_channel": "Info",
  "message": "Stopping gossipDataRoutine for peer",
  "module": "consensus",
  "peer": "Peer{MConn{192.168.178.87:39014} 9bfaab74127c6e92259f647b95c1712cfd972b73 in}",
  "run_id": "4805d7f8-97b8-11ea-8b71-2987a90dcbd6",
  "scope": "tendermint.NewNode",
  "time": "2020-05-16T21:13:47.66248807Z"
}
{
  "caller": "reactor.go:615",
  "component": "tendermint",
  "height": 0,
  "log_channel": "Info",
  "message": "Stopping gossipVotesRoutine for peer",
  "module": "consensus",
  "peer": "Peer{MConn{192.168.178.87:39014} 9bfaab74127c6e92259f647b95c1712cfd972b73 in}",
  "run_id": "4805d7f8-97b8-11ea-8b71-2987a90dcbd6",
  "scope": "tendermint.NewNode",
  "time": "2020-05-16T21:13:47.662757493Z"
}
{
  "caller": "reactor.go:744",
  "component": "tendermint",
  "height": 0,
  "log_channel": "Info",
  "message": "Stopping queryMaj23Routine for peer",
  "module": "consensus",
  "peer": "Peer{MConn{192.168.178.87:39014} 9bfaab74127c6e92259f647b95c1712cfd972b73 in}",
  "run_id": "4805d7f8-97b8-11ea-8b71-2987a90dcbd6",
  "scope": "tendermint.NewNode",
  "time": "2020-05-16T21:13:49.462323818Z"
}
```

It would be my understanding that the new peer should now be visible and part of the network, but nothing shows up: 

```
}pi@raspberrypi4B:~/$ curl -s 127.0.0.1:10001/network
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "ThisNode": {
      "ID": "39E469F37394134CB7F189EF3B11FC4A3687C230",
      "ListenAddress": "192.168.178.61:10000",
      "Network": "BurrowChain_50A6DC-401D26",
      "Version": "0.33.1",
      "Channels": "4020212223303800",
      "Moniker": "BurrowChain_50A6DC-401D26_Node_0B9B8BA52CD84C9C9628F5A983ED8EC4713B292D",
      "TxIndex": "off"
    },
    "listening": true,
    "listeners": null,
    "n_peers": 0,
    "peers": []
  }
}
```

**To Reproduce**
Maybe i am missing something, but I was basically trying to mimic the steps described here
https://hyperledger.github.io/burrow/#/tutorials/6-seeding for a private network setup and not on one local machine.

**Expected Behavior**
I would expect the seed node to appear on the validator's network (doesn't happen)
I would also expect the validator to appear on the seed node's network (doesn't happen either)

**Technical Details**
- [ ] Burrow Version (docker image tag or branch if built from source)
0.30.4+commit.v0.30.4-45-g1d7c4f60+dirty.654da7a3+2020-05-06

- [ ] Operating System (osx/windows/linux)
Raspbian buster

**Additional Context**
This is for a thesis - time is ticking away for me and I am stuck. Any help would be much appreciated. I also tried to reach the Hyperledger Burrow chat, but the page won't load for me (https://chat.hyperledger.org/channel/burrow).

Thank you for any insight or help, I feel like I must be missing something but I can't figure it out. I also joined the burrow_seed.toml and burrow_node.toml files.

[burrow_seed_toml.zip](https://github.com/hyperledger/burrow/files/4639248/burrow_seed_toml.zip)
[burrow_init_toml.zip](https://github.com/hyperledger/burrow/files/4639250/burrow_init_toml.zip)

**Comment by silasdavis** [comment]
It is a while since I used seed nodes but IIRC they do not maintain active connections to the network so they cannot act as validators, see https://kb.certus.one/peers.html:

> Seed nodes are only there to provide an up-to-date list of peers of the network. If a node is configured to run as a seed node, it will actively search the network for new peers and store them in its addressbook. However, it will not maintain active connections with the peers it queries. Connections from a seed node are meant to be short-lived in order to just query the other peers addressbook, learn about its new peers and then disconnect again. If you specify a seed node in the config of your node it will try to dial it on startup to retrieve an up-to-date addressbook as well as a list of peers on the network to bootstrap its connections.

Seed nodes will connect to a peer, exchange peers they know about from their addressbook, then shutdown again. See also: https://docs.tendermint.com/master/spec/p2p/node.html
