### ISSUE TITLE
Extending Consensus algorithms other than Tendermint. Custom Consensus?

### ISSUE THREAD

**Issue by Gauthamastro** [hyperledger/burrow#1396]
**Is your feature request related to a problem? Please describe.**
Tendermint Consensus is good, but I want to test and use my version of consensus algorithms that differ from Tendermint mechanisms.

**Describe the solution you'd like**
A generic consensus interface like the one that was provided in go-ethereum
 [Pull Request in geth](https://github.com/ethereum/go-ethereum/pull/3817)

**Describe alternatives you've considered**
Directly modifying the existing code to integrate other consensus algos but it can be too much time-consuming. it will be easier if there is a general consensus interface.

**Comment by silasdavis** [comment]
As soon as we have three consensus engines we can have a go at writing a generic consensus interface. I don't fancy our chances of just writing one down.

Can you make it fit ABCI? I'd be interested in a prototype of it is interesting for you to do. But I am very wary of the complexity of supporting multiple consensus engines. I'd almost call it a non goal.

**Comment by Gauthamastro** [comment]
> As soon as we have three consensus engines we can have a go at writing a generic consensus interface. I don't fancy our chances of just writing one down.
> 
> Can you make it fit ABCI? I'd be interested in a prototype of it is interesting for you to do. But I am very wary of the complexity of supporting multiple consensus engines. I'd almost call it a non goal.

Ohh okay, I thought it was available. Anyway I moved on to Substrate Framework.
