### ISSUE TITLE
Cannot run eWasm example on Burrow [EEI not supported]

### ISSUE THREAD

**Issue by sxysun** [hyperledger/burrow#1401]
**Describe the Bug**
When deploying the example contract [`foobar.sol`](https://hyperledger.github.io/burrow/#/reference/wasm) on burrow using [solang](https://github.com/hyperledger-labs/solang), which compiles the contract down to ewasm, we encounter the following problem of unknown [EEI](https://ewasm.readthedocs.io/en/mkdocs/eth_interface/) imports, specifically, the EEI of `getCallValue`. The error message is as follows:

```
executing deploy with command line:
burrow deploy --wasm --jobs=100 --chain=127.0.0.1:20997 --keys=127.0.0.1:20997    --address Full_0 --mempool-signing --set key2_addr=B45A407C2EBD15989DC8AB83284B31B0B6FB7C10 --set addr2_pub=860AD13F2223C22DDECEAD7C97191CC52B8F0A858527FA17FE5DC85D7F1520A8 --set key1=Full_0 --set key2=Participant_0 --proposal-create test-ewasm*/deploy.yaml
log_channel=Info message="Using chain" Chain=127.0.0.1:20997 Signer=127.0.0.1:20997
log_channel=Info message="Loading Playbook File."
log_channel=Info message="Loading playbook file" path=/Users/dshe/go/src/github.com/hyperledger/burrow/tests/jobs_fixtures/test-ewasm filename=/Users/dshe/go/src/github.com/hyperledger/burrow/tests/jobs_fixtures/test-ewasm/deploy.yaml
log_channel=Info message="*****Executing Job*****" JobName=defaultAddr Type=Account
log_channel=Info message="Setting Account" account=Full_0
log_channel=Info message="*****Executing Job*****" JobName=key2_addr Type=Set
log_channel=Info message="Setting Variable" result=B45A407C2EBD15989DC8AB83284B31B0B6FB7C10
log_channel=Info message="*****Executing Job*****" JobName=addr2_pub Type=Set
log_channel=Info message="Setting Variable" result=860AD13F2223C22DDECEAD7C97191CC52B8F0A858527FA17FE5DC85D7F1520A8
log_channel=Info message="*****Executing Job*****" JobName=key1 Type=Set
log_channel=Info message="Setting Variable" result=Full_0
log_channel=Info message="*****Executing Job*****" JobName=key2 Type=Set
log_channel=Info message="Setting Variable" result=Participant_0
log_channel=Info message="*****Executing Job*****" JobName=deployFoobar Type=Deploy
log_channel=Info message="Contract path" path=foobar.sol
log_channel=Info message="Warning during contract compilation" warning="foobar.sol:8:5-11:0: warning: function declared can be declared ‘view’"
log_channel=Info message="Saving Binary" contract=foobar
log_channel=Info message="Using keys server" server=127.0.0.1:20997
log_channel=Info message="Using mempool signing"
log_channel=Info message="There has been an error talking to your Burrow chain" defAddr=C9F239591C593CB8EE192B0009C6A0F2C9F8D768 rawErr="rpc error: code = Unknown desc = error 16 - Error 16: execution aborted: exception during transaction execution: call error: ewasm: unknown function getCallValue"
ERROR: Error finalizing contract deploy foobar.sol: 
There has been an error talking to your Burrow chain using account C9F239591C593CB8EE192B0009C6A0F2C9F8D768.

rpc error: code = Unknown desc = error 16 - Error 16: execution aborted: exception during transaction execution: call error: ewasm: unknown function getCallValue

log_channel=Info message="JOBS THAT FAILED" count=1
log_channel=Info message="Playbook result" jobNo=0 file=test-ewasm/deploy.yaml error="Error finalizing contract deploy foobar.sol: \nThere has been an error talking to your Burrow chain using account C9F239591C593CB8EE192B0009C6A0F2C9F8D768.\n\nrpc error: code = Unknown desc = error 16 - Error 16: execution aborted: exception during transaction execution: call error: ewasm: unknown function getCallValue\n\n" time=570.143803ms
Cleaning up...
Killing burrow with PID 17351
Waiting for burrow to shutdown...

Tests complete. Tests are Red. :(
Failures in:
not supplied by test
```

**To Reproduce**
- Make new test directory `ewasm-test` under `tests/jobs_fixtures` and add test files deploy.yaml and foobar.sol, which are examples obtainable from [Burrow's official website for wasm support](https://hyperledger.github.io/burrow/#/reference/wasm)
- Add `--wasm` in `deploy_cmd` in deploy.sh.
- Run `./deploy.sh ewasm-test`.

**Expected Behavior**
The example contract `foobar` should be deployable without bugs, and we should be able to interact with the contract using burrow.

**Technical Details**
- [ 98458787aa8f92d2d4b7b4b431df985dde7bfa5c] Burrow Version (docker image tag or branch if built from source)
- [1.14 ] Go Version (if applicable)
- [ ] Docker Version (if applicable)
- [ macOS Catalina 10.15.5] Operating System (osx/windows/linux)
- [0.1.2] solang compiler

**Additional Context**
After discussion with @dshe-certik who ran the tests and discovered this bug, we think the crux of this bug is this excerpt of the error message below:
```
rpc error: code = Unknown desc = error 16 - Error 16: execution aborted: exception during transaction execution: call error: ewasm: unknown function getCallValue
```
which says that the `getCallValue` function is unknown, but in the eWasm specification it states that this function is a part of the Ethereum Environment Interface (EEI). And EEIs are supposed to be supported by the VM, which in this case would be burrow's VM. And if we inspect the decompiled WebAssembly text version of the contract `foobar.sol`, we notice the following:
```
(module
  (type (;0;) (func))
  (type (;1;) (func (param i32) (result i32)))
  (type (;2;) (func (param i32 i64 i64 i32)))
  (type (;3;) (func (param i32)))
  (type (;4;) (func (param i32 i32)))
  (type (;5;) (func (result i32)))
  (type (;6;) (func (param i32 i32 i32)))
  (import "ethereum" "getCallValue" (func (;0;) (type 3)))
  (import "ethereum" "revert" (func (;1;) (type 4)))
  (import "ethereum" "getCodeSize" (func (;2;) (type 5)))
  (import "ethereum" "codeCopy" (func (;3;) (type 6)))
  (import "ethereum" "finish" (func (;4;) (type 4)))
  (import "ethereum" "memory" (memory (;0;) 2 2))
 .....
```
that the function `getCallValue` is the first EEI to be imported. So is it that all the EEIs are not supported at the moment? Or the bug is with the way we run the tests?

**Comment by seanyoung** [comment]
You need commit https://github.com/hyperledger/burrow/commit/cf68b271785b75eb60bd343a4c3469d7db475853 in your burrow.

Solang has implemented value transfers and needs to check whether value is sent to non-payable functions, and revert the transaction if its. functions are non-payable in Solidity unless marked with `payable`.

**Comment by seanyoung** [comment]
IOW use latest master
