### ISSUE TITLE
"too many open files" on high TPS transaction sending

### ISSUE THREAD

**Issue by nayuta-ueno** [hyperledger/burrow#1404]
**Describe the Bug**

burrow returns "too many open files" error on high TPS transaction sending.

**To Reproduce**
1. `burrow spec -p1 -f1 | burrow configure -s- > burrow.toml`
2. `burrow start --validator=0`
3. run below JavaScript(Node.js) to send transactions(customize LOOP, ADDR_FROM, IPADDR).

```javascript
/////////////////////
// send txs
const LOOP=1000;
// from burrow.toml
const ADDR_FROM="0xBB327029C6B1DFFF61162F4E1729262310D2B91A";   // first [GenesisDoc.Accounts]
const ADDR_TO="0x40911E49A856784E4D151FED2F5BB0AAA08D8C91";     // second [GenesisDoc.Accounts]
const IPADDR='http://localhost:26660';
/////////////////////


const Web3 = require('web3');
const web3 = new Web3();
web3.setProvider(new web3.providers.HttpProvider(IPADDR));

const fn = async() => {
    let nonce = await web3.eth.getTransactionCount(ADDR_FROM);
    console.log("nonce=" + nonce);
    for (let loop=0; loop < LOOP; loop++) {
        const tx = {from: ADDR_FROM, to: ADDR_TO, value:"100", gasPrice:"0", nonce: nonce};
        web3.eth.sendTransaction(tx, function(err, hash) {
            if (!err) {
                console.log("hash=" + hash);
            } else {
                console.log("err=" + err);
            }
        })
        .on('receipt', function(receipt){
            console.log('receipt=' + JSON.stringify(receipt.transactionHash));
        })
        nonce++;
    }
}
fn();
```

Then web3.js return errors: 

```
err=Error: Returned error: error signing transaction: open /something/workdir/.keys/data/BB327029C6B1DFFF61162F4E1729262310D2B91A.json: too many open files
```

**Expected Behavior**

Success all `eth_sendTransaction`.

**Technical Details**
- [x] Burrow Version (docker image tag or branch if built from source)
  - bee910099478c7982b71752a1c329f3314a009ba
- [x] Go Version (if applicable)
  - go version go1.15.2 linux/amd64
- [ ] Docker Version (if applicable)
  - not used
- [x] Operating System (osx/windows/linux)
  - Ubuntu 20.04 64bit

**Additional Context**
none.

**Comment by silasdavis** [comment]
You are spawning 1000 concurrent HTTP requests with this code, each TCP connection underlying that uses a file descriptor, and the default number of file descriptors is 1024 per process on linux. If you try `sudo ulimit -n unlimited` then I would expect this to work fine.

If you think this is a file descriptor leak from Burrow could you post the output `ls -l /proc/<pid of burrow>/fd` at some point before it fails and I will reopen this ticket.
