### ISSUE TITLE
not able to run  make install_burrow

### ISSUE THREAD

**Issue by Amanrahmani** [hyperledger/burrow#1407]
everytime I attempt to run the command it returns make: *** No rule to make target 'install_burrow'.  Stop.

**To Reproduce**
 export PATH=$PATH:$HOME/go/bin/burrow
k@LAPTOP-GP34K4U6:~$ export GOPATH=$HOME/go
k@LAPTOP-GP34K4U6:~$ cd $HOME/go && mkdir bin && cd bin && mkdir burrow
-bash: cd: /home/k/go: No such file or directory
k@LAPTOP-GP34K4U6:~$ sudo su
[sudo] password for k:
root@LAPTOP-GP34K4U6:/home/k# cd #Home/bin && mkdir bin && cd bin
root@LAPTOP-GP34K4U6:~# cd $Home/bin && mkdir hello && cd hello && mkdir burrow
root@LAPTOP-GP34K4U6:/bin/hello# cd $home/bin/hello/burrow
root@LAPTOP-GP34K4U6:/bin/hello/burrow# make install_burrow
make: *** No rule to make target 'install_burrow'.  Stop.

**Expected Behavior**
i expected for the program to run and then to go on with the other commands to deploy the chain

**Technical Details**
go version 1.13.8 Linux kernel ubuntu 20.04 lts  on windows 10

**Additional Context**
everything i did

**Comment by gregdhill** [comment]
There is no target `install_burrow`, where did you see this? Please use `make install` instead.

**Comment by Amanrahmani** [comment]
issue #1041 im still getting the same *** No rule to make target 'install'.  Stop. 
issue

**Comment by silasdavis** [comment]
Not sure what issue you might be having, what OS/environment are you using:

![works-for-me](https://user-images.githubusercontent.com/99715/98681611-369e2380-2363-11eb-8716-cc6aff2473dc.gif)

**Comment by Amanrahmani** [comment]
ubuntu 20.04.1 lts shell on windows 10 also im fairly certain im in the same directory as your showing in your gif but there might have been some issue with the downlad or something since my ls is showing a lot less then yours
![Screenshot (83)](https://user-images.githubusercontent.com/68824763/98723643-a6f77580-2360-11eb-83fd-4d37b9f79a83.png)

**Comment by Amanrahmani** [comment]
nvm re cloned the github code and its working now. so now i just do the burrow spec -v1 | burrow configure -s- | burrow start -c-
 comand right?
