### ISSUE TITLE
State cache storage overwrite during VM memory write

### ISSUE THREAD

**Issue by yoongbok-lee** [hyperledger/burrow#1417]
**Describe the Bug**
Since state cache only refers to a byte slice from VM's memory, overwriting the section will overwrite the storage.

**To Reproduce**
(only tested on EWASM)
Deploy a simple contract with get-then-set function. Call it to get return value of 0 (because the return value is overwritten), and the storage is set to return value.

**Expected Behavior**
State cache storage should be only be written through `SetStorage`

**Technical Details**
- [ ] Burrow Version (docker image tag or branch if built from source)
- [ ] Go Version (if applicable)
- [ ] Docker Version (if applicable)
- [ ] Operating System (osx/windows/linux)

**Additional Context**
Burrow version: 0.30.5 (with addition of EWASM hashing native contracts)

To fix it, https://github.com/hyperledger/burrow/blob/759545605d6072675b2ebc5545e8ffa0a447a012/acm/acmstate/state_cache.go#L170

need to be replaced with
```
	tmp := make([]byte, len(value))
	copy(tmp, value)
	accInfo.storage[key] = tmp
```

**Comment by silasdavis** [comment]
Thanks for this!

The error is in the WASM implementation, I have fixed in #1423 

Incidentally you should not need your workaround to get access to the precompiles once #1422 is merged. It would be great to get some more testing done. @seanyoung is planning to follow up with full eWASM/Solang support so this should see a lot more love.

**Comment by yoongbok-lee** [comment]
Thanks! Is there a plan to release the features in the near future?

**Comment by silasdavis** [comment]
They will be on master shortly which you can build or depend on directly. We'll merge a few more tests in along with some other improvements. I expect to make a formal release in the next couple of weeks.
