### ISSUE TITLE
Wasm ETH interface missing components

### ISSUE THREAD

**Issue by yoongbok-lee** [hyperledger/burrow#1424]
**Is your feature request related to a problem? Please describe.**
Currently the WASM implementation is missing a few opcodes such as `create` or `log`. (also missing in the wasm call PR)

**Describe the solution you'd like**
Fully implement the ETH interface, as specified in https://github.com/ewasm/design/blob/master/eth_interface.md .

**Describe alternatives you've considered**
If there isn't any plan to add them in near future, I can work on it and submit a PR for review.

**Comment by seanyoung** [comment]
The wasm-call PR needs to be merged before further work can be done, this is close to being completed.

There quite a few to implement; most of them just require a few lines of code and a test. Any help would be appreciated! We have to divide up the work.

- log
- create
- debug.printMem
- getBlockHash
- getBlockDifficulty
- getGasLeft
- getBlockGasLimit
- getBlockTimestamp
- getTxGasPrice
- getTxOrigin
- getBlockCoinbase

**Comment by yoongbok-lee** [comment]
Great! I'll work on those and create a PR soon. I have a couple of questions regarding those features:
1. Could you give me a little more context on `debug.printMem`? Not sure what it should do (I guess print out some portion of memory for debugging)?
2. There aren't any ways currently to get either block difficulty or tx gas price on the blockchain/parameter interface/struct. Should I add them along the way?

Thanks!

**Comment by seanyoung** [comment]
`debug.printMem` should just log a string to the burrow log. The following solidity will call `debug.printMem()` when using Solang:
```
contract c {
    function f(int64 arg1, bool arg2) public {
        print("arg:{} arg:{}".format(arg1, arg2));
   }
}
```

- block difficulty does not make any sense with tendermint concencus
- burrow does not charge for gas, so there is no gas price (this is something that should be added)

Note that `selfdestruct()` also needs implementing.

Thank you very much.

**Comment by yoongbok-lee** [comment]
I don't think I'm familiar enough with Solang to implement `debug.printMem`, so I'll try to work on it after I finish working on the opcodes.

Also, I think there is a bug with the `call` implementation. I'm testing deployment on my chain with `soll` compiler, and `call` should accept `value` as third argument where others shouldn't. Currently it has `value` as third arguments for all types of calls.

here's the code I used to bypass the error:
```
			case "call":
				valuePtr := int(uint32(vm.GetCurrentFrame().Locals[2]))
				value = binary.LittleEndian.Uint64(vm.Memory[valuePtr : valuePtr+32])
				dataPtr := int(uint32(vm.GetCurrentFrame().Locals[3]))
				dataLen := int(uint32(vm.GetCurrentFrame().Locals[4]))
				data = vm.Memory[dataPtr : dataPtr+dataLen]
			default:
				dataPtr := int(uint32(vm.GetCurrentFrame().Locals[2]))
				dataLen := int(uint32(vm.GetCurrentFrame().Locals[3]))
				data = vm.Memory[dataPtr : dataPtr+dataLen]
			}
```
of course the code can be much cleaner.

**Comment by seanyoung** [comment]
Great find, that's also broken in solang.

Note that according to https://github.com/ewasm/design/blob/master/eth_interface.md `callCode` does have a value argument.

**Comment by yoongbok-lee** [comment]
OK I'll include the fix in the PR as well.

**Comment by seanyoung** [comment]
I've created a PR for the debug.printMem functions

**Comment by yoongbok-lee** [comment]
Thanks, I finished first implementation in #1427, but haven't tested it yet.

**Comment by silasdavis** [comment]
It sounds like this is now merged, I know we need to make a release which I am now working on.
