### ISSUE TITLE
burrow spec -v1 | burrow configure .... cannot unmarshal array into Go struct field 

### ISSUE THREAD

**Issue by dgome** [hyperledger/burrow#1426]
I have downloaded the release binaries and in the latest versions and executing the command:

burrow spec -v1 | burrow configure -s- | burrow start -c-

it indicates the error:

`could not obtain config: json: cannot unmarshal array into Go struct field Account.Accounts.Permissions of type permission.AccountPermissions`

from version 0.25.0 backwards it does not produce an error.

**Comment by silasdavis** [comment]
Thanks for the report. Which version of Burrow are you using, can you provide the output of`burrow --version` 

I am not seeing this on master or with the latest version v0.30.5 (`0.30.5+commit.v0.30.5+2021-03-04`) locally.

**Comment by silasdavis** [comment]
Tentatively closing this, will reopen if there is repro
