### ISSUE TITLE
How much should I fill in for burrow to metamask chainid? 

### ISSUE THREAD

**Issue by bitbeb** [hyperledger/burrow#1449]
Hi @bitbeb I recently changed our behaviour here, before we were using a stub ChainID but that offers no reply protection.

I am currently using the following code: https://github.com/hyperledger/burrow/blob/master/crypto/signature.go#L120-L122 to establish a web3-compatible integer ChainID based on our string one. You would need your tool to provide that integer value (check how any CLI wants it to be encoded).

If there is a better standard I could use here vis-a-vis string-to-integer chain id please let me know.

Hello! May I ask what I got according to your method big.int The result indicates that the number is too large. The chainid of my buorrw is "chainname": "burrowchain"_ FAB3C1",
"ChainId": "BurrowChain_ FAB3C1-AB0FD1",

https://github.com/hyperledger/burrow/blob/master/crypto/signature.go#L120-L122 to

chainID：98398506046391950612428913232117193968501817186218405401892336238027608097865

**Comment by silasdavis** [comment]
Seems like we have an issue for this here: https://github.com/hyperledger/burrow/issues/1411

Let me know if this should be reopened for some reason
