### ISSUE TITLE
I would like to ask BOSS , now version 0.31.3 can connect with metamask, 

### ISSUE THREAD

**Issue by bitbeb** [hyperledger/burrow#1476]
I would like to ask CTO, now version 0.31.3 can connect with metamask, and see the balance, so I try to transfer from, but metamask has been waiting, unable to confirm the transaction, what's the problem? Thank you for your reply!

**Comment by bitbeb** [comment]
I use burrow version 0.31.3 to generate towl, and then add chainid = "1869"
BurrowDir = ".burrow"
[GenesisDoc]
GenesisTime = 2021-03-15T16:26:51Z
ChainName = "MyLovelyChain"
ChainID = "1869"
[ GenesisDoc.Params ]
We successfully joined metamask and saw the initial balance, but we were unable to make a transfer transaction or deploy the contract with Remix because it had been waiting and could not confirm successfully

**Comment by bitbeb** [comment]
http://161.117.51.184:26658/
http://161.117.51.184:26660
chainid="1860"

Can you test some? thank you!

**Comment by bitbeb** [comment]
RPC endpoints use different chain IDS: 4.1716850

**Comment by bitbeb** [comment]
[root@iZt4n6feax4zkua4wka8hnZ ~]# cd /opt/burrow/bin
[root@iZt4n6feax4zkua4wka8hnZ bin]# SENDER=39832F04F5FBED26882547DB6C518C6478D3BE5C
[root@iZt4n6feax4zkua4wka8hnZ bin]# RECIPIENT=B811B02E4277028988D9833F9A6FD9720BB5430A
[root@iZt4n6feax4zkua4wka8hnZ bin]# AMOUNT=8888
[root@iZt4n6feax4zkua4wka8hnZ bin]# ./burrow tx formulate send -s $SENDER -t $RECIPIENT -a $AMOUNT > tx.json
### **cannot continue with config: could not finalise address - please provide one in config or via --account-address**
[root@iZt4n6feax4zkua4wka8hnZ bin]# 


Why can't I transfer?

**Comment by bitbeb** [comment]
jobs:
- name: sendTxTest1
  send:
      destination: B811B02E4277028988D9833F9A6FD9720BB5430A
      amount: 8888




jobs:
- name: sendTxTest1
  send:
      destination: B811B02E4277028988D9833F9A6FD9720BB5430A
      amount: 8888
tx.json

[root@iZt4n6feax4zkua4wka8hnZ bin]# SIGNING_ADDRESS=39832F04F5FBED26882547DB6C518C6478D3BE5C
[root@iZt4n6feax4zkua4wka8hnZ bin]# ./burrow deploy --address 39832F04F5FBED26882547DB6C518C6478D3BE5C tx.json
log_channel=Info message="Using chain" Chain=127.0.0.1:10997 Signer=
log_channel=Info message="Loading Playbook File."
log_channel=Info message="Loading playbook file" path=/opt/burrow/bin filename=/opt/burrow/bin/tx.json
log_channel=Info message="*****Executing Job*****" JobName=defaultAddr Type=Account
log_channel=Info message="Setting Account" account=39832F04F5FBED26882547DB6C518C6478D3BE5C
log_channel=Info message="*****Executing Job*****" JobName=sendTxTest1 Type=Send
log_channel=Info message="Sending Transaction" source=39832F04F5FBED26882547DB6C518C6478D3BE5C destination=B811B02E4277028988D9833F9A6FD9720BB5430A amount=8888
log_channel=Info message=SendTx send="&{39832F04F5FBED26882547DB6C518C6478D3BE5C 8888  B811B02E4277028988D9833F9A6FD9720BB5430A}"
log_channel=Info message="Using mempool signing since no keyClient set, pass --keys to sign locally or elsewhere"
log_channel=Info message="Using mempool signing"
Error in RunPlaybooks: error in SendJob with payload SendTx{[TxInput{39832F04F5FBED26882547DB6C518C6478D3BE5C, Amount: 8888, Sequence:1}] -> [TxOutput{B811B02E4277028988D9833F9A6FD9720BB5430A, Amount: 8888}]}: rpc error: code = DeadlineExceeded desc = context deadline exceeded
log_channel=Info message="JOBS THAT FAILED" count=1
log_channel=Info message="Playbook result" jobNo=0 file=tx.json error="error in SendJob with payload SendTx{[TxInput{39832F04F5FBED26882547DB6C518C6478D3BE5C, Amount: 8888, Sequence:1}] -> [TxOutput{B811B02E4277028988D9833F9A6FD9720BB5430A, Amount: 8888}]}: rpc error: code = DeadlineExceeded desc = context deadline exceeded" time=15.004032273s



[root@iZt4n6feax4zkua4wka8hnZ bin]# SIGNING_ADDRESS=39832F04F5FBED26882547DB6C518C6478D3BE5C
[root@iZt4n6feax4zkua4wka8hnZ bin]# ./burrow deploy --address 39832F04F5FBED26882547DB6C518C6478D3BE5C tx.json
log_channel=Info message="Using chain" Chain=127.0.0.1:10997 Signer=
log_channel=Info message="Loading Playbook File."
log_channel=Info message="Loading playbook file" path=/opt/burrow/bin filename=/opt/burrow/bin/tx.json
log_channel=Info message="*****Executing Job*****" JobName=defaultAddr Type=Account
log_channel=Info message="Setting Account" account=39832F04F5FBED26882547DB6C518C6478D3BE5C
log_channel=Info message="*****Executing Job*****" JobName=sendTxTest1 Type=Send
log_channel=Info message="Sending Transaction" source=39832F04F5FBED26882547DB6C518C6478D3BE5C destination=B811B02E4277028988D9833F9A6FD9720BB5430A amount=8888
log_channel=Info message=SendTx send="&{39832F04F5FBED26882547DB6C518C6478D3BE5C 8888  B811B02E4277028988D9833F9A6FD9720BB5430A}"
log_channel=Info message="Using mempool signing since no keyClient set, pass --keys to sign locally or elsewhere"
log_channel=Info message="Using mempool signing"
Error in RunPlaybooks: error in SendJob with payload SendTx{[TxInput{39832F04F5FBED26882547DB6C518C6478D3BE5C, Amount: 8888, Sequence:1}] -> [TxOutput{B811B02E4277028988D9833F9A6FD9720BB5430A, Amount: 8888}]}: rpc error: code = DeadlineExceeded desc = context deadline exceeded
log_channel=Info message="JOBS THAT FAILED" count=1
log_channel=Info message="Playbook result" jobNo=0 file=tx.json error="error in SendJob with payload SendTx{[TxInput{39832F04F5FBED26882547DB6C518C6478D3BE5C, Amount: 8888, Sequence:1}] -> [TxOutput{B811B02E4277028988D9833F9A6FD9720BB5430A, Amount: 8888}]}: rpc error: code = DeadlineExceeded desc = context deadline exceeded" time=15.004032273s

**Comment by silasdavis** [comment]
As I elaborated in chat this is not a good place for debugging help:

Ideally provide a test case as part of working project that can be run with a single command, say what you expected, say what you got, explain why this is likely to be a problem with Burrow.

I can see it would be useful if we had a test case/example running against metamask, if this is something you would like to contribute then that would be great. Perhaps you could distil what you are trying to do into a minimal node js app against metamask that I could run. The easier that is for me to convert to example code to help others the more likely I am to allocate time to it.
