### ISSUE TITLE
[eris-contracts.js] Bytes32 passing problem

### ISSUE THREAD

**Issue by PathHomotopy** [hyperledger/burrow#149]
Hi all, it appears there is another problem with bytes32. 

When we pass a bytes32 structure (which is less than 32 bytes) from an epm to a solidity contract function, it works. However, when we pass a bytes32 from javascript to solidity, the contract is unable to hold it. We determined this by passing a bytes32 structure from eris-contracts to a contract which returns the bytes32 structure it received. Rather than returning our bytes32 input, it returns 000000000... Thanks!

**Comment by dennismckinnon** [comment]
Can you provide materials on how to re-create? epm.yaml, javascript and solidity files? a gist or pastebin would be sufficient and would be extremely helpful in tracking down the issue. I ran into something similar to this recently but was unable to isolate it from the project it occurred in.

**Comment by PathHomotopy** [comment]
Hi Dennis and Ben,

Issue recreation is attached. Thanks!
[Bytes32 Issue Replication.docx](https://github.com/eris-ltd/eris-db/files/348621/Bytes32.Issue.Replication.docx)

**Comment by benjaminbollen** [comment]
Can you help me out here on understanding the issue.

```
contract.passVal("this is of type bytes32",function(error,result){
        console.log(result);
})```
here you're passing a string to a function that expects a byte32, but you're not sending it hex characters.  The string would not be auto-converted to hex (as it would be impossible to determine whether the string already is hex or should be converted. )  Arguably we should error more clearly here.

Please tell me if I am fully and completely misunderstanding the problem at hand here.

**Comment by PathHomotopy** [comment]
Are you sure bytes32 only takes in hex? We are able to put nonhex strings in bytes32 in Eris.

**Comment by silasdavis** [comment]
@NodeGuy could you take a look at this. Is it possible to send a string and have it interpreted as bytes32? If it is then I expect it should not be. How would you send this. Would like to close this issue.

**Comment by NodeGuy** [comment]
I don't know if this is causing the problem but formatting of `bytes` types was broken in web3 until they accepted [my pull request](https://github.com/ethereum/web3.js/pull/520) to fix it yesterday.  I'm doing some more work on web3 in this area and when I've finished I'll take a look at this.

**Comment by VoR0220** [comment]
Great work @NodeGuy !

**Comment by NodeGuy** [comment]
Thank you!
