### ISSUE TITLE
[Tests] Implement network level tests on 4-7 node chains

### ISSUE THREAD

**Issue by benjaminbollen** [hyperledger/burrow#154]
Create a separate test-executable that functions as a full node, but runs a json-defined test suite against a (test) chain.

Initial commit: https://github.com/benjaminbollen/eris-db/tree/networktests

**Comment by silasdavis** [comment]
I believe you have done this. Will this ticket progress or can we close and see work represented elsewhere?

**Comment by AFDudley** [comment]
doesn't Eris-marmont do this?

**Comment by silasdavis** [comment]
This is still worth doing. The old work is not of any current relevance. The test client can be implemented using bosmarmot. It would involve writing a transaction recorder that captures transactions from EPM as JSON and records the account state after each call, then replays them against a running node. Then dumps the account state verifying the state hashes etc match the captured versions.
