### ISSUE TITLE
Make transaction signing error-free

### ISSUE THREAD

**Issue by silasdavis** [hyperledger/burrow#166]
Currently we have two identical interfaces for writing 'sign bytes':

https://github.com/eris-ltd/eris-db/blob/4b5f3cbcc23e6296793ac82bdf29a4f879b9c15f/account/account.go#L37 

``` go
type Signable interface {
    WriteSignBytes(chainID string, w io.Writer, n *int, err *error)
}
```

and:

https://github.com/eris-ltd/eris-db/blob/4b5f3cbcc23e6296793ac82bdf29a4f879b9c15f/txs/tx.go#L66

``` go
type Tx interface {
    WriteSignBytes(chainID string, w io.Writer, n *int, err *error)
}
```

In practice the Signable interface is only used for transactions so provided that is the case I think we should drop it. The interfaces seem to be inherited from go-wire that uses io.Writer and so the possibility of an error infects all callers. In practice we are signing in-memory objects where it should be possible to do so without error. To avoid errors transmitting currently we just panic:

https://github.com/eris-ltd/eris-db/blob/4b5f3cbcc23e6296793ac82bdf29a4f879b9c15f/account/account.go#L46

Not very nice precious.

Instead I propose the interface:

``` go
type Tx interface {
    CanonicalBytes(chainID string) []byte
}
```

This will require checking and removing all `WriteSignBytes` and `Signable` usages

**Comment by compleatang** [comment]
Dealt with elsewhere
