### ISSUE TITLE
Consider making ChainId part of Tx interface

### ISSUE THREAD

**Issue by silasdavis** [hyperledger/burrow#167]
Shouldn't a Tx know it's own ChainId? Perhaps for some reason not. Otherwise `Tx` could look like:

``` go
type Tx interface {
    ChainId string
    CanonicalBytes() []byte
}
```

Can we can drop the `chainId` argument from `WriteSignBytes` or `CanonicalBytes`

**Comment by ebuchman** [comment]
I think the only argument for not knowing is redundancy. it's redundant extra information added to *every* tx in the chain. that said, I sympathize with the extra complexity of having to grab it from somewhere magic to validate a signature, but you'll need to do that anyways to validate that it's on the right chain. so in reality the only effect of this is to add useless data to the chain.

**Comment by ebuchman** [comment]
actually, maybe there's a use case for knowing what chain a tx should be on just by looking at the tx, rather than checking the CanonicalBytes are for a chain you know about. but maybe you can make a privacy argument against that as well

**Comment by benjaminbollen** [comment]
at the interface level we don't need to affect the wire format.  That said, we can take a shorter hash of the `ChainIdHash`, and include it in the tx on the wire, especially for situations where multiple chains run on shared nodes.

@ebuchman can you point to where Tendermint adds a "mapping-identifier", assuming the need for this from GnuClear, or please correct me if Im wrong assuming that.

**Comment by silasdavis** [comment]
As I think Ben is saying, we don't have to add the ChainId to the serialisation of a transaction, we could just grab the ChainId from somewhere suitable when you need to deserialise or create a new Tx in memory.

I'm not sure about this case, but I often like to follow the principle of including redundant information in a piece of data if it makes it more self-describing when divorced from it's context. Can be convenient when processing from another tool, when debugging, etc.

**Comment by AFDudley** [comment]
Doesn't the application have a protocol version in the transaction?

I haven't had any caffeine yet, but people shouldn't be process "loose" transactions outside of blocks unless it's crosstalk between two networks, in which case it seems reasonable to kick the identification into either the block(transaction log) and/or let the application manage it.

**Comment by silasdavis** [comment]
> Doesn't the application have a protocol version in the transaction?

I don't think so neither in the concrete Tx types or the block header... What would be the bearing of this if it did?

> but people shouldn't be process "loose" transactions outside

Perhaps not, my point doesn't really amount to much more than "metadata is good"

Having the ChainId on the Tx interface is convenient whether or not we include on the wire.

**Comment by ebuchman** [comment]
I see. I can see value in storing the chainID in the tx struct but not in the serialization for convenience. but no really ;)

**Comment by compleatang** [comment]
Done
