### ISSUE TITLE
[RPC] Support to watch event logs from the beginning of the blockchain

### ISSUE THREAD

**Issue by NodeGuy** [hyperledger/burrow#171]
A user requested this over at `eris-db.js`: https://github.com/eris-ltd/eris-contracts.js/issues/32

**Comment by NodeGuy** [comment]
Here's another user request:

> Can you please let us know how to get past events (from block 0 to latest) using eris contracts JS SDK.
>  
> I know to get event notifications we can call myContract.MyEvent(startCallback, eventCallback); . But this is useful only to get future notifications. How can we get past events i.e. from Block 0?
>  
> In Ethererum/Web3 we can do something like below to get all past events
>  
> var sendEvent = myContract. MyEvent ({from: sendFromAddress}, {fromBlock: 0, toBlock: 'latest'});
>  
> sendEvent.watch(function(error, log){
>      console.log(log);
> });

**Comment by silasdavis** [comment]
Replaced by firehose: #658
