### ISSUE TITLE
[EVM] Type byte32 does not store full 32 bytes

### ISSUE THREAD

**Issue by benjaminbollen** [hyperledger/burrow#188]
[formal_docs_for_bytes32.pdf](https://github.com/eris-ltd/eris-db/files/397560/formal_docs_for_bytes32.pdf)

**Comment by benjaminbollen** [comment]
https://github.com/eris-ltd/eris-pm/issues/192

**Comment by silasdavis** [comment]
@benjaminbollen the eris-pm issue link is dead. Can you comment on whether this is still a live issue, also does it relate to #149 ? If so can we merge.

If it is live then we should transcribe the code snippets and text in the PDF to markdown and replace the link to a PDF with the text therein.
