### ISSUE TITLE
Fix CacheTx persistance for nested calls in ErisMint

### ISSUE THREAD

**Issue by benjaminbollen** [hyperledger/burrow#205]
This has been hot-fixed on 0.11.4 in issue #164 and #184; but needs to be carried over to ErisMint on 0.12.0
- [x] port the fix in evm
- [ ] port the unit tests in state for this fixed bug
- [ ] assert created test is also integrated in eris-pm https://github.com/eris-ltd/eris-pm/issues/189

**Comment by compleatang** [comment]
this is done, no?

**Comment by benjaminbollen** [comment]
It's not checked off on being carried onto erismint/develop 0.12.0-rc3 so will check that.

There is an "overview issue" at https://github.com/eris-ltd/eris-db/issues/259

**Comment by benjaminbollen** [comment]
e-pm test needs to be asserted

**Comment by silasdavis** [comment]
@benjaminbollen is this done now?
