### ISSUE TITLE
Component sandboxing

### ISSUE THREAD

**Issue by benjaminbollen** [hyperledger/burrow#213]
Eris-db leverages (external) components that are not fully under our control. Eris-db needs to be able to recover from component failure.  This is an additional requirement to code contributions from eris to partner projects to address potential failures in the components at the source.

**Comment by compleatang** [comment]
Putting the FT in BFT!

**Comment by silasdavis** [comment]
@benjaminbollen I don't understand the goal and scope of this ticket from the description. Could you clarify or simplify or expand on it?
