### ISSUE TITLE
[Pipe] ErisMint: checkCache for CheckTx reset

### ISSUE THREAD

**Issue by benjaminbollen** [hyperledger/burrow#228]
Currently if an empty block is committed (no transactions included) then the cached copy for CheckTx - which runs in parallel to AppendTx - is not reset and preserved.  The checkCache is reset to the current state when a non-empty block is committed.

Tendermint mempool however can update and recheck the transactions; this can make the checkCache and state move out of sync;
1. One consideration is that ErisMint needs to synchronise on FlushSync() 
2. A tension remains: on a new block, the application would want to reset caches as the block tick is the only reference point; on the other hand, one can argue that the mempool already improves statistically the odds of producing a synchronized sequence of transactions, if indeed the checkCache is preserved (allowing sequentially dependent transactions to potentially be included in the same block*); It has to be added though that if no transactions are committed in the block, then it is likely to assume there are close to no transactions lingering in the mempool.  This provides the strongest argument to stay close to the logic of preserving the block tick for resetting caches.  -> This resolves the tension lined out in point 2., but builds a tension with point 1.

*This can be understood by considering that if CheckTx would work off off the last committed state for every checked transaction, the sequence numbers of sequential transactions in the same block would cause a dependent transaction to be rejected from the mempool.

**Comment by silasdavis** [comment]
Great this capture what we spoke about perfectly.

**Comment by compleatang** [comment]
Handled in new concurrency paradigm.
