### ISSUE TITLE
Retrieve log of transactions/ solidity events since block X

### ISSUE THREAD

**Issue by dennismckinnon** [hyperledger/burrow#245]
This has been requested by several customers and i believe is not currently possible. Sure its expensive and _kinda of_ excessive but customer is always right...

**Comment by NodeGuy** [comment]
Another request: https://support.erisindustries.com/helpdesk/tickets/387

**Comment by NodeGuy** [comment]
Another request: http://ethereum.stackexchange.com/questions/9188/is-there-a-way-to-view-all-events-on-all-blocks-for-eris-blockchain

**Comment by compleatang** [comment]
Dealt with elsewhere
