### ISSUE TITLE
[RPC] Make LogN calls queryable without replaying all blocks 

### ISSUE THREAD

**Issue by VoR0220** [hyperledger/burrow#246]
Problem: It would appear that currently, e-db tries to handle everything from the state root and doesn't exactly record event logs in a way that's similar to Eth's...which leads to problems for how users expect to interact with our chain. 

I'm not certain of the solution at this point and time. I will leave that for the E-DB team to figure out. Essentially the way the EVM does events is by registering a call and logging whatever information via a Keccak hash of up to 4 indexed parameters (Log1, 2, 3, 4) into the current block of the chain. Everything else is logged as the byte string. This enables one to sync through the entire history of the chain and gather cumulative logs, or watch the chain and await for a log to fire off and respond accordingly...in addition, this they are near free in the Ethereum world so they are heavily used there.  

Geth implementation:
https://github.com/ethereum/go-ethereum/blob/290e851f57f5d27a1d5f0f7ad784c836e017c337/core/vm/instructions.go#L623
https://github.com/ethereum/go-ethereum/blob/master/core/vm/log.go

ABI Formal Description:
https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI#events

This SO answer for useful reading: 
http://ethereum.stackexchange.com/questions/1302/where-do-contract-event-logs-get-stored-in-the-ethereum-architecture

**Comment by silasdavis** [comment]
This may be broader than area/EVM, that is TBC. We have various plans for event streams for domain events (like EVM events) scoped to participant/network level and consensus/governance events.

**Comment by VoR0220** [comment]
Agreed but in the meanwhile can we maintain the logging structure that the EVM has? Perhaps be able to return logs and make those automatically printable by eris-db particularly when interacting with EPM jobs.

**Comment by silasdavis** [comment]
Ethereum stores Log directly in blocks (redundantly) making it queryable.

**Comment by compleatang** [comment]
closing in favor of #658
