### ISSUE TITLE
[RPC] CallTx not getting added to chain when used from JS libs

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#253]
Currently am reviewing @NodeGuy 's benchmark application https://github.com/eris-ltd/benchmarks against edb-rc3. The relevant code at the JS level is here -> https://github.com/eris-ltd/benchmarks/blob/master/lib/index.js#L112-L115

After putting a bunch of tracers in the code I get output that looks like this:

```
Transact
G[94 95 31 217 54 225 47 60 60 172 109 236 180 139 144 74 96 149 20 22]
[]
96 96 96 64 82 96 59 128 96 16 96 0 57 96 0 243 96 96 96 64 82 96 224 96 2 10 96 0 53 4 99 96 254 71 177 129 20 96 36 87 128 99 109 76 230 60 20 96 46 87 91 0 91 96 4 53 96 0 85 96 34 86 91 96 0 84 96 96 144 129 82 96 32 144 243]
1000000
0
SignTx
I'm a call TX
PPubKeyEd25519{0208C10BA9E59522F5EF2E3C134C9BFA552478B7C6E515C6364D7AD051F977E4}
[]
96 96 96 64 82 96 59 128 96 16 96 0 57 96 0 243 96 96 96 64 82 96 224 96 2 10 96 0 53 4 99 96 254 71 177 129 20 96 36 87 128 99 109 76 230 60 20 96 46 87 91 0 91 96 4 53 96 0 85 96 34 86 91 96 0 84 96 96 144 129 82 96 32 144 243]
1000000
0
/5096D9D3C7CD.../
<CallTx{TxInput{5E5F1FD936E12F3C3CAC6DECB48B904A60951416,1,1,/5096D9D3C7CD.../,PubKeyEd25519{0208C10BA9E59522F5EF2E3C134C9BFA552478B7C6E515C6364D7AD051F977E4}} -> : 6060604052603b8060106000396000f3606060405260e060020a600035046360fe47b1811460245780636d4ce63c14602e575b005b6004356000556
022565b6000546060908152602090f3}
eris-mint's BroadcastTX
<CallTx{TxInput{5E5F1FD936E12F3C3CAC6DECB48B904A60951416,1,1,/5096D9D3C7CD.../,PubKeyEd25519{0208C10BA9E59522F5EF2E3C134C9BFA552478B7C6E515C6364D7AD051F977E4}} -> : 6060604052603b8060106000396000f3606060405260e060020a600035046360fe47b1811460245780636d4ce63c14602e575b005b6004356000556
022565b6000546060908152602090f3}
After go wire's WriteBinary
vmap[tx:020101145e5f1fd936e12f3c3cac6decb48b904a6095141600000000000000010101015096d9d3c7cdb310bd21a183041c72acc2ae91a0e5eb859cca0ed07973ea40e99c73f9df43d1800b184a3a00a65c28de4048c64143d4e04511c6b5548261560a010208c10ba9e59522f5ef2e3c134c9bfa552478b7c6e515c6364d7ad051f977e4000000000000
0f42400000000000000000014b6060604052603b8060106000396000f3606060405260e060020a600035046360fe47b1811460245780636d4ce63c14602e575b005b6004356000556022565b6000546060908152602090f3]
6invalid character 'x' in literal true (expecting 'r')
XError broadcasting transaction: %vinvalid character 'x' in literal true (expecting 'r')
```

This seems to imply that somewhere either during the signing of the TX or in go-wire's WriteBinary function that we are not signing or writing for the wire correctly. The tx getting sent is a dead simple send and I cannot find anything within the code that would be a `literal true`...

**Comment by ebuchman** [comment]
The issue may be that the tx argument in BroadcastTx is expected to come as []byte, not pre-encoded to hex.

Eg. in a tendermint test: https://github.com/tendermint/tendermint/blob/master/rpc/test/client_test.go#L66
(see the testTx() function which returns []byte)

Whereas erisdb is encoded to hex first: https://github.com/eris-ltd/eris-db/blob/develop/manager/eris-mint/eris-mint.go#L98

The go-rpc client takes care of encoding to hex so you don't have to: https://github.com/tendermint/go-rpc/blob/master/client/http_client.go#L176

**Comment by silasdavis** [comment]
@compleatang is this still a live issue? Can we close?

Is it actually the issue with needing to send quotation marks for hex string?

**Comment by compleatang** [comment]
I'm not sure. I tried to get slams to work, but don't understand the setup well enough to move beyond a bunch of setup errors. @NodeGuy have you tested the slams benchmark against 0.15.6 / 0.12.1 ...?

**Comment by NodeGuy** [comment]
No I haven't.  I've been focused on fixing bugs in eris-contract.js first.  It's on my to do list to test slams with 0.12.1 and to create documentation for it at the same time.

**Comment by ratranqu** [comment]
A bit remote, but this might be fixed by https://github.com/eris-ltd/eris-db/pull/453

**Comment by compleatang** [comment]
Fixed
