### ISSUE TITLE
[RPC] fails to respond with valid id in JSON-RPC responses

### ISSUE THREAD

**Issue by NodeGuy** [hyperledger/burrow#271]
This request:

``` shell
curl --data '{"jsonrpc":"2.0","method":"erisdb.getChainId","params":null,"id":23}' --header "Content-Type:application/json" http://192.168.99.100:33367/rpc
```

responds with:

```
{"result":null,"error":{"code":-32700,"message":"Failed to parse request: json: cannot unmarshal number into Go value of type string"},"id":"","jsonrpc":"2.0"}
```

but the [JSON-RPC specification](http://www.jsonrpc.org/specification#request_object) states:

> id
> An identifier established by the Client that MUST contain a String, Number, or NULL value if included.  The Server MUST reply with the same value in the Response object if included.

**Comment by compleatang** [comment]
@silasdavis ideally this is a 0.12.0-battlemarmot addition

**Comment by silasdavis** [comment]
Will be superseded by RPC framework

**Comment by silasdavis** [comment]
This is a WONTFIX for v0 which is in maintenance mode
