### ISSUE TITLE
[Architecture] Bring Manager to the foreground in design

### ISSUE THREAD

**Issue by silasdavis** [hyperledger/burrow#291]
Looking at the current architecture, it seems that the 'manager' concept is not as developed as it might be. By this I mean that within the erismint manager, there is really only a tendermint application (eris-mint.go) and no overarching manager.

I think there would be an advantage in re-jigging things a bit to make the manager a stronger concept. Here is my initial proposal:
### Create a manager interface and a managers registry

I would propose a `Manager` interface like:

``` go
type Manager interface {
    NewManagerPipe(managerConfig, consensusConfig *config.ModuleConfig,
        eventSwitch *events.EventSwitch)
}
```

And also a registry of supported managers, currently it would just be 'erismint'. I think we should look to some simple form of dependency injection for inspiration on how to implement this. It seems ideal for the kind of code we have that 'reconfigures' itself depending on config.

`NewCore` would make a single call to `NewManagerPipe` dispatching off the manager config value and setting up an instance of the erismint `manager`. I would propose:

```
rename:    manager/erismint/erismint.go -> manager/erismint/application.go
create:      manager/erismint/manager.go
```

The manager would be passed consensus and manager config and would be responsible for ensuring compatibility and creating a pipe containing ConsensusEngine, Blockchain, and Application, before returning to `NewCore`.

A specific `Manager` will know about the types of application engine and consensus engine it supports, so this is where we would aim to centralise the mixing of concerns in this regard. Erismint `Genesis` is one object subject to such a mixing, so this could be defined and initialised at this level, as could the associated `ChainId`. Another possibility is logic for bonding/unbonding, where Erismint Application might want to "run stuff up the chain" to manager to issue commands to consensus (I'm not sure this is something we want or not). It would also serve as a place to hook in things like replicating to a queryable SQL store, where we are interested in application state and consensus events (just the place to hook - the actual logic would be its own module).
### The relation between Pipe and Manager?

There are some similarities between the current erismint/pipe.go and and the erismint/manager.go I am proposing in terms of what they internally have access to. It might be possible to collapse the implementation of erismint Pipe and erismint Manager to a single concrete type, but I am not sure if this is desirable. In any case I think the interfaces would still make sense as separate entities: Pipe is how the components of a Manager talk to the outside world (via RPC etc), Manager is how the components are assembled and talk to each other (instigated by Manager).
### Arguments for doing this
- It closely resembles what we originally spoke about when outlining the concept of Manager, and it is a natural extension/reorganisation of what we already have.
- It gives a clearer logical branching at startup:

```
Core --> Bootstrap Manager --> Manager checks compatibility --> Manager creates specific ConsensusEngine, Application, and Blockchain that are interdependent
```

rather than the isolation at initialisation of erismint application and tendermint consensus even though they are dependent on each other (we do two string switches, but they still can't share initialisation values).
- It creates a space to handle 'platform-wide' considerations, that is not generic (like `Core` or `Pipe`), but involves a specific combination of our components . Things like Genesis, Validators, Governance.
- If the matrix of 'supported configurations' over consensus engines, databases, execution engines, etc is sparse and the special treatment needed for particular 'supported' cells in that matrix is somewhat significant then it makes sense for us to thing of a single entry point to a particular configuration rather than to treat our system as some massive cartesian product of components.

**Comment by silasdavis** [comment]
@benjaminbollen @compleatang don't want to distract from release work at this point, but wanted to capture some thought on this for comment when there is time.

**Comment by benjaminbollen** [comment]
We should come back on the proposal itself, but purely on the naming I want to have noted that it is called an "application manager" where the application is the set of ethereum permissioned bytecode run.; so erismint is the "manager" of the "application".  I acknowledge that the naming is not ideal.  We could call it the "computer", "virtual machine" or "driver" (last one is my favorite).
