### ISSUE TITLE
[Consensus] Treat networks with less than five validators more forcibly

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#294]
Networks that have less than five BFT nodes are very different animals from more distributed networks. Also such networks are typically dev environments where extreme customization of network and consensus settings likely gets in the way. 

Erisdb (perhaps with the help of cm and cli) needs to treat these networks in a manner which is more opinionated than currently is done. 

For example fast sync. It should really never be on in smaller networks. There are probably other examples that we should add here. 

The end result will be a much better developer experience.

**Comment by silasdavis** [comment]
We need to look into what fastsync is doing, I'm not entirely clear. I'm not convinced that eris-db is the place to be opinionated about (or even know) the network size though.

**Comment by AFDudley** [comment]
wherever the size of the network is specified is where we should be explaining to users that their 1-4 node networks will demonstrably behave very differently thank their > 5 node networks. I agree that changing behavior in erisDB based on genesis peer count might be too much magic, but we need to expose the knob to configuration, such that I can specify a 3 node network as Master, Slave, Slave if I want. Also, that would need to have some meaning with regards to endpoint connections and drivers. Do we even have drivers outside of the JS bindings? are we doing connection management there?

**Comment by silasdavis** [comment]
Adding this to 0.16.0-01 sprint with the intention of discussing it, and reopen actionable items.
