### ISSUE TITLE
[Keys] consider making eris-keys key files compatible with ethereum clients

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#334]
@Gustav-Simonsson commented on [Wed Sep 09 2015](https://github.com/eris-ltd/eris-keys/issues/24)

To get compatibility between all Ethereum clients we worked out a spec for a common key file: https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

While GCM is nice and we probably should have gone with it instead of CTR + MAC, for the moment Ethereum clients generate key files with CTR.

However the current go-ethereum code supports multiple key formats for backwards compatibility; both scrypt and PBKDF2 for KDF and both CTR and CBC for encryption mode. This could be extended to support GCM if defined by the `cipher` field present in version 3 (latest) of the spec.

Would recommend we strive for compatibility between platforms here. This could be done quite easily if eris-keys rebases on go-ethereum's `crypto/key_store_passphrase.go` to pickup version 3 of it's key file format and defines it's GCM mode usage by setting the  `cipher` field to something like `aes-128-gcm` (we use `aes-128-ctr` to denote CTR mode)

---

@ebuchman commented on [Wed Sep 09 2015](https://github.com/eris-ltd/eris-keys/issues/24#issuecomment-138911853)

yes I would love to do this. thanks for the details.

---

@benjaminbollen commented on [Tue May 10 2016](https://github.com/eris-ltd/eris-keys/issues/24#issuecomment-218089612)

@zramsay @VoR0220 @AFDudley shall we post progress on this issue here ?

---

@VoR0220 commented on [Tue May 10 2016](https://github.com/eris-ltd/eris-keys/issues/24#issuecomment-218286447)

yesh

**Comment by silasdavis** [comment]
I need to learn some more crypto acronyms, but the intention of this ticket seems like a good one.

**Comment by silasdavis** [comment]
I am inclined to agree with @ebuchman here: https://github.com/tendermint/go-crypto/issues/13. Hoard also makes use of OpenPGP armor
