### ISSUE TITLE
[Keys] Test locking and unlocking of keys both via command line and API input

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#341]
@ebuchman commented on [Tue Nov 03 2015](https://github.com/eris-ltd/eris-keys/issues/29)

**Comment by silasdavis** [comment]
@compleatang this might be clear for someone who knows their way around keys, but could you update the description to describe what is meant by locking/unlocking.

**Comment by zramsay** [comment]
`eris-keys gen` without `--no-pass` will create a locked key (i.e., needs to be unlocked with password before being used). cli currently only generates unlocked keys (https://github.com/eris-ltd/eris-cli/blob/master/keys/keys.go#L83).

`eris-keys lock` will lock an unlocked key (not sure if possible if it wasn't created with the `--no-pass` flag) and `eris-keys unlock` will unlock it for use prior to signing. unlocking a key only last for some amount of time.

**Comment by zramsay** [comment]
see also https://github.com/eris-ltd/eris-cli/issues/794

**Comment by compleatang** [comment]
@seanyoung can we confirm that tests for this are getting added?

**Comment by seanyoung** [comment]
See https://github.com/hyperledger/burrow/pull/776 
We have a bunch of tests covering the new key store which is now part of burrow (but can be run separately if needed). 
However,  the lock/unlock feature is removed. It was both broken and confusing.
