### ISSUE TITLE
[Types] Usage of "return" attribute in JSON

### ISSUE THREAD

**Issue by fabcan** [hyperledger/burrow#348]
I'd like to report that being "return" a keyword in many programming languages, the automatically serialization/deserialization of entities that use that name as a property name (e.g. the Event entity or the Call struct) would be tricky/impossible.

The only 2 examples that I've seen until now are:
- https://monax.io/docs/documentation/db/latest/specifications/api/#event-types
- https://monax.io/docs/documentation/db/latest/specifications/api/#code-execution-calls

Note for Java users: I managed to avoid this problem with the appropriate `@XmlElement(name="return")` annotation, but this restricts my ability to create an automated system that maps the entities to Java.

**Comment by silasdavis** [comment]
@fabcan thanks for this, it's a great point. We will be overhauling the RPC layers (and unifying), and at some point aspects of the event system so we will bear this in mind and try to avoid reserved keywords where possible.

Also as an aside, if any work of the work you have done in Java is public domain I'd be very interested to see what you are building to use that to help support bindings to languages other than javascript.

**Comment by compleatang** [comment]
Fixed
