### ISSUE TITLE
Running into problems with cryptographic functions

### ISSUE THREAD

**Issue by VoR0220** [hyperledger/burrow#357]
Working on https://github.com/eris-ltd/eris-cli/issues/1030 and running into the problem of not getting pretty byte output when converting to string. 

Output:

```
Debugging:Nd�|�_    І6�^��89�\S ��᧨8ۯ�
Return Value                                 Nd�|�_ І6�^��89�\S ��᧨8ۯ�
Job Vars                                      [0xc42024fe00]
Executing Job                                 assert256
Type                                          Assert
Replacement Match Found                 match=$callSha256
Fixing Variables =>                       resNd�|�_ І6�^��89�\S ��᧨8ۯ�
                                          var=callSha256
Assertion =>                              keyNd�|�_ І6�^��89�\S ��᧨8ۯ�
                                     relation=eq
                                        value=6ffa955749c31a98f50d0a3030c2d9aa663081c5ca423a691d7b44bd55e3c2eb
Assertion Failed                             Nd�|�_ І6�^��89�\S ��᧨8ۯ� == 6ffa955749c31a98f50d0a3030c2d9aa663081c5ca423a691d7b44bd55e3c2eb
```

**Comment by VoR0220** [comment]
Is there something regarding hex encoding that we need to do regarding the native cryptographic functions?

**Comment by silasdavis** [comment]
@VoR0220 please supply the command you are running to see this, and steps to reproduce.

**Comment by VoR0220** [comment]
Let me rebase the branch and then push it up and link it.

**Comment by VoR0220** [comment]
So here is the directory in the tests, you can simply run the test.sh script for app38, and you'll be able to reproduce the problem there. https://github.com/eris-ltd/eris-pm/tree/cryptoTests/tests/fixtures/app38-cryptographic_functions

**Comment by benjaminbollen** [comment]
this is a sympton of not having armored types.  I can pick this up

**Comment by VoR0220** [comment]
Armored types?

**Comment by silasdavis** [comment]
@benjaminbollen assume you mean armoured text output? Is it just a case of adding a `func (*Hash) String() string` method somewhere appropriate?

**Comment by VoR0220** [comment]
Got it
