### ISSUE TITLE
Switch JSON-RPC Parameter Structures to 'by-position'.

### ISSUE THREAD

**Issue by NodeGuy** [hyperledger/burrow#358]
The JSON-RPC methods accept parameters [by-name](http://www.jsonrpc.org/specification#parameter_structures), e.g.:

``` JSON
{
  "method": "erisdb.transactAndHold",
  "params": {
    "priv_key": "DE3211635E7C4C4A74B1582007A26D7ABCF41FA06254794BC8180F030888903B1E67B62D6EC2AB1BAFB4994A7D31A5DE2C1130797E833403005A382DC5E576E0",
    "address": "",
    "data": "606060405260448060106000396000f3606060405260e060020a60003504633bdab8bf8114601a575b005b60187f57050ab73f6b9ebdd9f76b8d4997793f48cf956e965ee070551b9ca0bb71584e60006060a156",
    "gas_limit": 1000000,
    "fee": 0
  },
  "jsonrpc": "2.0",
  "id": "1"
}
```

Since neither Go nor JavaScript supports calling procedures with named parameters, this isn't idiomatic to either language.  Let's switch to specifying arguments by position:

``` JSON
{
  "method": "erisdb.transactAndHold",
  "params": [{
    "priv_key": "DE3211635E7C4C4A74B1582007A26D7ABCF41FA06254794BC8180F030888903B1E67B62D6EC2AB1BAFB4994A7D31A5DE2C1130797E833403005A382DC5E576E0",
    "address": "",
    "data": "606060405260448060106000396000f3606060405260e060020a60003504633bdab8bf8114601a575b005b60187f57050ab73f6b9ebdd9f76b8d4997793f48cf956e965ee070551b9ca0bb71584e60006060a156",
    "gas_limit": 1000000,
    "fee": 0
  }],
  "jsonrpc": "2.0",
  "id": "1"
}
```

**Comment by silasdavis** [comment]
@NodeGuy So you are proposing that we make it explicit that we accept a 1-argument function call that itself is a dictionary?

This may be better subsumed into RPC discussion which will change much of this, but will leave open for now since it is broader than the particular JSON-RPC implementation we are using now (which will be scrapped)

**Comment by NodeGuy** [comment]
Yes, that's exactly what I'm proposing.  That way the JSON-RPC layer will simply translate function calls abstractly (which is what it's designed for) rather than requiring special knowledge of the application as it does today.
