### ISSUE TITLE
Concurrency issue

### ISSUE THREAD

**Issue by DrBAXA** [hyperledger/burrow#361]
I have contract with code below
 
 ```
 contract Coin {
      address minter;
      
      mapping (address => uint) balances;
      
      event Send(address from, address to, uint value);
      
      function Coin() {
          minter = msg.sender;
      }
      
      function mint(address owner, uint amount) {
          if (msg.sender != minter) return;
          balances[owner] += amount;
      }
      
      function send(address receiver, uint amount) returns (bool success) {
          if (balances[msg.sender] < amount) return false;
          balances[msg.sender] -= amount;
          balances[receiver] += amount;
          Send(msg.sender, receiver, amount);
      return true;
      }
      
      function queryBalance(address addr) constant returns (uint balance) {
          return balances[addr];
      }
      
      function distribute(address[] accounts, uint amount) returns (bool success) {
          if (balances[msg.sender] < amount) return false;
          uint mean = amount / accounts.length;
          uint rest = amount % accounts.length;
          uint i = 0;
          while (i < accounts.length) {
          uint amountPerAccount = 0;
              if (rest > 0) {
          amountPerAccount = mean + 1;
          rest = rest - 1;
          } else {
              amountPerAccount = mean;
          }
              balances[msg.sender] -= amountPerAccount;
              balances[accounts[i]] += amountPerAccount;
              i = i + 1;
          }
          return true;
      }
      
  }
```
I use http rpc calls to invoke contract methods. In case I have many concurrent calls to `queryBalance` method some return values is empty.
RPC call data 

```
{
   "jsonrpc": "2.0",
   "method": "erisdb.call",
   "id": "",
   "params": {
     "from": "D9ADB041D75B842E0CA3D263F99CDC8483759A9A",
     "address": "C77CDE43F65450FB64EA53C71CF4E16610996856",
     "data": "37F42841000000000000000000000000042225F59901A36C847069E092122A3BD6FD60AA"
   }
 }
 ```
 
 Plain "correct" response when I make requests from one thread
 
```
 {"result":{"return":"0000000000000000000000000000000000000000000000000000000000000000","gas_used":0},"error":null,"id":"","jsonrpc":"2.0"}
```
 
 Wrong response when I make 20 requests from different threads
 
```
{"result":{"return":"","gas_used":0},"error":null,"id":"","jsonrpc":"2.0"}
```
 
 I use own client implementation in Java

**Comment by DrBAXA** [comment]
One more thing - this chain has just one validator.

**Comment by benjaminbollen** [comment]
Thanks @DrBAXA.  It's not clear to me, were you only querying empty balances and is your issue that on multithreading it returns empty string, or would you have expected also non-zero values returned?

**Comment by DrBAXA** [comment]
There is no differences if values is zero or not. This issue is reproduced with both variants.

**Comment by benjaminbollen** [comment]
at which endpoint do you make the calls? `chain:1337/rpc` or `chain:46657`?

**Comment by DrBAXA** [comment]
I use chain:1337/rpc and chain:1337/socketrpc. In both cases I got this issue

**Comment by silasdavis** [comment]
@DrBAXA thanks for this report. Is the incorrect response reliably repeatable each time you query from multiple threads or is it intermittent?

>I use own client implementation in Java

I don't know if this is something you can share, but I would be very interested to see it, or if you have any remarks about integrating. We currently consider binding against our RPC from other languages more involved that we would like, and your experience might inform our work in this direction.

**Comment by DrBAXA** [comment]
When I use 20 calls in ```paralelStream``` it happens all time (from 1 to 10 responses is broken).
If there is less calls it happens time to time.
Code is [here](https://github.com/SoftJourn/eris-java-client)

**Comment by compleatang** [comment]
We have completely refactored the concurency and events system. Am closing this ticket for now, but if the issue rearises and a test case can be generated please reopen!
