### ISSUE TITLE
Triage every issue in eris-db repo

### ISSUE THREAD

**Issue by silasdavis** [hyperledger/burrow#377]
We have fairly large number of open issues - nothing wrong with this per se, but I suspect a number of old ones should be closed, some can be consolidated, some will be subsumed by planned future work, and some are unactionable in their current state. We should:

- Either close or label every open issue
- Label every issue with a severity (triage)
- Label every issue with type (bug, feature, etc)
- Label every issue with which component is affected
- Label as 'ready to work on' or 'needs more information'

I'd also like to raise the standard of issue reporting without being obstructive by:
- Asking for clear reproduction steps
- Urging strongly for the reporter to provide a minimal test case/example that is as focused as possible, and probably built specifically for the issue (not always practical, and sometimes will be down to issue investigator, but often the reporter could do more than they tend to do currently)

This pushes a certain amount of work onto the reporter, but we have limited resources and often the reporter can do more particularly around generic work isolating where the bug appears. We are always grateful to have issues reported, but we should (usually) prioritise issues with clear isolated reproduction above those without, since it is a more efficient use of our time and there is a self-selection at work on the priorities of the reporter - presumably if someone has made more effort in the reporting of a bug they assign more value to it themselves.

I'd like to also propose for non-critical issues that have limited or inadequate reproduction steps, that we first label them and request more information, but if they are dormant for ~3 months we close them. This is because I think having many dead issues hurts our focus. Open to contrary opinions on this.

**Comment by benjaminbollen** [comment]
LGTM
