### ISSUE TITLE
[EVM] dynamically allocate stack depth

### ISSUE THREAD

**Issue by benjaminbollen** [hyperledger/burrow#386]
**problem** current max data stack capacity is hard-coded at 1024 words256; memory at 1MB (call depth is unlimited)

**solution** by default make data stack and memory unlimited; set optional limit in configuration file for embedded devices; enforce call stack depth similarly

**Comment by silasdavis** [comment]
Suggest we start with a fixed size exponentially grow it as needed. Can't think of any reason why not to...

**Comment by compleatang** [comment]
@silasdavis do we still want to do this?

**Comment by silasdavis** [comment]
yeah currently we panic if we run out of stack there is also a panic in stack.go we should clear up. Easy task.
