### ISSUE TITLE
[Licensing] Consistently present licensing information

### ISSUE THREAD

**Issue by silasdavis** [hyperledger/burrow#407]
We want to consistently present licensing information, then enforce this presentation throughout codebase.

**Comment by benjaminbollen** [comment]
We have discussed this and needs to be executed; there is an open ticket for this

**Comment by kgehmlich** [comment]
I'm interested in dipping my toes into the Hyperledger water and figure I can start by clearing out some of the old issues like this one.

@silasdavis can you offer more insight into requirements/constraints for this ticket? Is it still wanted?

**Comment by kgehmlich** [comment]
@compleatang would you be the right person to ask about this? (see my previous comment)

**Comment by gregdhill** [comment]
Hi @kgehmlich, thanks for your interest! So I've had a discussion offline with @compleatang and we would ideally want to catch the licensing information in the header of every every `*.go` file throughout the project. There are already some examples of this ([see](https://github.com/hyperledger/burrow/blob/develop/logging/logger.go#L1) - `s/Monax/Hyperledger/g`) but I think it would be prudent to assess what other Hyperledger projects are doing so that we can maintain consistency there as well.

**Comment by gregdhill** [comment]
An extension of this task will be to maintain forward integrity, in that CI should fail if a file is committed without this header and we need a way for a developer to automatically populate new files.

**Comment by kgehmlich** [comment]
Hi @gregdhill, thanks for the response! I'll take a look at other projects to see what they've got going and put something together this week. I'm not familiar with CircleCI but it looks pretty straightforward, so I don't expect adding that check to be difficult.

**Comment by CaptainUday** [comment]
Hi Everyone, 
I am working on a proposal where i need to propose to my clients to build an de centralized app for their business support using Hyperledger fabric. Request if someone can help in understanding what will be the costing for procuring its license from IBM. Will they charge us on per  node wise ? How do we estimate how many nodes will be there at proposal stage??
Any suggestions/ recommendations would be helpful 

Regards  
Uday

**Comment by compleatang** [comment]
https://github.com/google/addlicense

**Comment by silasdavis** [comment]
I'd like to use a short one-line header for this is possible. Seems like the Apache org permits this, so hopefully Hyperledger does too.

**Comment by christo4ferris** [comment]
We do;-) Fabric uses the SPDX short form for specifying the license header.
eg
/*
SPDX-License-Identifier: Apache-2.0
*/

**Comment by adeebahmed** [comment]
The short-form license header should read somthing like this: 
```
// Copyright Monax Industries Limited
// SPDX-License-Identifier: Apache-2.0
```
