### ISSUE TITLE
[make] Structure development and test pipeline with Makefile consistently across repos

### ISSUE THREAD

**Issue by benjaminbollen** [hyperledger/burrow#411]
**problem** from a continuous integration point of view we want to separate and consistently define the check, build, test, (docker build and docker test), separate from the deployment steps.

**solution** [PROPOSAL] introduce make build system to structure the different steps; pro: limited capability of make guards against over-reliance on build dependency; cons: introduces a voluntary build dependency

**Comment by silasdavis** [comment]
This is fine for now, and we do need to share a common definition of build tasks but we should consider switching to something more modern before we add much complexity to a make file. Scons (http://scons.org/) can be shipped with repository and only requires that python is installed locally.
