### ISSUE TITLE
Unable to send CallTx transaction signed outside of eris-db

### ISSUE THREAD

**Issue by konstantinzolotarev** [hyperledger/burrow#425]
I’m working on sign transactions in JS code and sending them using `eris-db.txs().broadcastTx()` method. 

I was able to send a `SendTx` without any error (using this docs: https://monax.io/docs/documentation/db/0.12.0-rc3/specifications/api/#the-transaction-types)

But when I'm trying to create a `CallTx` and send it using same method I'm getting this error from `eris-db` 

```
{ Error: Expected type [Byte,?] but got type string
    at values.next.then (/Users/KoS/Projects/langa/vulcanize/eris-contracts.js/node_modules/eris-db/node_modules/@nodeguy/json-rpc/lib/index.js:12:38)
  method: 'broadcastTx',
  params:
   [ { input: [Object],
       address: '290AA16393FA6321BAF85AC801ED2CBFA5C91DAC',
       gas_limit: 10000,
       fee: 100,
       data: '6060604052602b8060106000396000f3606060405260e060020a6000350463a5f3c23b8114601a575b005b602435600435016060908152602090f3' } ],
  code: -32602,
  message: 'Expected type [Byte,?] but got type string' } undefined
```
** Sorry it's pretty dirty but working**
Source code for this is here: https://github.com/konstantinzolotarev/eris-contracts.js/blob/custom-sign/test.js#L85

**Comment by silasdavis** [comment]
This has been superceded
