### ISSUE TITLE
Wrong `erisdb.getPeers` response

### ISSUE THREAD

**Issue by konstantinzolotarev** [hyperledger/burrow#441]
I'm using JSON-RPC 2.0 for eris and here: 
https://monax.io/docs/documentation/db/latest/specifications/api/#get-peers

`erisdb.getPeers` call should return response in format: 
`{ peers: [<Peer>] }` but it returns just array ` [<Peer>] `

**Comment by compleatang** [comment]
this pipeline has all been refactored. closing for now
