### ISSUE TITLE
Chain becomes unusable after executing infinite loop smart contract

### ISSUE THREAD

**Issue by j-h-scheufen** [hyperledger/burrow#452]
This ticket is in continuation of https://github.com/eris-ltd/eris-cli/issues/1158 

#### Problem Description:
Running a smart contract with an endless loop (`for (uint i = 10; i >= 0; i--) {}`) via the `eris pkgs` command produces a timeout error upon the first run. Any invocation thereafter results in the JSON unmarshalling error.

```
[eris-client] Failed to unmarshal json bytes for websocket event: unexpected end of JSON input
[eris-client] Failed to unmarshal json bytes for websocket event: unexpected end of JSON input
[eris-client] Failed to unmarshal json bytes for websocket event: unexpected end of JSON input
[eris-client] Failed to unmarshal json bytes for websocket event: unexpected end of JSON input
```

The chain becomes unusable and cannot be recovered. E.g. stopping and starting the chain node does not eradicate the JSON unmarshal error.

#### Requirements:
Even though the problem is due to a programming error in solidity, the timeout of the operation should not render the chain useless. This should be analyzed to find a way to allow contracts to fail in this way and still leave the chain in a usable state.

#### Versions:
OSX version: 10.11.6
Eris CLI Version: 0.12.0
Docker:
Client:
Version: 1.12.2
API version: 1.24
Go version: go1.6.3
Git commit: bb80604
Built: Tue Oct 11 17:00:50 2016
OS/Arch: darwin/amd64
Server:
Version: 1.12.3
API version: 1.24
Go version: go1.6.3
Git commit: 6b644ec
Built: Wed Oct 26 23:26:11 2016
OS/Arch: linux/amd64
docker-machine version 0.8.2, build e18a919

**Comment by compleatang** [comment]
closing as old.
