### ISSUE TITLE
[RPC] JSON-RPC 2.0 Specification are not met

### ISSUE THREAD

**Issue by fabcan** [hyperledger/burrow#464]
I'm trying to integrate the RPC APIs with my Java project (using http://software.dzhuvinov.com/json-rpc-2.0.html), but the library I'm using continues to give me this error "_Invalid JSON-RPC 2.0 response: You cannot have result and error at the same time_" while calling **erisdb.getAccounts**. 
The raw response that I get from Eris is `{"result":null,"error":{"code":-32602,"message":"unexpected end of JSON input"},"id":"0","jsonrpc":"2.0"}`, but it can't be parsed.
I thought that the library I was using was too strict so I checked the JSON-RPC 2.0 specifications but it is right, there **must not** be both the _error_ and _respose_  attribute: http://www.jsonrpc.org/specification#response_object

I've managed to patch it for now with some Java Reflection trickery, but it is not the way it should work.

**Comment by benjaminbollen** [comment]
Can you provide information on reproducibility; specifically the request sent to the method?

**Comment by fabcan** [comment]
I send the following request to http://localhost:1337/rpc , I use _..._ to abbreviate the raw response.

Request: `{"id":"0","method":"erisdb.getAccounts","params":{"filters":[]},"jsonrpc":"2.0"}`
Response: `{"result":{"accounts":[{...},{...}]},"error":null,"id":"0","jsonrpc":"2.0"}`

Java library error when parsing: _Invalid JSON-RPC 2.0 response: You cannot have result and error at the same time_

**Comment by fabcan** [comment]
*Communication example*
Request: `{"id":"0","method":"erisdb.getAccounts","params":{},"jsonrpc":"2.0"}`
Response: `{"result":{"accounts":[{...},{...}]},"error":null,"id":"0","jsonrpc":"2.0"}`

The response given by Eris has the right values in the _accounts_ member, but the presence in the response of both the _error_ and _result_ members means that it isn't a right JSON-RPC 2.0 response according to the specifications (http://www.jsonrpc.org/specification#response_object) as it seems that the error member "MUST NOT exist if there was no error triggered during invocation."

So when I receive that response and the Java library I'm using parses it (http://software.dzhuvinov.com/json-rpc-2.0-client.html), it gives me this error: "_com.thetransactioncompany.jsonrpc2.client.JSONRPC2SessionException: Invalid JSON-RPC 2.0 response_"

If I use some Java reflection trickery and I manage to remove the error member entirely (`{"result":{"accounts":[{...},{...}]},"id":"0","jsonrpc":"2.0"}`), when the Java library parses the response it gives me no errors at all and it returns a correct Java object.

**Comment by compleatang** [comment]
closing as this pipeline has been significantly refactored. specific violations of JSON-RPC spec by burrow code should definitely be documented individually, however.
