### ISSUE TITLE
[EVM] Date storage conversions to and from epochdates are inconsistently stored and retrieved

### ISSUE THREAD

**Issue by shalinigpt** [hyperledger/burrow#467]
Attribute is stored in contract which contains epochdate. What I am saving as a date in an attributes is not same what is retrieve from contract to Attribute is stored in contract which contains epochdate, but when i retrieve the attribute from smart contract the date differs from what i had saved.
Let take an example i store "15 feb 2017" convert into epoch format in Rollingdate and while retriveing i get "14 jan 4763" after converting from epoch date. So the value differs what i save and what i get.

**Comment by compleatang** [comment]
Hi @shalinigpt thanks for raising this issue, can you please provide a reproducible case with code that we can use to track down if this is a bug? How exactly are you storing the attributes in contracts and communicating with the chain? That will help use efficiently track down whether this is a bug or something else.

**Comment by compleatang** [comment]
Closing as stale.
