### ISSUE TITLE
Retrieving incorrect value for uint or any integer format in smart contract.

### ISSUE THREAD

**Issue by npc0405** [hyperledger/burrow#473]
Hi, 
When I submit/save an integer value as 11, it retrieves 17 in smart contract.
Is it a bug? It started appearing after upgrading eris version to 0.12.0

Regards,
Nikhil

**Comment by zramsay** [comment]
@npc0405 please see the [issue template](https://github.com/eris-ltd/eris-db/blob/master/.github/ISSUE_TEMPLATE.md) and provide the appropriate information, especially the step to reproduction (including your solidity code and `epm.yaml`)
