### ISSUE TITLE
Valid solidity function leads to "Invalid jump dest" in ErisDB

### ISSUE THREAD

**Issue by j-h-scheufen** [hyperledger/burrow#474]
The following Test contract runs fine in browser-solidity using both Solidity compiler 0.3.6 and 0.4.9 (latest). However, executing this code on ErisDB leads to an error:

```
Executing Job                                 testBytes32ToString
Encountered Exception from chain: Transaction confirmed with exception:%!(EXTRA string=Invalid jump dest)
```

```
contract Test {
       function toString (bytes32 x) constant returns (string) {
        bytes memory bytesString = new bytes(32);
        uint charCount = 0;
        for (uint j = 0; j < 32; j++) {
            byte char = byte(bytes32(uint(x) * 2 ** (8 * j)));
            if (char != 0) {
                bytesString[charCount] = char;
                charCount++;
            }
        }
        bytes memory resultBytes = new bytes(charCount);
        for (j = 0; j < charCount; j++) {
            resultBytes[j] = bytesString[j];
        }

        return string(resultBytes);
    }
}
```

Versions:
OSX version: 10.11.6
Eris CLI Version: 0.12.0
Docker:
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64
Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
docker-machine version 0.9.0, build 15fd4c7

**Comment by silasdavis** [comment]
Can confirm this is fixed by #607
