### ISSUE TITLE
[SNatives] CREATE allows for creation on reserved SNative addresses

### ISSUE THREAD

**Issue by benjaminbollen** [hyperledger/burrow#483]
`CREATE` does not return an error if a contract is created at a reserved native address:
 https://github.com/eris-ltd/eris-db/blob/master/manager/eris-mint/evm/vm.go#L763

For the `Permissions.sol` it is my understanding that the interface `contract Permissions` is not deployed;
and no contract is `CREATE`d on the native contracts addresses. [permissions.sol](https://github.com/eris-ltd/eris/blob/develop/tests/jobs_fixtures/app33-evm_connection_edb_permissions_and_roles_layer/permissions.sol#L1)

It is better then to ensure that an early error is returned on `CREATE` if accidentally a contract would be deployed on reserved native address; https://github.com/eris-ltd/eris-db/blob/master/txs/tx.go#L226

**Comment by silasdavis** [comment]
We should find a away of checking/enforcing the reserved-ness of SNative contract addresses more generally.
