### ISSUE TITLE
[SNatives] Document permissions SNatives

### ISSUE THREAD

**Issue by silasdavis** [hyperledger/burrow#498]
Add documentation in snative.go.

This will inform the integration-level tests that @VoR0220 will write for: https://github.com/eris-ltd/eris/issues/1227. Once this is done, give that ticket a bump.

**Comment by VoR0220** [comment]
* Use godoc style

**Comment by silasdavis** [comment]
output from `make snatives` documents this and `burrow snatives` is coming which will do so more
