### ISSUE TITLE
Add Vagrant configuration.

### ISSUE THREAD

**Issue by NodeGuy** [hyperledger/burrow#514]

**Comment by NodeGuy** [comment]
This doesn't make sense, according to @silasdavis:

> but in terms of just copying it in, I'm not so sure that makes sense. For specific versions we ought to provide packer base boxes on the vagrant public repo that we built off packer. Then people just make their own Vagrantfile referencing our public box. You wouldn't want to include a Vagrantfile in eris-db for that I don't think, you'd be better to add it to the readme

cc: @zramsay

**Comment by benjaminbollen** [comment]
for eris-db the vagrantfile will have to be given a bit more work than the draft we have for eris tooling; but I definitely see clear value in having it defined at eris-db level as well.
