### ISSUE TITLE
[rpc] getBlocks does not take in params for rpc endpoint

### ISSUE THREAD

**Issue by belsyuen** [hyperledger/burrow#530]
Hi, 

I am trying to use the getBlocks() through RPC, the same code was used for getBlock with params: {height : 4271618} and it worked. 

But when I do getBlocks with the below: - 
---------------------------------
var getBlocks_option = {
    method: 'POST',
    url: 'http://ipaddress/rpc',
    headers: {
      'content-type': 'application/json'
    },
    body: {
      jsonrpc: '2.0',
      method: 'erisdb.getBlocks',
      params: {
        field: "height",
        op: ">",
        value : "4271618"}
    },
    json: true
  };
---------------------------------
The return is the most recent 50 blocks, and does not take into account for the params specified, in fact, I can pass an undefined value and the same is returned. This was sent via node request lib

But if I do :-
---------------------------------
http://ipaddress/blockchain/blocks?q=height:>4271618

---------------------------------
The correct result is returned. 

erisdb version 0.12.0

Thanks!

**Comment by benjaminbollen** [comment]
Thanks for reporting this; we will try to reproduce and get it addressed.

**Comment by belsyuen** [comment]
thank!

**Comment by belsyuen** [comment]
Hey, has there been any updates?
Thanks!

**Comment by compleatang** [comment]
closing this issue as unreproduceable.
