### ISSUE TITLE
Call of Eris DB method 'transactAndHold' with parameters - Transaction timed out

### ISSUE THREAD

**Issue by madmanblues** [hyperledger/burrow#540]
Opened issue as suggested by Casey in eris-db.js and then reopened here as suggested on the first issue https://github.com/monax/legacy-db.js/issues/57

I'll try to collect the requested info as soon as possible.

Problem - I created a service to call a function on a contract. When the service is called the information is logged in the console correctly (the service receive the data correctly) but when it calls the contract it goes in time out with the following error:

`Call of Eris DB method 'transactAndHold' with parameters { "priv_key": "...............", "address": "17FD3BE508C4410F41FCA995B4F6B96A9F19E89D", "data": "5c3f3e0c00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000015546869732069732061206861736820746f206c6f670000000000000000000000", "gas_limit": 1000000, "fee": 0 } responded with "Transaction timed out. Hash: 87C8A7BE5A5D4625D5C62C4AE29FD1FF7C200A85". { Error: Transaction timed out. Hash: 87C8A7BE5A5D4625D5C62C4AE29FD1FF7C200A85 at values.next.then (/usr/src/app/node_modules/eris-contracts/node_modules/eris-db/node_modules/@nodeguy/json-rpc/lib/index.js:12:38) method: 'transactAndHold', params: [ { priv_key: '................', address: '17FD3BE508C4410F41FCA995B4F6B96A9F19E89D', data: '5c3f3e0c00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000015546869732069732061206861736820746f206c6f670000000000000000000000', gas_limit: 1000000, fee: 0 } ], code: -32603, message: 'Transaction timed out. Hash: 87C8A7BE5A5D4625D5C62C4AE29FD1FF7C200A85' }`

Please include in your bug report:

- [ ] `eris-db version` (docker image tag or branch if built from source)
- [x] `eris version` (if applicable) - v0.12
- [ ] `go version` (if applicable)
- [ ] `docker version` (if applicable)
- [x] operating system details  - Linux/Unix, Ubuntu 14.04-LTS2
- [x] what you expected to happen - See description
- [x] what actually happened - see description
- [x] steps to reproduction - See description

**Comment by compleatang** [comment]
this pipeline has been refactored. closing this issue. if it reappears we can reopen
