### ISSUE TITLE
Call to selfdestruct(..) stops the chain

### ISSUE THREAD

**Issue by marc4gov** [hyperledger/burrow#542]
Please include in your bug report:

- [ ] `eris-db version` (docker image tag or branch if built from source)
0.12.0
- [ ] `eris version` (if applicable)
0.12.0
- [ ] `go version` (if applicable)
- [ ] `docker version` (if applicable)
1.13.0
- [ ] operating system details (osx/windows/linux)
osx
- [ ] what you expected to happen
chain keeps alive
- [ ] what actually happened
chain stops
- [ ] steps to reproduction
I'm making a call to Solidity selfdestruct via a cascading contract call, e.g.:

From a TaskManager contract:
```
    function removeTask(address manager, address taskAddress)
    returns (bool result) {
        Task t = Task(taskAddress);
        if (t.remove(manager)) {
            taskList.removeElement(t);
            TaskDeleted(t, "Task Deleted", block.number, block.timestamp);
            return true;
        } else {
            return false;
        }
    }
```
call from within the Task contract:

```
    function remove(address manager)
    onlyManager(manager)
    isEmpty(manager)
    returns (bool)
    {
        selfdestruct(owner);
        return true;
    }
```
It doesn't matter if I use the `owner` or the `manager` address for the refund

**Comment by silasdavis** [comment]
Will need to reproduce and pull a trace to see what is going on here.

**Comment by zramsay** [comment]
https://github.com/monax/cli/pull/1344

**Comment by silasdavis** [comment]
Minimal-ish reproduction here: https://gist.github.com/silasdavis/7f35cb31a255c18d2fc70eed1fa38211

**Comment by silasdavis** [comment]
Fixed on develop
