### ISSUE TITLE
NewBlock event subscription fails

### ISSUE THREAD

**Issue by NodeGuy** [hyperledger/burrow#582]
Please include in your bug report:

- [ ] `burrow version` (docker image tag or branch if built from source)

0.12.0

- [ ] `monax version` (if applicable)

Eris CLI Version: 0.12.0

- [ ] `docker version` (if applicable)

Docker version 17.03.0-ce, build 60ccb22

- [ ] operating system details (osx/windows/linux)

Mac OS

- [ ] what you expected to happen

I expect to receive events for new blocks every second.

- [ ] what actually happened

```
MONAX 62126: { method: 'erisdb.eventSubscribe',
  params: { event_id: 'NewBlock' },
  id: 'g/J2FRPonWdELdvOl0yUnQXbvFlSOohcds7Pe/dqXf4=',
  jsonrpc: '2.0' }
MONAX 62126: { result: { sub_id: '0' },
  error: null,
  id: 'g/J2FRPonWdELdvOl0yUnQXbvFlSOohcds7Pe/dqXf4=',
  jsonrpc: '2.0' }
MONAX 62126: { method: 'erisdb.eventPoll',
  params: { sub_id: '0' },
  id: 'j3UaQy4iyLLxxwjO4QMutYVRsJ8pc2Dy4pX2U2Cy4PA=',
  jsonrpc: '2.0' }
MONAX 62126: { result: { events: [] },
  error: null,
  id: 'j3UaQy4iyLLxxwjO4QMutYVRsJ8pc2Dy4pX2U2Cy4PA=',
  jsonrpc: '2.0' }
MONAX 62126: { method: 'erisdb.eventPoll',
  params: { sub_id: '0' },
  id: 'o/RlM9OOHITpSlPtrzMSBNveYLKJEwdu0ciiApT1rKQ=',
  jsonrpc: '2.0' }
MONAX 62126: { result: { events: [] },
  error: null,
  id: 'o/RlM9OOHITpSlPtrzMSBNveYLKJEwdu0ciiApT1rKQ=',
  jsonrpc: '2.0' }

...
```

- [ ] steps to reproduction

Call `erisdb.eventSubscribe` with `event_id` set to `NewBlock`.

**Comment by compleatang** [comment]
closing in favor of #609
