### ISSUE TITLE
[EVM] Support INVALID opcode

### ISSUE THREAD

**Issue by silasdavis** [hyperledger/burrow#601]
See: https://github.com/ethereum/EIPs/issues/141

**Comment by benjaminbollen** [comment]
Yes, this is the opcode I want (to prioritise) ! :)

**Comment by silasdavis** [comment]
Superceded by REVERT (I believe)

**Comment by silasdavis** [comment]
This is trivial to implement - already happens implicitly, we just need to add it.

**Comment by seanyoung** [comment]
Merged, see https://github.com/hyperledger/burrow/pull/757
