### ISSUE TITLE
[RPC] NewBlock events are not sent to web socket endpoint 1337/socketrpc

### ISSUE THREAD

**Issue by ratranqu** [hyperledger/burrow#609]
Please include in your bug report:

- [ ] `burrow version` (docker image tag or branch if built from source)
0.16.0, 0.16.3
- [ ] `monax version` (if applicable)
0.16
- [ ] operating system details (osx/windows/linux)
Linux ubuntu 16.04
- [ ] what you expected to happen
on 0.11.4, subscribing to `NewBlock` or `Log/$Addr` events over websockets would return the events as they came back. On 0.16.x, the events are not published anymore to the 1337/socketrpc endpoint.
Acc/*/* events still work though.
- [ ] what actually happened
no events are published to the 1337/socketrpc endpoint
- [ ] steps to reproduction
contact me if need a way to reproduce (it requires a chain with contracts publishing events and a web socket client subscribing and listening to all Log/$Addr  or NewBlock events)

**Comment by ratranqu** [comment]
the Log/$Address part of the bug is a red herring: it's due to the change in the way the event messages are deserialised (in 0.11.x, they had an EventType encoded).

The NewBlock part still remains.

I will update the title to reflect that.

**Comment by ratranqu** [comment]
Setting the New Block event subscription over web socket on 1337 does make it to hyperledger/burrow/events/events.go:63 (Subscribe), but the callback is never called (and NewBlock events are not making their way back to the `EventSwitch` it seems). When using `monad pkgs do ...` to deploy contracts, it does turn on subscription on NewBlock (the NewBlock events make their way back to the `EventSwitch`) however.

**Comment by compleatang** [comment]
We are working towards complete removal of 1337 in favor of grpc. Closing
