### ISSUE TITLE
Can't restart the chain after it failed

### ISSUE THREAD

**Issue by bonen** [hyperledger/burrow#616]
Running this line inside a smart contract caused the chain to stop running.
--bytes20(keccak256(msg.sender, block.blockhash(block.number - 1)))

I can't restart the chain, the logs show:
$monax chains logs [CHAIN]

DBUG[05-24|15:27:45] Loading configuration for serve command  channel=Trace run_id=895ae9c7-4095-11e7-8838-fa30d7d11bb1 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 info_trace_logger.go:139 convention.go:60 serve.go:133 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve chainId=localbloqnetwork workingDirectory=/home/monax/.monax/chains/localbloqnetwork dataDirectory=/home/monax/.monax/chains/localbloqnetwork/data genesisFile=/home/monax/.monax/chains/localbloqnetwork/genesis.json
DBUG[05-24|15:27:45] Modules configured                       channel=Trace run_id=895ae9c7-4095-11e7-8838-fa30d7d11bb1 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 info_trace_logger.go:139 convention.go:60 serve.go:147 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve consensusModule=tendermint-0.8 applicationManager=burrowmint-0.16
DBUG[01-01|00:00:00] Starting EventSwitch                     channel=Info run_id=895ae9c7-4095-11e7-8838-fa30d7d11bb1 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 capture.go:43 handler_go14.go:14 handler_go14.go:14 logger.go:120 logger.go:142 service.go:93 core.go:52 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve captured_logging_source=tendermint_log15 module=events impl=EventSwitch
INFO[05-24|15:27:45] Loading BurrowMint                       channel=Info run_id=895ae9c7-4095-11e7-8838-fa30d7d11bb1 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 manager.go:47 core.go:57 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core]" compatibleConsensus=tendermint-0.8 burrowMintVersion=burrowmint-0.16.2
INFO[05-24|15:27:45] Loaded state                             channel=Info run_id=895ae9c7-4095-11e7-8838-fa30d7d11bb1 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 pipe.go:83 manager.go:48 core.go:57 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" chainId=localbloqnetwork lastBlockHeight=656811 lastBlockHash=
DBUG[05-24|15:27:45] Loaded pipe with application manager     channel=Trace run_id=895ae9c7-4095-11e7-8838-fa30d7d11bb1 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 convention.go:35 log.go:143 convention.go:60 convention.go:45 core.go:61 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core]"
DBUG[05-24|15:27:45] Loaded Tendermint sub-configuration      channel=Trace run_id=895ae9c7-4095-11e7-8838-fa30d7d11bb1 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 convention.go:35 log.go:143 convention.go:60 convention.go:45 tendermint.go:103 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" chainId=localbloqnetwork genesisFile=/home/monax/.monax/chains/localbloqnetwork/genesis.json nodeLocalAddress=0.0.0.0:46656 moniker=localbloqnetwork_full_000 seeds= fastSync=false rpcLocalAddress=0.0.0.0:46657 databaseDirectory=/home/monax/.monax/chains/localbloqnetwork/data/tendermint/data privateValidatorFile=/home/monax/.monax/chains/localbloqnetwork/priv_validator.json privValFile=priv_validator.json
DBUG[01-01|00:00:00] Loaded PrivValidator                     channel=Info run_id=895ae9c7-4095-11e7-8838-fa30d7d11bb1 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 capture.go:43 handler_go14.go:14 handler_go14.go:14 logger.go:120 logger.go:146 priv_validator.go:122 tendermint.go:110 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve captured_logging_source=tendermint_log15 module=types file=/home/monax/.monax/chains/localbloqnetwork/priv_validator.json privValidator="PrivValidator{E0DE09DC0D42F255BBF4D16FA79445555905790C LH:656812, LR:0, LS:3}"
INFO[05-24|15:27:45] Force disabling Tendermint's native RPC  channel=Info run_id=895ae9c7-4095-11e7-8838-fa30d7d11bb1 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 tendermint.go:118 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" provided_rpc_laddr=0.0.0.0:46657
panic: Paniced on a Sanity Check: Expected storeHeight (656812) and stateHeight (656811) to match.

goroutine 1 [running]:
panic(0x561a116dc6e0, 0xc420ec4320)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common.PanicSanity(0x561a116dc6e0, 0xc420ec4300)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common/errors.go:26 +0xe2
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state.(*Handshaker).ReplayBlocks(0xc4204f9380, 0x0, 0x0, 0x0, 0x0, 0x561a11b0fb00, 0xc420ec4160, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state/execution.go:400 +0xda4
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state.(*Handshaker).Handshake(0xc4204f9380, 0x561a11b11200, 0xc42006c120, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state/execution.go:329 +0x485
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc42006c120, 0xc420250be0, 0x15)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/proxy/multi_app_conn.go:100 +0x208
github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common.(*BaseService).Start(0xc42006c120, 0x0, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common/service.go:96 +0x548
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/node.NewNode(0x561a11b11820, 0xc4200246b0, 0xc42049e1e0, 0x561a11b03ca0, 0xc4201716a0, 0x2)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/node/node.go:68 +0x485
github.com/hyperledger/burrow/consensus/tendermint.NewTendermint(0xc42006d0e0, 0x561a11b0f2c0, 0xc4200cd900, 0x561a11b0df40, 0xc4201870b0, 0xc4201870b0, 0x561a10b42baa, 0x561a11b05e60)
	/go/src/github.com/hyperledger/burrow/consensus/tendermint/tendermint.go:123 +0x114b
github.com/hyperledger/burrow/consensus.LoadConsensusEngineInPipe(0xc42006d0e0, 0x561a11b118c0, 0xc42047a680, 0x24, 0x0)
	/go/src/github.com/hyperledger/burrow/consensus/consensus.go:30 +0x155
github.com/hyperledger/burrow/core.NewCore(0xc42000c0e9, 0x10, 0xc42006d0e0, 0xc42006d3b0, 0x561a11b0df40, 0xc4201872f0, 0x4, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/core/core.go:63 +0x360
github.com/hyperledger/burrow/cmd.NewCoreFromDo(0xc4204ea2a0, 0xc42001400f, 0x2a, 0x561a1111ef2a)
	/go/src/github.com/hyperledger/burrow/cmd/serve.go:149 +0xa88
github.com/hyperledger/burrow/cmd.ServeRunner.func1(0xc4204fa000, 0x561a11b5f830, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/cmd/serve.go:167 +0xcb
github.com/hyperledger/burrow/vendor/github.com/spf13/cobra.(*Command).execute(0xc4204fa000, 0x561a11b5f830, 0x0, 0x0, 0xc4204fa000, 0x561a11b5f830)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/spf13/cobra/command.go:575 +0x43b
github.com/hyperledger/burrow/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x561a11afbcc0, 0x1, 0x1, 0xc4204fa000)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/spf13/cobra/command.go:661 +0x369
github.com/hyperledger/burrow/vendor/github.com/spf13/cobra.(*Command).Execute(0x561a11afbcc0, 0x0, 0xc4204f80c0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/spf13/cobra/command.go:620 +0x2d
github.com/hyperledger/burrow/cmd.Execute()
	/go/src/github.com/hyperledger/burrow/cmd/burrow.go:46 +0x33d
main.main()
	/go/src/github.com/hyperledger/burrow/cmd/burrow/main.go:22 +0x16
DBUG[05-24|15:28:30] Loading configuration for serve command  channel=Trace run_id=a429b2ed-4095-11e7-88fa-cbc76ee83e5f trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 info_trace_logger.go:139 convention.go:60 serve.go:133 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve chainId=localbloqnetwork workingDirectory=/home/monax/.monax/chains/localbloqnetwork dataDirectory=/home/monax/.monax/chains/localbloqnetwork/data genesisFile=/home/monax/.monax/chains/localbloqnetwork/genesis.json
DBUG[05-24|15:28:30] Modules configured                       channel=Trace run_id=a429b2ed-4095-11e7-88fa-cbc76ee83e5f trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 info_trace_logger.go:139 convention.go:60 serve.go:147 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve consensusModule=tendermint-0.8 applicationManager=burrowmint-0.16
DBUG[01-01|00:00:00] Starting EventSwitch                     channel=Info run_id=a429b2ed-4095-11e7-88fa-cbc76ee83e5f trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 capture.go:43 handler_go14.go:14 handler_go14.go:14 logger.go:120 logger.go:142 service.go:93 core.go:52 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve captured_logging_source=tendermint_log15 module=events impl=EventSwitch
INFO[05-24|15:28:30] Loading BurrowMint                       channel=Info run_id=a429b2ed-4095-11e7-88fa-cbc76ee83e5f trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 manager.go:47 core.go:57 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core]" compatibleConsensus=tendermint-0.8 burrowMintVersion=burrowmint-0.16.2
INFO[05-24|15:28:30] Loaded state                             channel=Info run_id=a429b2ed-4095-11e7-88fa-cbc76ee83e5f trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 pipe.go:83 manager.go:48 core.go:57 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" chainId=localbloqnetwork lastBlockHeight=656811 lastBlockHash=
DBUG[05-24|15:28:30] Loaded pipe with application manager     channel=Trace run_id=a429b2ed-4095-11e7-88fa-cbc76ee83e5f trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 convention.go:35 log.go:143 convention.go:60 convention.go:45 core.go:61 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core]"
DBUG[05-24|15:28:30] Loaded Tendermint sub-configuration      channel=Trace run_id=a429b2ed-4095-11e7-88fa-cbc76ee83e5f trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 convention.go:35 log.go:143 convention.go:60 convention.go:45 tendermint.go:103 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" chainId=localbloqnetwork genesisFile=/home/monax/.monax/chains/localbloqnetwork/genesis.json nodeLocalAddress=0.0.0.0:46656 moniker=localbloqnetwork_full_000 seeds= fastSync=false rpcLocalAddress=0.0.0.0:46657 databaseDirectory=/home/monax/.monax/chains/localbloqnetwork/data/tendermint/data privateValidatorFile=/home/monax/.monax/chains/localbloqnetwork/priv_validator.json privValFile=priv_validator.json
DBUG[01-01|00:00:00] Loaded PrivValidator                     channel=Info run_id=a429b2ed-4095-11e7-88fa-cbc76ee83e5f trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 capture.go:43 handler_go14.go:14 handler_go14.go:14 logger.go:120 logger.go:146 priv_validator.go:122 tendermint.go:110 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve captured_logging_source=tendermint_log15 module=types file=/home/monax/.monax/chains/localbloqnetwork/priv_validator.json privValidator="PrivValidator{E0DE09DC0D42F255BBF4D16FA79445555905790C LH:656812, LR:0, LS:3}"
INFO[05-24|15:28:30] Force disabling Tendermint's native RPC  channel=Info run_id=a429b2ed-4095-11e7-88fa-cbc76ee83e5f trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 tendermint.go:118 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" provided_rpc_laddr=0.0.0.0:46657
panic: Paniced on a Sanity Check: Expected storeHeight (656812) and stateHeight (656811) to match.

goroutine 1 [running]:
panic(0x55d7e4f146e0, 0xc4204fcf40)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common.PanicSanity(0x55d7e4f146e0, 0xc4204fcf20)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common/errors.go:26 +0xe2
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state.(*Handshaker).ReplayBlocks(0xc4204e7830, 0x0, 0x0, 0x0, 0x0, 0x55d7e5347b00, 0xc4204fcd30, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state/execution.go:400 +0xda4
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state.(*Handshaker).Handshake(0xc4204e7830, 0x55d7e5349200, 0xc42006c120, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state/execution.go:329 +0x485
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc42006c120, 0xc420459400, 0x15)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/proxy/multi_app_conn.go:100 +0x208
github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common.(*BaseService).Start(0xc42006c120, 0x0, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common/service.go:96 +0x548
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/node.NewNode(0x55d7e5349820, 0xc4200246b8, 0xc42042c6e0, 0x55d7e533bca0, 0xc4204b0460, 0x2)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/node/node.go:68 +0x485
github.com/hyperledger/burrow/consensus/tendermint.NewTendermint(0xc42006d0e0, 0x55d7e53472c0, 0xc4200ca730, 0x55d7e5345f40, 0xc4201984e0, 0xc4201984e0, 0x55d7e437abaa, 0x55d7e533de60)
	/go/src/github.com/hyperledger/burrow/consensus/tendermint/tendermint.go:123 +0x114b
github.com/hyperledger/burrow/consensus.LoadConsensusEngineInPipe(0xc42006d0e0, 0x55d7e53498c0, 0xc420087000, 0x24, 0x0)
	/go/src/github.com/hyperledger/burrow/consensus/consensus.go:30 +0x155
github.com/hyperledger/burrow/core.NewCore(0xc42000c0e9, 0x10, 0xc42006d0e0, 0xc42006d3b0, 0x55d7e5345f40, 0xc420199300, 0x4, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/core/core.go:63 +0x360
github.com/hyperledger/burrow/cmd.NewCoreFromDo(0xc4204d42a0, 0xc42001400f, 0x2a, 0x55d7e4956f2a)
	/go/src/github.com/hyperledger/burrow/cmd/serve.go:149 +0xa88
github.com/hyperledger/burrow/cmd.ServeRunner.func1(0xc4204e8000, 0x55d7e5397830, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/cmd/serve.go:167 +0xcb
github.com/hyperledger/burrow/vendor/github.com/spf13/cobra.(*Command).execute(0xc4204e8000, 0x55d7e5397830, 0x0, 0x0, 0xc4204e8000, 0x55d7e5397830)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/spf13/cobra/command.go:575 +0x43b
github.com/hyperledger/burrow/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x55d7e5333cc0, 0x1, 0x1, 0xc4204e8000)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/spf13/cobra/command.go:661 +0x369
github.com/hyperledger/burrow/vendor/github.com/spf13/cobra.(*Command).Execute(0x55d7e5333cc0, 0x0, 0xc4204e60c0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/spf13/cobra/command.go:620 +0x2d
github.com/hyperledger/burrow/cmd.Execute()
	/go/src/github.com/hyperledger/burrow/cmd/burrow.go:46 +0x33d
main.main()
	/go/src/github.com/hyperledger/burrow/cmd/burrow/main.go:22 +0x16

**Comment by silasdavis** [comment]
Resolved by: https://github.com/hyperledger/burrow/pull/595, on develop waiting to be released.
