### ISSUE TITLE
[docs] README.md links to non-existent file

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/burrow#619]
In https://github.com/hyperledger/burrow/blob/master/README.md#usage, the link "javascript api" points to non-existent file (https://github.com/hyperledger/burrow.js).

**Comment by dmjones500** [comment]
This comment was posted on the Slack channel in April:

> The JS libraries, afaik, were not moved into the hyperledger repository and remain under Monax's github account. See here:
https://github.com/monax/legacy-contracts.js
https://github.com/monax/legacy-db.js
