### ISSUE TITLE
[docs] specs/api.md points to non-existent file

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/burrow#620]
The link "burrow-js" in https://github.com/hyperledger/burrow/blob/master/docs/specs/api.md points to non-existent https://github.com/hyperledger/burrow.js.

**Comment by silasdavis** [comment]
thanks, fixed in https://github.com/hyperledger/burrow/commit/2ba8decaed59816f602ecfa173bd96b2568b93e0
