### ISSUE TITLE
Error initializing DB: sync /home/monax/.monax/data/burrowmint/data/burrowmint.db: invalid argument

### ISSUE THREAD

**Issue by RobertDiebels** [hyperledger/burrow#654]
Please include in your bug report:

- [ x ] `burrow version` (docker image tag or branch if built from source)  
017.0
- [ ] `monax version` (if applicable)
- [ ] `go version` (if applicable)
- [ x ] `docker version` (if applicable) 
17.05.0-ce 
- [ x ] operating system details (osx/windows/linux) 
Windows 10
- [ x ] what you expected to happen
I expected burrow to boot leveldb.
- [ x ] what actually happened
LevelDB threw an Invalid argument exception
- [ x ] steps to reproduction
1. Run: docker run -v /c/Users/$LocalUser/Containers/burrowconfig:/home/monax/.monax --rm --name burrow-node quay.io/monax/db:0.17.0
2. Behold the `Invalid argument` error.

**Info**
So I did some digging before I dropped an issue here. I found an issue (where I also commented) https://github.com/google/leveldb/issues/281 which describes the same issue.
It might have something to do with the fact that Docker Quickstart Terminal uses shared folders for volumes on Windows.

Maybe @silasdavis could tell me how he tested the container? That would be great.

**Edit:** I can't reproduce on Linux so I guess this is Windows only. Which is no longer supported in 0.17.0 of the Monax-cli I believe. Is this also the case for Burrow?

**Comment by silasdavis** [comment]
@RobertDiebels looks like it is a Windows issue. Not supporting Windows is more of a bandwidth issue rather than anything else. A more direct way to do want you want would just be this though:

```shell
go get -u github.com/hyperledger/burrow # would be 0.17.1, but I'd recommned you use that
cd /c/Users/$LocalUser/Containers/burrowconfig
burrow serve
```

You will need Go installed and the `%GOPATH%` environment variable set with `%GOPATH%/bin` in your `%PATH%`. But that should serve from your config dir and will write a data directory there.

**Comment by RobertDiebels** [comment]
@silasdavis thanks for the answer. I can run on Linux so it's not that much of a problem. I do need docker though. Since I want to setup Burrow to run in Kubernetes. 

Thanks again though! I'll close the issue.
