### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by kevinaquick** [hyperledger/burrow#655]
Hi

We have been trying to install Burrow following the instructions, but have been unable to do so.

Details as follows:

We are running Ubuntu 16.04.3
Monax CLI Version: 0.16.0
go version go1.6.2 linux/amd64

Following the install instructions and running the following from the command line:

go get -d github.com/hyperledger/burrow

We get the following error:
"can't load package: package github.com/hyperledger/burrow: no buildable Go source files in /root/.go/src/github.com/hyperledger/burrow"

Not to be totally thrown by this we did try installing by hand by going to:
/.go/src/github.com/hyperledger/burrow/cmd  (where .go is our $GOPATH) and running go install from there however, this threw up a list of packages which were missing (tendermint related etc). SO we went through and installed each of these individually except one which wouldn't install - namely:

github.com/tendermint/go-p2p

which throws up the error:

# github.com/tendermint/go-p2p
../../../tendermint/go-p2p/peer.go:169: cannot use p.PubKey() (type "github.com/tendermint/go-crypto".PubKeyEd25519) as type "github.com/tendermint/go-crypto".PubKey in argument to peerNodeInfo.PubKey.Equals
../../../tendermint/go-p2p/secret_connection.go:51: invalid type assertion: locPrivKey.PubKey().("github.com/tendermint/go-crypto".PubKeyEd25519) (non-interface type "github.com/tendermint/go-crypto".PubKey on left)
../../../tendermint/go-p2p/secret_connection.go:99: invalid type assertion: remPubKey.("github.com/tendermint/go-crypto".PubKeyEd25519) (non-interface type "github.com/tendermint/go-crypto".PubKey on left)
../../../tendermint/go-p2p/secret_connection.go:258: invalid type assertion: locPrivKey.Sign(challenge[:]).("github.com/tendermint/go-crypto".SignatureEd25519) (non-interface type "github.com/tendermint/go-crypto".Signature on left)
../../../tendermint/go-p2p/secret_connection.go:273: cannot use pubKey (type "github.com/tendermint/go-crypto".PubKeyEd25519) as type "github.com/tendermint/go-crypto".PubKey in field value
../../../tendermint/go-p2p/secret_connection.go:273: cannot use signature (type "github.com/tendermint/go-crypto".SignatureEd25519) as type "github.com/tendermint/go-crypto".Signature in field value
../../../tendermint/go-p2p/secret_connection.go:297: cannot use remSignature (type "github.com/tendermint/go-crypto".SignatureEd25519) as type "github.com/tendermint/go-crypto".Signature in argument to remPubKey.VerifyBytes
../../../tendermint/go-p2p/switch.go:157: invalid type assertion: nodePrivKey.PubKey().("github.com/tendermint/go-crypto".PubKeyEd25519) (non-interface type "github.com/tendermint/go-crypto".PubKey on left)
../../../tendermint/go-p2p/switch.go:216: cannot use peer.PubKey() (type "github.com/tendermint/go-crypto".PubKeyEd25519) as type "github.com/tendermint/go-crypto".PubKey in argument to sw.nodeInfo.PubKey.Equals
../../../tendermint/go-p2p/switch.go:534: invalid type assertion: privKey.PubKey().("github.com/tendermint/go-crypto".PubKeyEd25519) (non-interface type "github.com/tendermint/go-crypto".PubKey on left)
../../../tendermint/go-p2p/switch.go:534: too many errors
root@kmi-blockcn02:~/.go/src/github.com/hyperledger/burrow/cmd#

Any help and suggestions would be appreciated

Thanks
Kevin

**Comment by silasdavis** [comment]
Hi Kevin,

Burrow is not `go get`able since we don't vendor our dependencies. Maybe it should be (I am working on a release where it is). If you want to install a development version you'll need to get the repo (go get has done this, don't worry about the no buildable files message) and install our dependencies using glide, do:

```
cd $GOPATH/src/github.com/hyperledger/burrow
make install_vendor
make build
```

You'll then find binaries under `./target/burrow`.

Bear in mind at this time the standard way to interact with Burrow is through the `monax` tool: https://monax.io/docs/getting-started/. We are transitioning to a more standalone experience.

**Comment by kevinaquick** [comment]
Thank you fro getting back with the above details, however I seem to be having trouble with these namely the "make build" stage as I get the following error:

Checking code for formatting style compliance.
go build -o /root/.go/src/github.com/hyperledger/burrow/target/burrow-a140ca6 ./cmd/burrow
vendor/golang.org/x/net/trace/trace.go:67:2: cannot find package "context" in any of:
	/root/.go/src/github.com/hyperledger/burrow/vendor/context (vendor tree)
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/root/.go/src/context (from $GOPATH)
Makefile:103: recipe for target 'build_db' failed
make: *** [build_db] Error 1

Kevin

**Comment by silasdavis** [comment]
You'll need to upgrade your go version to >= 1.7, you are on 1.6 before the `context` package was moved to stdlib. 1.6 is a year and a half old. I'd recommend go 1.8 or 1.9.

**Comment by sadaf2605** [comment]
I am trying to install burrow on my OSX machine. I have followed the tutorial and it is stuck.

$ go version
go version go1.9.2 darwin/amd64

$ go get -d github.com/hyperledger/burrow
can't load package: package github.com/hyperledger/burrow: no Go files in /Users/sadafnoor/go/src/github.com/hyperledger/burrow

When I tried to make:

$ make install_vendor
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by mohitsharma18** [comment]
facing the same issue even with Go 1.9

Makefile:82: recipe for target 'install_vendor' failed
make: *** [install_vendor] Error 1

Please help

- Mohit

**Comment by cupaco** [comment]
Having the same issue with Go 1.9.2

go version go1.9.2 linux/amd64

can't load package: package github.com/hyperledger/burrow: no Go files in /root/go/src/github.com/hyperledger/burrow

Please help

**Comment by CryptoKass** [comment]
Ensure your $GOPATH is setup correct. If you `export GOPATH=/Users/$USER/go` then try to run `make build` again.
