### ISSUE TITLE
Glide install from source fails due to outdated / migrated dependencies on tendermint packages

### ISSUE THREAD

**Issue by tommling** [hyperledger/burrow#660]
**Summary:**
The install process laid out in https://github.com/hyperledger/burrow#for-developers is slightly outdated. I have found this to be true at least in repeated observation that the go-clist package no longer exists in the github.com/tendermint/tendermint repository. A lot of the packages that were present here have been migrated to github.com/tendermint/tmlibs/ as the tendermint project has matured.

- [a140ca605340c6adfd84ed6123a5a766d0eaca55] `burrow version`
- [0.9.2] `go version` (if applicable)
- [ Ubuntu 16.04 (virtual) ] operating system details (osx/windows/linux)
- [ Smooth `gliding` installation ] what you expected to happen
- [ Crash and burn installation ] what actually happened
- [ https://github.com/hyperledger/burrow#for-developers ] steps to reproduction

**Initial observation:**
```
>>>>>#glide install
...
...
[INFO]	--> Fetching gopkg.in/fatih/set.v0
[INFO]	--> Fetching gopkg.in/go-playground/validator.v8
[INFO]	--> Fetching gopkg.in/tylerb/graceful.v1
[INFO]	--> Fetching gopkg.in/yaml.v2

Password for 'https://github.com': 
[WARN]	Unable to checkout github.com/tendermint/go-clist
[ERROR]	Update failed for github.com/tendermint/go-clist: Unable to get repository: Cloning into '/home/t/.glide/cache/src/https-github.com-tendermint-go-clist'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/tendermint/go-clist/'
: exit status 128
[ERROR]	Failed to install: Unable to get repository: Cloning into '/home/t/.glide/cache/src/https-github.com-tendermint-go-clist'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/tendermint/go-clist/'
: exit status 128
```

**Side note:**
Also, note that the workaround in ( https://github.com/Masterminds/glide/issues/675 ) recommends setting global git config via command line with:
`git config --global url."git@github.com:".insteadOf "https://github.com/"`

This avoids the authentication catch, but does not fix the problem.

**Propose Fix:**
A pull request on this issue to develop that updates glide.lock and glide.yaml that points to new tendermint/tmlibs repo. This does not entierly fix the problem because the tendermint version currently used is ~0.9.2, while the migration occurred at a later version closer to ~0.12.1 I believe.

**Comment by tommling** [comment]
On further investigation, this is not a good approach because it requires patching the version of tendermint.

**Comment by silasdavis** [comment]
fixed by: https://github.com/hyperledger/burrow/pull/672
