### ISSUE TITLE
[EVM] EVM Compliance Issues

### ISSUE THREAD

**Issue by smblucker** [hyperledger/burrow#674]
The following are a compiled list of issues related to the EVM; it includes all issues compiled in [#588](https://github.com/hyperledger/burrow/issues/588) by @silasdavis as well as subsequent issues:

Table of Contents:
- EIP Implementation Issues
- Bad/Invalid Jumpdest Issues
- Invalid Opcodes
- Chain Stopping Issues

**EIP Implementation Issues**
Byzantium:
- [INVALID opcode - #601](https://github.com/hyperledger/burrow/issues/601)
- [STATICCALL opcode - #594](https://github.com/hyperledger/burrow/issues/594)

- [REVERT opcode - #600](https://github.com/hyperledger/burrow/issues/600)

- [RETURNDATASIZE and RETURNDATACOPY opcodes- #705](https://github.com/hyperledger/burrow/issues/705)

Constantinople:
- [SHL, SHR, and SAR opcodes - #705](https://github.com/hyperledger/burrow/issues/706) 

**Bad/Invalid Jumpdest Issues**

- [String concatenation issue - #300](https://github.com/hyperledger/burrow/issues/300), **see failing test**: https://github.com/monax/bosmarmot/blob/develop/legacy-contracts.js/failing%20tests/%2327.js

- [Subcurrency test causes panic in EVM tool but not burrow - #675](https://github.com/hyperledger/burrow/issues/675)

**Invalid Opcodes**

- [Bad EVM interpretation on non-opcode - #526](https://github.com/hyperledger/burrow/issues/526), **see failing test**: https://github.com/monax/bosmarmot/blob/develop/legacy-contracts.js/failing%20tests/WebSocket.js

**Chain Stopping Issues**

- [Storage/Merkle related panic #626](https://github.com/hyperledger/burrow/issues/626)

- [Storage/BlockCache related panic #627](https://github.com/hyperledger/burrow/issues/627)

**Comment by kyriediculous** [comment]
Is there an ETA on exceptions rather than using if-else-> Boolean ? 

What version of solc is burrow using atm?

Thank you in advance!

**Comment by compleatang** [comment]
@kyriediculous we test against solc 0.4.22 at the moment.

**Comment by kyriediculous** [comment]
@compleatang That's super awesome ! 

That means the five-types model might actually work well now that we can return dynamic types from functions (despite from gas cost maybe)

**Comment by silasdavis** [comment]
Finally fixed!
