### ISSUE TITLE
unable to connect burrow and nodejs

### ISSUE THREAD

**Issue by mohitsharma18** [hyperledger/burrow#680]
- `burrow version`: 0.17.1
- `monax version`: 0.18.0
- `go version`: go1.9.3 linux/amd64
- `docker version`: 17.12.0-ce
- `operating system details`: linux Ubuntu 16.04

- `what you expected to happen`

Burrow must be connected with the nodejs server

- `what actually happened`

Burrow is not connecting with the nodejs server

- `steps to reproduction`

after stating the burrow, it start creating blocks every second.
But when we try to connect it with the nodejs server is throws the error

'code':

var burrowFactory = require('@monax/legacy-db');

console.log(burrowFactory);

var contracts = require('@monax/legacy-contracts');

console.log(contracts);

var burrow = burrowFactory.createInstance('http://10.0.3.198:1337/rpc');

console.log(burrow);

`Here burrow thows an error as given below`

Burrow {
  server: undefined,
  _unsafe: 
   Unsafe {
     server: undefined,
     _validator: SinglePolicyValidator { _policy: true } },
  _accounts: 
   Accounts {
     server: undefined,
     _unsafe: Unsafe { server: undefined, _validator: [Object] } },
  _blockChain: BlockChain { server: undefined },
  _consensus: Consensus { server: undefined },
  _events: 
   Events {
     _pollingInterval: 1000,
     server: undefined,
     _sub: { [Function: HttpEventSub] super_: [Function: EventSub] } },
  _namereg: 
   NameReg {
     server: undefined,
     _unsafe: Unsafe { server: undefined, _validator: [Object] },
     _events: Events { _pollingInterval: 1000, server: undefined, _sub: [Object] } },
  _network: Network { server: undefined },
  _transactions: 
   Transactions {
     server: undefined,
     _unsafe: Unsafe { server: undefined, _validator: [Object] } } }
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Method not found: burrow.toJSON".
(node:5915) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot convert a Symbol value to a string
(node:5915) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

could anybody tell me what is the error or what is the correct way to do it????

Thanks
Mohit

**Comment by silasdavis** [comment]
It doesn't look like you are requiring legacy-contracts... If this is still an issue can you open at http://github.com/monax/bosmarmot where this tooling now lives.
