### ISSUE TITLE
Unable to Connect burrow server using node js code

### ISSUE THREAD

**Issue by Gaurav094** [hyperledger/burrow#684]
Please include in your bug report:

- [ 0.17.1] `burrow version` (docker image tag or branch if built from source)
- [0.18.0 ] `monax version` (if applicable)
- [ 1.9.3] `go version` (if applicable)
- [ 17.12.0-ce] `docker version` (if applicable)
- [ linux- ubuntu 16.0.4] operating system details (osx/windows/linux)
- [Want to connect burrow server using monax/legacy-db to access burrow chain functionality ] what you expected to happen
- [ **Burrow {
  server: undefined,
  _unsafe: 
   Unsafe {
     server: undefined,
     _validator: SinglePolicyValidator { _policy: true } },
  _accounts: 
   Accounts {
     server: undefined,
     _unsafe: Unsafe { server: undefined, _validator: [SinglePolicyValidator] } },
  _blockChain: BlockChain { server: undefined },
  _consensus: Consensus { server: undefined },
  _events: 
   Events {
     _pollingInterval: 1000,
     server: undefined,
     _sub: { [Function: HttpEventSub] super_: [Function: EventSub] } },
  _namereg: 
   NameReg {
     server: undefined,
     _unsafe: Unsafe { server: undefined, _validator: [SinglePolicyValidator] },
     _events: Events { _pollingInterval: 1000, server: undefined, _sub: [Function] } },
  _network: Network { server: undefined },
  _transactions: 
   Transactions {
     server: undefined,
     _unsafe: Unsafe { server: undefined, _validator: [SinglePolicyValidator] } } }
Accounts {
  server: undefined,
  _unsafe: 
   Unsafe {
     server: undefined,
     _validator: SinglePolicyValidator { _policy: true } } }
Received request for details.
server started at 10.0.0.141:8000
Burrow error:  Call of method "toJSON" with parameters 'server' responded with "Error: socket hang up".
(node:4743) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `reject` of 'undefined' or 'null'.
    at values.next.then (/home/gauravagarwal/.monax/apps/legacydb/node_modules/@nodeguy/json-rpc/lib/index.js:13:57)
    at <anonymous>
(node:4743) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4743) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**
] what actually happened

screenshot of error-
https://user-images.githubusercontent.com/36070107/36086471-9c575f16-0ff2-11e8-867b-ffffab589a54.png

my code 
var burrowFactory = require('@monax/legacy-db');

  var burrow = burrowFactory.createInstance("http://172.17.0.3:1337/rpc");//got the ip use monax chains ip <CHIAN-NAME>
  console.log(burrow);
  console.log(burrow.accounts());

**Comment by silasdavis** [comment]
I think it will be easier to provide some help on this on hyperledger chat, it looks like you might be running on a non-standard part
