### ISSUE TITLE
Unable to sync newly created accounts in burrow chain

### ISSUE THREAD

**Issue by Gaurav094** [hyperledger/burrow#689]
Please include in your bug report:

[ 0.17.1] burrow version (docker image tag or branch if built from source)
[0.18.0 ] monax version (if applicable)
[ 1.9.3] go version (if applicable)
[ 17.12.0-ce] docker version (if applicable)
[ linux- ubuntu 16.0.4] operating system details (osx/windows/linux)
- [ Create a new account in running burrow chain dynamically using rpc endpoint ] what you expected to happen

- [ I am able to create new account using rpc endpoint using below code:

var burrowFactory = require('@monax/legacy-db');
let chainUrl = 'http://localhost:1337/rpc';
let accounts = require('./accounts.json');
var burrow = burrowFactory.createInstance(chainUrl);
var myAccount = burrow.accounts();
myAccount.genPrivAccount(accounts.node1_full_000, function(error, result){
if (!error){
console.log('result = ', JSON.stringify(result,null,4));
}
else{
console.log(error);
}
});

I am able to get the address along with pubKey and PrivKey but I cannot see this account is added in blockchain when I run the below code:

function showAccounts(error,data){
if(data){
var str = JSON.stringify(data,null,4);
console.log(str);
} 
else{
console.log(error); 
}
}

var loadAccounts = ()=>{
var burrow = burrowDbFactory.createInstance("http://localhost:1337/rpc");
var accounts = burrow.accounts();
accounts.getAccounts(showAccounts);
}

Neither any file in burrow chain are reflected. ] what actually happened
- [ 
Tried to add manually newly generated address in burrow files but no outcomes
] steps to reproduction
![accountcreate](https://user-images.githubusercontent.com/36070107/36364554-c29bace0-156a-11e8-9a46-527b96953279.png)

**Comment by silasdavis** [comment]
I think you got some resolution to this - but it is not an issue with Burrow but with lack of documentation of our JS libs. Closing here for that reason.
