### ISSUE TITLE
[Docker] remove the bash scripting layer

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#70]
all of the `ecm` stuff (currently bash start scripts in this repository in the docker directory) we currently have in bash scripts should be collapsed into the erisdb boot process. 

The boot process should respect a variety of env vars currently encapsulated in the ecm scripts in this repository. The docker images should be refactored to remove those bash scripts and just boot the edb binary.

Two env vars we will use frequently but that I do not think are currently respected:

`ERISDB_FAST_SYNC` which should be an easy way for us to turn fast_sync to try via env vars when booting from containers.
`ERISDB_SEEDS` which should be an easy way for us to pass in the IP address of the seed to the binary.

Obviously, all env vars should overwrite anything in a static config file.

**Comment by compleatang** [comment]
I think I logged a duplicate issue here. In `feature-smaller-docker` I made the necessary switches for the dockerfile to *only* reference the binary. The bash wrapper **is** in the dockerfile so folks can use if needed. However, by default the binary rather than the bash wrapper is called by the docker CMD. Also, cli, once the branch of the same name is merged there, will **only** utilize the binary. Tl'dr the bash wrapper can safely be removed in 0.12.1 once we smoke test that no weird side effects from this change settle.

**Comment by benjaminbollen** [comment]
the bash script set `ERIS_DB_WORKDIR`

```
if [ "$ERIS_DB_WORKDIR" = "" ]; then
	ERIS_DB_WORKDIR="$ERIS/chains/$CHAIN_ID"
fi

if [ ! -d "$ERIS_DB_WORKDIR" ]; then
	mkdir -p $ERIS_DB_WORKDIR
	ifExit "Error making working directory $ERIS_DB_WORKDIR"
fi

export ERIS_DB_WORKDIR
export ERIS_DB_DATADIR=$ERIS_DB_WORKDIR/data
```

also adds `$CONFIG_OPTS` to serve; does cli deal with this?

**Comment by silasdavis** [comment]
Bumped up estimate... Time taken suggest more than a 1. Is this for current sprint?

**Comment by compleatang** [comment]
CLI currently does not use the bash script at all.... It sets the env vars and then calls the eris-db binary directly. It was a 1 because all that needs to happen is the build script updated and the bash script removed from the repo... 

https://github.com/eris-ltd/eris-cli/blob/master/chains/chains.go#L383-L390

**Comment by silasdavis** [comment]
Done and supercede
