### ISSUE TITLE
[Keys] Support in-burrow crypto API instead of external monax.keys REST API

### ISSUE THREAD

**Issue by phymbert** [hyperledger/burrow#702]
Would be nice to use burrow without any external crypto API REST server call like monax.keys.

There is already everything in MockKeyClient and tendermint/go-crypto to do it: allow an entry point in config API to override default monax.keys dependency within kernel creation:

1. Make ValidatorAddress not mandatory
2. Create tendermint.NewNode with a new burrow privValidator API
3. New entry in BurrowConfig that wrap Keys or new InMemoryCrypto struct
3. Support flexible API to acccess node private key in InMemoryCrypto

Example to be discussed:
```go
type BurrowConfig struct {
	// ValidatorAddress *acm.Address =>  Moved to Keys
	GenesisDoc       *genesis.GenesisDoc
	Tendermint       *tendermint.BurrowTendermintConfig
        // Keys             *keys.KeysConfig ==> Moved to CryptoConfig and Keys Server
	Crypto           *CryptoConfig // New top crypto config
	RPC              *rpc.RPCConfig
	Logging          *logging_config.LoggingConfig
}

type CryptoConfig struct {
	KeysServer  *keys.KeysConfig // If the user wants to keep current behavior
	InMemoryCrypto *InMemoryCrypto // If user wants in-node crypto
}

type InMemoryCrypto struct {
	Address    acm.Address
	PrivateKey [ed25519.PrivateKeySize]byte
	PublicKey  []byte
} 

type KeysConfig struct {
	URL string,
        ValidatorAddress *acm.Address
}

```
I think it is usefull for user who want to use only burrow and tendermint while minimizing REST invocations.

Thank you for your review, if you are ok with this idea I may submit a PR.

_like burrow, keep it up!_

**Comment by silasdavis** [comment]
Thanks for the issue.

I am not against the idea of self-hosted keys in Burrow. I am wary of introducing private key matter into Config.

However I'd like to step back and thing about what we are trying to achieve here, I think:
1. Run Burrow in a single process without keys
2. Be able to form a genesis doc to start a chain - which requires the public keys

One idea that I like is that of the validator creating its own key on boot and gossiping its public key around in a 'lazy genesis' process. The key does not need to leave the node. If the node goes down and it has not persisted at least to disk its key this does mean it would need some means to be rebonded on to the network which is probably just moving the problem around - and we tend to think of validator keys as durable identities that may have some long term value attached.

Another option would be to effectively still run a monax-keys service, using the same code, but running it in a single process. I believe that changes I have recently made (https://github.com/monax/bosmarmot/commit/e9a65a5814e7421d71b08f1a9e232ea561e09650) mean that we could relicense it to Apache and pull it in. We have always wanted to point out that monax-keys is unaudited crypto, but it is built on solid libraries and I think we should probably give it a higher status (and ultimately get it audited). The option of replacing it with a remote HSM-based service should always be there.

If we went for this option then I would pull in keys from: https://github.com/monax/bosmarmot/tree/master/keys and we would add the necessary configuration to run keys as a launched service of Burrow but maintain the same interface boundary (just not use a HTTP transport). There could be the option of having Burrow also act as a key server for local applications.

**Comment by phymbert** [comment]
Thank you very much @silasdavis for your anwser, appreciate you are sharing your vision here.

I agree private key within the Config file is not a target, I am trying to start Burrow as an API in my own process: this way the wrapper is responsible of storage and lifecycle of the node private key.
I have yet to understand Tendermint and Burrow impacts on the block consensus and vote algorithm if we generate keys at bootstrap.

I didnt check monax.keys recent changes, actually I didnt manage to start monax inside docker-for-windows, but that's another story!

I have pushed [in this fork](https://github.com/phymbert/burrow/tree/feature/FEATURE-INMEMORY-CRYPTO) changes I would like to see in Burrow, I am sure to move directly mature and existing code of monax.keys is a better option, feel free to tell me wether or not I can submit a PR.


Yes need to be more agnostic to crypto implementation, reintroduce secp256k1 would be good.

**Comment by zramsay** [comment]
@phymbert try starting keys without docker - the docker functionality has been mostly stripped away from the tooling

**Comment by phymbert** [comment]
Thanks @zramsay but this is not my main point: I just dont want my burrow node depends on a centralized PKI or an external server responsible to sign my own node messages.
I have submitted a PR #707 to support this feature, I wish it will be reviewed and maybe merged as a good signal to encourage open source contributions.

**Comment by seanyoung** [comment]
Burrow can do signing and key management itself now, see https://github.com/hyperledger/burrow/pull/776
