### ISSUE TITLE
Black-box test strategy

### ISSUE THREAD

**Issue by b00f** [hyperledger/burrow#708]
Suggestion:

Having different package name for test files will make sure the package will test as a black box entity. 
I suggest you to follow this naming convention for test files, like: 
`package evm_test`
instead of 
`package evm`

you can check this here for more testing strategies in go:
https://stackoverflow.com/questions/19998250/proper-package-naming-for-testing-with-the-go-language

Let me know if you agree with it, then I can help you fixing it.

**Comment by silasdavis** [comment]
This does not strike me as a priority.

**Comment by b00f** [comment]
I figured out that by having different package for testing we can reduce the size of executable file, because some methods can be written in test package. For we can put `NewDeterministicGenesis` method in test package, either `NewConcreteAccountFromSecret`.

If you are busy I can do it.
