### ISSUE TITLE
Issues with draft of api.md

### ISSUE THREAD

**Issue by smblucker** [hyperledger/burrow#745]
There is a substantive issue at LN# 135:

"When using a client-server setup, do NOT send public keys over non-secure connections. The only time this is fine is during development when the keys are nothing but test data and does not protect anything of value. Normally they should either be kept locally and used to sign transactions locally, held on the server where the blockchain client is running, or be passed over secure channels."

I believe what is meant here is that 'private keys' should not be sent over non-secure connections. This is also indicted by the reference to signing transactions, as private keys are used to cryptographically sign data, transactions, etc.

There is another substantive issue at LN# 520:

The HTTP method indicated for GenPrivAccount is 'GET'; this is contradicted by its elaboration at LN# 1927 where the indicated method is 'POST'.

In addition, there are numerous cosmetic and grammatical changes that could be made to clean up this document--see LN#'s 21, 26, 73, 104, 113, 127, 257, 259, 261, 267, 269, 307, 309, 360, 362, 430, 446, 536, 538, 635, 642, 684, 951, 1170, 1213, 1235, 1621, 1692, 1812, 1961, 1980, 2033, and 2039.

**Comment by smblucker** [comment]
If you would like, I could clean this up.

**Comment by compleatang** [comment]
That would be super @smblucker !

**Comment by silasdavis** [comment]
I think this was handler in #746 - ping back if not
