### ISSUE TITLE
make GitHub show `develop` branch by default

### ISSUE THREAD

**Issue by paulvi** [hyperledger/burrow#752]
As pointed in #748, it is not clear when looking at https://github.com/hyperledger/burrow that the code is under active development.

The solution is to change GitHub default shown branch to `develop`

![](https://user-images.githubusercontent.com/1614482/39366339-39d62030-4a66-11e8-8fb7-08253c0d1909.png)

**Comment by silasdavis** [comment]
master should be the default branch, we have since released here

**Comment by silasdavis** [comment]
Actually you were right about this, although master is our release branch, it will be better to have PRs default to develop. Ideally I would really like the home branch you see on first visit to still be master, but PRs to go to develop. I can't have it both ways so I've switched to develop.
