### ISSUE TITLE
[evm] Downstream libraries panic on building if they already invoke `trace`

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#792]
Talking to @guoger in #fabric-evm room regarding a panic they've been seeing on building fabric with burrow's evm.

```
hi, thank you so much for helping us out! by looking at this graph, 
both projects ultimately depend on `x/net/trace`. When we load 
burrow-evm as a plugin, `init` in `trace` is called for the second 
time, which triggers a panic because the `/debug/requests` 
endpoint is registered already.

so I think it's a problem with grpc, instead of tendermint. 
(possibly `go-kit/kit` as well)
```

He also dumped their dep graph which I've attached here.

It seems if we're running a trace init in the evm itself that would be very bad for downstream libraries and we should seek to instantiate that a level "up" from the evm to avoid this if possible.

![dep](https://user-images.githubusercontent.com/590037/41092083-f20f03f8-6a3f-11e8-85c2-95eedb567306.png)

**Comment by silasdavis** [comment]
Spoke to them about this, it's from fabric not us turns out
