### ISSUE TITLE
How i can get my transaction history using  burrow JSONRPC

### ISSUE THREAD

**Issue by Nagaraj007** [hyperledger/burrow#806]
i am running the burrow,i am able to get details of Blocks and block height using JSON RPC, How i can get transaction history.

**Comment by compleatang** [comment]
Currently we have `/status` endpoint which retrieves current blockheight as well as `list_blocks` which returns an array of block information. You can see all of the endpoints on what we call the TM RPC by hitting the `/` endpoint. 

For a locally running node this would typically be something like `curl localhost:46657/` or `curl localhost:46657/status | jq .result.LatestBlockHeight`
