### ISSUE TITLE
Issue in contract deployment

### ISSUE THREAD

**Issue by basilji** [hyperledger/burrow#811]
- [ ] `burrow version` (docker image tag or branch if built from source)
- [ ] `monax version` (if applicable)
- [ ] `go version` (if applicable)
- [ ] `docker version` (if applicable)
- [ ] operating system details (osx/windows/linux)
- [ ] what you expected to happen
- [ ] what actually happened
- [ ] steps to reproduction

burrow version	: 	0.18.1+commit.v0.18.0-100-g19b8b07
go version	:	go1.10.1 linux/amd64
bos version	:	0.2.0+commit.b5f6db7
os		:	Ubuntu 16.04.3 LTS  

Issue :
----------
We were not able to deploy a sample contract. It is giving below error

*************************************************************************************************
With ChainURL                               => tcp://localhost:46657
Using Signer at                             => localhost:10997
Loading monax Jobs Definition File.
Loading monax jobs file                     path => /home/twinapp/chain_dir_newname => epm

*****Executing Job*****

Job Name                                    => defaultAddr
Type                                        => Account
Setting Account                             => 30B96CEC85FED075A452A43CFB51A27BFB146143

*****Executing Job*****

Job Name                                    => deployStorageK
Type                                        => Deploy
Library String                              =>
Contract path                               => idi.sol
Cached Item(s)                              cached? => false
Could not find cached object, compiling...
To Cache                                    Filepath of include:  => a0bbb9f9c11a8640af1674bd8828c41d3021de6eca900875f0cebf8b1d525659.sol
Command Input                               Command:  => [solc --combined-json bin,abi --libraries monax-libs a0bbb9f9c11a8640af1674bd8828c41d3021de6eca900875f0cebf8b1d525659.sol]
Output from command:                        => {"contracts":{"a0bbb9f9c11a8640af1674bd8828c41d3021de6eca900875f0cebf8b1d525659.sol:IdisContractsFTW":{"abi":"[{\"constant\":false,\"inputs\":[{\"name\":\"x\",\"type\":\"uint256\"}],\"name\":\"set\",\"outputs\":[],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"get\",\"outputs\":[{\"name\":\"retVal\",\"type\":\"uint256\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}]","bin":"608060405234801561001057600080fd5b5060df8061001f6000396000f3006080604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c146078575b600080fd5b348015605957600080fd5b5060766004803603810190808035906020019092919050505060a0565b005b348015608357600080fd5b50608a60aa565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a72305820156e0dd82471b100b213740402c63be0b1cd4bc13895d7b8792dc439fda071360029"}},"version":"0.4.25-develop.2018.6.6+commit.59b35fa5.Linux.g++"}
Command Output                              Json:  => {"contracts":{"a0bbb9f9c11a8640af1674bd8828c41d3021de6eca900875f0cebf8b1d525659.sol:IdisContractsFTW":{"abi":"[{\"constant\":false,\"inputs\":[{\"name\":\"x\",\"type\":\"uint256\"}],\"name\":\"set\",\"outputs\":[],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"get\",\"outputs\":[{\"name\":\"retVal\",\"type\":\"uint256\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}]","bin":"608060405234801561001057600080fd5b5060df8061001f6000396000f3006080604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c146078575b600080fd5b348015605957600080fd5b5060766004803603810190808035906020019092919050505060a0565b005b348015608357600080fd5b50608a60aa565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a72305820156e0dd82471b100b213740402c63be0b1cd4bc13895d7b8792dc439fda071360029"}},"version":"0.4.25-develop.2018.6.6+commit.59b35fa5.Linux.g++"}
Response formulated                         name => IdisContractsFTWbin => 608060405234801561001057600080fd5b5060df8061001f6000396000f3006080604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c146078575b600080fd5b348015605957600080fd5b5060766004803603810190808035906020019092919050505060a0565b005b348015608357600080fd5b50608a60aa565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a72305820156e0dd82471b100b213740402c63be0b1cd4bc13895d7b8792dc439fda071360029abi => [{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]
Response                                    name => IdisContractsFTWbin => 608060405234801561001057600080fd5b5060df8061001f6000396000f3006080604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c146078575b600080fd5b348015605957600080fd5b5060766004803603810190808035906020019092919050505060a0565b005b348015608357600080fd5b50608a60aa565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a72305820156e0dd82471b100b213740402c63be0b1cd4bc13895d7b8792dc439fda071360029abi => [{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]
Warning during contract compilation         => Warning: This is a pre-release compiler version, please do not use it in production.
a0bbb9f9c11a8640af1674bd8828c41d3021de6eca900875f0cebf8b1d525659.sol:6:3: Warning: No visibility specified. Defaulting to "public".
  function set(uint x) {
  ^ (Relevant source part starts here and spans across multiple lines).
a0bbb9f9c11a8640af1674bd8828c41d3021de6eca900875f0cebf8b1d525659.sol:10:3: Warning: No visibility specified. Defaulting to "public".
  function get() constant returns (uint retVal) {
  ^ (Relevant source part starts here and spans across multiple lines).

Deploying the only contract in file         path => idi.sol
Abi                                         => [{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]
Bin                                         => 608060405234801561001057600080fd5b5060df8061001f6000396000f3006080604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c146078575b600080fd5b348015605957600080fd5b5060766004803603810190808035906020019092919050505060a0565b005b348015608357600080fd5b50608a60aa565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a72305820156e0dd82471b100b213740402c63be0b1cd4bc13895d7b8792dc439fda071360029
ABI Specification (From Compilers)          => [{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]
Saving ABI                                  => abi/IdisContractsFTW
Deploying Contract                          name => IdisContractsFTW
                                            source => 30B96CEC85FED075A452A43CFB51A27BFB146143code => 608060405234801561001057600080fd5b5060df8061001f6000396000f3006080604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c146078575b600080fd5b348015605957600080fd5b5060766004803603810190808035906020019092919050505060a0565b005b348015608357600080fd5b50608a60aa565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a72305820156e0dd82471b100b213740402c63be0b1cd4bc13895d7b8792dc439fda071360029chain-url => tcp://localhost:46657
                                            defAddr => 30B96CEC85FED075A452A43CFB51A27BFB146143rawErr => Response error: RPC error -32603 - Internal error: runtime error: invalid memory address or nil pointer dereference
Error finalizing contract deploy idi.sol:
There has been an error talking to your monax chain.

Response error: RPC error -32603 - Internal error: runtime error: invalid memory address or nil pointer dereference

Debugging this error is tricky, but don't worry the marmot recovery checklist is...
  * is the 30B96CEC85FED075A452A43CFB51A27BFB146143 account right?
  * is the account you want to use in your keys service: burrow keys list ?
  * is the account you want to use in your genesis.json: see http://localhost:46657/genesis
  * do you have permissions to do what you're trying to do on the chain?
*****************************************************************************************

Steps to reproduce the issue :
------------------------------

export GOROOT="/usr/local/go"
export GOPATH="/home/twinapp/burrowchain"

go get github.com/hyperledger/burrow
cd $GOPATH/src/github.com/hyperledger/burrow
make build

go get github.com/monax/bosmarmot
cd $GOPATH/src/github.com/monax/bosmarmot
make build

mkdir chain_dir_new
cd chain_dir_new

burrow spec --participant-accounts=1 --full-accounts=1 > genesis-spec.json
burrow configure --genesis-spec=genesis-spec.json > burrow.toml

burrow start --validator-index=0 2>burrow.log &

bos --address="30B96CEC85FED075A452A43CFB51A27BFB146143"

where "30B96CEC85FED075A452A43CFB51A27BFB146143" is the address of validator[0] 

burrow.toml file content
--------------------------

[GenesisDoc]
  GenesisTime = 2018-06-19T04:09:28Z
  ChainName = "BurrowChain_2BE507"
  [GenesisDoc.GlobalPermissions]
    Roles = []
    [GenesisDoc.GlobalPermissions.Base]
      Perms = 2302
      SetBit = 16383

  [[GenesisDoc.Accounts]]
    Address = "30B96CEC85FED075A452A43CFB51A27BFB146143"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"E191F15D03FDF76138D6B4EE7503CD0110AC3FDDD72A129F6BFF3E30C9976F20\"}"
    Amount = 99999999999999
    Name = "Full_0"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = 16383
        SetBit = 16383

  [[GenesisDoc.Accounts]]
    Address = "33FD006E8619FC7F9F969D6C8B7AF7C261221184"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"27AE53D00C96065B0AD443402ED9E1C978B34257A242B6741E6F9FA626E1125D\"}"
    Amount = 9999999999
    Name = "Participant_0"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = 2118
        SetBit = 2118

  [[GenesisDoc.Validators]]
    Address = "30B96CEC85FED075A452A43CFB51A27BFB146143"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"E191F15D03FDF76138D6B4EE7503CD0110AC3FDDD72A129F6BFF3E30C9976F20\"}"
    Amount = 9999999999
    Name = "Full_0"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "30B96CEC85FED075A452A43CFB51A27BFB146143"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"E191F15D03FDF76138D6B4EE7503CD0110AC3FDDD72A129F6BFF3E30C9976F20\"}"
      Amount = 9999999999

[Tendermint]
  Seeds = ""
  PersistentPeers = ""
  ListenAddress = "tcp://0.0.0.0:46656"
  Moniker = ""
  TendermintRoot = ".burrow"

[Keys]
  GRPCServiceEnabled = true
  AllowBadFilePermissions = false
  RemoteAddress = ""
  KeysDirectory = ".keys"

[RPC]
  [RPC.V0]
    Enabled = true
    [RPC.V0.Server]
      [RPC.V0.Server.bind]
        address = "localhost"
        port = 1337
      [RPC.V0.Server.TLS]
        tls = false
        cert_path = ""
        key_path = ""
      [RPC.V0.Server.CORS]
        enable = false
        allow_credentials = false
        max_age = 0
      [RPC.V0.Server.HTTP]
        json_rpc_endpoint = "/rpc"
      [RPC.V0.Server.web_socket]
        websocket_endpoint = "/socketrpc"
        max_websocket_sessions = 50
        read_buffer_size = 4096
        write_buffer_size = 4096
  [RPC.TM]
    Enabled = true
    ListenAddress = "tcp://localhost:46657"
  [RPC.Profiler]
    Enabled = false
    ListenAddress = "tcp://localhost:6060"
  [RPC.GRPC]
    Enabled = true
    ListenAddress = "localhost:10997"

[Logging]
  ExcludeTrace = false
  NonBlocking = false
  [Logging.RootSink]
    [Logging.RootSink.Output]
      OutputType = "stderr"
      Format = "json"

epm.yaml 
-------------

jobs:

- name: deployStorageK
  deploy:
      contract: idi.sol

- name: setStorageBase
  set:
      val: 5

- name: setStorage
  call:
      destination: $deployStorageK
      function: set
      data:
        - $setStorageBase

- name: queryStorage
  query-contract:
      destination: $deployStorageK
      function: get

idi.sol
------

pragma solidity ^0.4.0;

contract IdisContractsFTW {
  uint storedData;

  function set(uint x) {
    storedData = x;
  }

  function get() constant returns (uint retVal) {
    return storedData;
  }
}

**Comment by compleatang** [comment]
Please upgrade to bos's develop branch which is fixed against burrow's develop branch. Or downgrade to burrow 0.18.0 and bos 0.1.0. (better to upgrade those as these are solidifying).

**Comment by basilji** [comment]
It’s working after upgrading bos with latest version

**Comment by compleatang** [comment]
great. sorry for the hassles but we're through the weeds on the big incongruity changes.
