### ISSUE TITLE
[RPC] How i can get the transcation history from RPC

### ISSUE THREAD

**Issue by Nagaraj007** [hyperledger/burrow#817]
Please include in your bug report:

- [ ] `burrow version` (0.18.0)
- [ ]  'rpc version '(0.7.0/3")
- [ ] operating system details (osx)

  I am trying to send the transaction its working fine and i will get the response has transaction hash 
( TXhash). But i am unable to get the details of particular Txhash and Transaction history from burrow.
I want to know which RPC method is used to get the Txhash and Transaction history details.

**Comment by silasdavis** [comment]
What information in particular are you after from a transaction - can you describe the use case?

The rpc/TM `get_block` (46657 by default) returns the Tendermint view of blocks and transactions serialised within: https://github.com/hyperledger/burrow/blob/develop/rpc/service.go#L347.

However recover the transactions themselves you would need to deserialise the transactions from their go-amino encoding which would be tricky without using the go library.

We are actually providing tx metadata over the brand new execution events service, see: https://github.com/hyperledger/burrow/blob/develop/execution/events/pbevents/events.proto#L47. This doesn't provide the transaction, but we are actually storing the entire transaction in state. It would not be difficult to extend this to provide the full transactions by hash.

Just to point out - the transaction won't tell you anything about the state that results in applying it.

**Comment by Nagaraj007** [comment]
I am able to get the transaction hash once the send/transaction is done. if i want to query using transaction hash (Txhash) through JSON RPC method, I am not able to find any method 
 a) Which  method is used in burrow to get the details of Txhash.

  E.g (After the transaction, I ll receive Txhash, I need to check details of transaction using Txhash)

 b) How i can get list of all Txhash in burrow.

**Comment by silasdavis** [comment]
I think our new events RPC will get you want you want: https://github.com/hyperledger/burrow/blob/develop/protobuf/rpcevents.proto. It is based on GRPC so you should be able to use from a variety of languages.

For example usage from Go see our tests: https://github.com/hyperledger/burrow/blob/develop/integration/rpcevents/execution_events_server_test.go 

This allows you to retrieve a full execution trace of 'exactly what happened' for past blocks or for a particular tx. You will also get the full `TxExecution` back from `BroadcastTxSync`
