### ISSUE TITLE
[Logging] Vent and Deploy should use `burrow/logging`

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#866]
- [ ] remove vent custom levelled logger 
- [x] remove logrus from deploy packages and use burrow's logger package.
- [x] TBD whether to remove the formatter (which is suitable for deploy's purposes) or not.

**Comment by silasdavis** [comment]
We are lacking a nice terminal format against burrow's logger. go-kit/log's terminal output is kind of rubbish we should port a version of something like: https://github.com/inconshreveable/log15/blob/master/format.go 

Personally I would like to see:
- Left aligned colourised output of key value in square brackets
- Key-values aligned
- Possibly a default sort order over keys (which we could add to) see sort_logger
- Striped colouring of keys/values
- Generated colours for the same key (by doing a quick hash)
- A custom log format (we have template support) for burrow deploy specifically

We should use prettiest possible format for burrow deploy by default.

**Comment by silasdavis** [comment]
Note: adding vent to this

**Comment by sparstormo** [comment]
Hi! I'll help on this.

**Comment by silasdavis** [comment]
@sparstormo great thanks. I believe our maintainer @phymbert was going to take a look on this. It would be great if he could get you involved.

**Comment by phymbert** [comment]
Hi @sparstormo , I am pleased to review your contribution when you are ready.

**Comment by sparstormo** [comment]
Hi Pierrick! I was at eth Denver last week and so didn't get anything done.
I'll get in there and try to figure out the code base this week.

Thanks!

**Comment by phymbert** [comment]
Good to hear, appreciate your effort.

**Comment by silasdavis** [comment]
closed by #1117
