### ISSUE TITLE
[State] Burrow panics without global permissions address

### ISSUE THREAD

**Issue by knkski** [hyperledger/burrow#908]
Please include in your bug report:

- `burrow version`: master
- `go version`: 1.10
- what you expected to happen: Burrow to handle the global permissions address not existing
- what actually happened: Burrow panicked without the global permission step
- steps to reproduction: Run the tests in this PR: https://github.com/hyperledger/sawtooth-seth/pull/73

The panic in question:

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x9b9cd1]

goroutine 20 [running]:
github.com/hyperledger/burrow/acm/state.GlobalAccountPermissions(0x7f9fbdc30230, 0xc4201b81b8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/project/sawtooth-seth/processor/src/github.com/hyperledger/burrow/acm/state/state.go:122 +0x91
github.com/hyperledger/burrow/execution/evm.HasPermission(0xd8c260, 0xc4201b81b8, 0xd8d160, 0xc4201b81d0, 0x8, 0xc4201b81c8)
	/project/sawtooth-seth/processor/src/github.com/hyperledger/burrow/execution/evm/vm.go:108 +0xee
seth_tp/handler.CreateContractAccount(0xc4201c1590, 0xc4201cd400, 0xc4201b81b8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/project/sawtooth-seth/processor/src/seth_tp/handler/transaction_handlers.go:245 +0x3f3
seth_tp/handler.(*BurrowEVMHandler).Apply(0x13980b0, 0xc4201e4ae0, 0xc4201bff00, 0xc4201c76c0, 0xd8a4e0)
	/project/sawtooth-seth/processor/src/seth_tp/handler/handler.go:110 +0x3ef
github.com/hyperledger/sawtooth-sdk-go/processor.worker(0xc4201beb80, 0xbdda48, 0x10, 0xc4201e4720, 0xc4202001c0, 0xc4201b6660, 0x1, 0x1)
	/project/sawtooth-seth/processor/src/github.com/hyperledger/sawtooth-sdk-go/processor/worker.go:67 +0x340
created by github.com/hyperledger/sawtooth-sdk-go/processor.(*TransactionProcessor).start
	/project/sawtooth-seth/processor/src/github.com/hyperledger/sawtooth-sdk-go/processor/processor.go:140 +0x4b0
```

The unit tests for Seth don't set up the global permissions account, which breaks Burrow. The version we were using (0.17) worked without it set up. The unit tests work with this diff applied:

```diff
115c115,123
< 	return GlobalPermissionsAccount(getter).Permissions()
---
>
> 	global := GlobalPermissionsAccount(getter)
> 	if global == nil {
> 		return permission.AccountPermissions{
> 			Roles: []string{},
> 		}
> 	}
>
> 	return global.Permissions()
```

Would it be possible to have this or a similar fix applied to Burrow to allow running without the global permissions account set up?

**Comment by silasdavis** [comment]
I think this fix would have some unintended consequences since the permissions codes expects the fallback permission account to have all bits in the mask 'set'. We should fallback to `DefaultAccountPermissions` to which the global account is initialised. However this would also need to be handled in the snatives.

I think it might be better to ensure that the global permissions account is always defined. I presume difficulty is you may need hack on your account/address model to get the zero address defined? We may want to handle the global permissions a distinguished piece of state rather than treating it as a pseudo account just because that sort of works....

**Comment by knkski** [comment]
Yeah, the difficulty arises in that if we attempt to set up the global permissions address for the unit tests, `evm.HasPermission` gets called and panics. Not sure how to hack our way around that unless burrow switches to returning an error instead of panicking.

**Comment by silasdavis** [comment]
Sorry about the delay on getting back on this I've been away a lot this month.

In your previous comment are you saying that in the process of setting the global permission address you are hitting the code that panics? Could you link some code? I would have thought you can set up some initial accounts without that being an issue.

Here's where we do that in Burrow: https://github.com/hyperledger/burrow/blob/develop/execution/state.go#L146-L151

**Comment by silasdavis** [comment]
I'm afraid we weren't able to get to the bottom of why Burrow _ought_ to function without a global permissions address defined. Running Burrow without global permissions address is effectively running it partially initialised. I am open to better designs, but haven't been able to reach you @knkski about this so I'm closing for now.
