### ISSUE TITLE
[EVM] BLOCKHASH opcode unimplemented

### ISSUE THREAD

**Issue by knkski** [hyperledger/burrow#909]
- `burrow version`: master
- `go version`: 1.10
- what you expected to happen: To be able to use the `BLOCKHASH` opcode in Seth contracts
- what actually happened: The `BLOCKHASH` opcode is currently a no-op
- steps to reproduction: See vendored files in https://github.com/hyperledger/sawtooth-seth/pull/73

It would be useful to allow implementing the `BLOCKHASH` opcode in Burrow, as Seth provides this functionality (see https://github.com/hyperledger/sawtooth-seth/commit/b5475d45b2a4982fd83df1c7a572c284be65cf19 for where it was introduced to the vendored version of Burrow). The above-mentioned PR un-vendorizes Burrow, but runs into the issue of Burrow not allowing a way to call `GetBlockHash`.

The PR fixes this by overwriting bits of Burrow in the Dockerfile to introduce a `BlockHashGetter` interface used by `Reader`, and adding no-op implementations on relevant structs. This is a hack however, and should be added in Burrow proper. Is this something that could be added to Burrow?

**Comment by silasdavis** [comment]
Thanks, we'll make this change. It seems like this was unimplemented at some point. We should read this from the VM params where it is already defined.
