### ISSUE TITLE
[Core] .burrow and .keys should not be hidden directories

### ISSUE THREAD

**Issue by seanyoung** [hyperledger/burrow#982]
Both the .keys and the .burrow directory are hard to find since they start with a dot, and thus are hidden on unix. This makes them harder to find and affects usability.

**Comment by seanyoung** [comment]
Some ideas for ergonomics:
- Separate tendermint data from burrow state, i.e. `mkdir .burrow/tendermint/ && mv .burrow/{config,data} .burrow/tender/mint`
- burrow configure should output genesis.json by default
- burrow configure should write burrow.toml by default, rather than stdout

**Comment by seanyoung** [comment]
Having .burrow and .keys as hidden directories does help in some situations:
- Blow away .burrow to start with clean slate with existing genesis.json/burrow.toml
- When running burrow spec/configure in test directory means .burrow and .keys does not clutter with test solidity/deploy/nodejs code.
- Changing this means changing our helm charts and changes backward compatibility. In short: the change must be worthwhile else the cost will be too much.

So we're still undecided whether this is a good change or not.

**Comment by silasdavis** [comment]
I think we are ambivalent enough on this to do nothing
