### ISSUE TITLE
[Deploy] mempool-signing in "burrow deploy --mempool-signing" needs a better name

### ISSUE THREAD

**Issue by seanyoung** [hyperledger/burrow#984]
Someone new to blockchain is not going to know what mempool-signing is, and mempool is a very overloaded term.
Please make suggestions for a better name.

burrow deploy --server-signing
burrow deploy --burrow-signing

**Comment by silasdavis** [comment]
This has been open for a while, we've spoken about it a bit, I don't think we have come up with a better name.

--mempool-signing kind of captures two important features:

- We use locking over the local mempool of a node to assign sequence numbers
- It happens at the node not locally

Yes mempool is overloaded, but mempool-signing is probably sufficiently unreserved we can assign our own meaning
