### ISSUE TITLE
Block timestamps wrong when Tendermint is configured to not create empty blocks

### ISSUE THREAD

**Issue by joeriexelmans** [hyperledger/burrow#999]
burrow 0.23.3+2018-12-20T12:00:18Z

Note: Possibly a Tendermint bug.

For every new block, Burrow sets the timestamp of that block to the previous block timestamp + 1 second.
Tendermint can however create more or fewer than one block per second, depending on whether there are transactions, resulting in wrong timestamps. Only the genesis timestamp is correct in this case.

I'm not sure if Burrow has anything to say about the timestamps that are used or if it is strictly a Tendermint thing.

**Comment by silasdavis** [comment]
Thanks for the report.

The time is purely from Tendermint. Looking at the code this seems to me like it is probably an 'as designed' thing. Their implementation of 'BFT time' makes use of time stamps in that are included in commits. Commits are the subject of BFT agreement and contain a time. When `CreateEmptyBlocks` is disabled then the tendermint state machine does not propose blocks in the absence of transactions and there will be no commits.

So when you see the timestamp of the previous block + 1 (I think the +1 is just related to how the median is calculated - do you have 1 validator) that is what BFT time provides - commits are not available for the _current_ block when it is proposed - this is common in tendermint where state hashes and so on run one block behind.

It's difficult to know how they could do better - they need a round of consensus to get determine the BFT time, but if they do a round of consensus they need to store the commits (basically the block).

Times be hard.

Will close for now, feel free to reply here or reopen though.
